#
# Copyright (c) 2025 Elara AI Pty Ltd
# Licensed under the Business Source License 1.1. See LICENSE.md for details.
#
"""East type system — public surface.

Re-exports the value classes, type constructors, type guards, runtime
validation/coercion, and ergonomic constructors so plain-Python code can do:

    from east.types import EastArray, StructType, FloatType, coerce_to, struct
"""

from east.types.coercion import (
    EastTypeError,
    assert_value_of,
    coerce_to,
    explain_value_of,
)
from east.types.construct import (
    array,
    match,
    none,
    some,
    struct,
    variant,
)
from east.types.types import (
    # Type constructors
    ArrayType,
    AsyncFunctionType,
    # Core alias + TypedDicts
    AsyncFunctionTypeValue,
    # Primitive type singletons
    BlobType,
    BooleanType,
    DateTimeType,
    DictType,
    DictValueTypeDef,
    EastType,
    FloatType,
    FunctionType,
    FunctionTypeValue,
    IntegerType,
    MatrixType,
    NeverType,
    NullType,
    OptionType,
    RecursiveType,
    RecursiveTypeRef,
    RefType,
    SetType,
    SomeType,
    StringType,
    StructFieldDef,
    StructType,
    # Type predicates / comparison
    TypeMismatchError,
    VariantCaseDef,
    VariantType,
    VectorType,
    # Helpers for working with types
    case_names,
    case_type,
    case_types,
    field_index,
    field_names,
    field_types,
    first_mutable_path,
    get_option_inner_type,
    # Type guards
    is_array_type,
    is_async_function_type,
    is_blob_type,
    is_boolean_type,
    is_data_type,
    is_datetime_type,
    is_dict_type,
    is_float_type,
    is_function_type,
    is_immutable_type,
    is_integer_type,
    is_matrix_type,
    is_never_type,
    is_null_type,
    is_option_type,
    is_recursive_type,
    is_ref_type,
    is_set_type,
    is_string_type,
    is_struct_type,
    is_subtype,
    is_type_equal,
    is_variant_type,
    is_vector_type,
    recursive_type,
    type_equal,
    type_intersect,
    type_union,
)
from east.types.values import (
    # dtype helpers
    EAST_ELEMENT_TO_DTYPE,
    # value classes
    EastArray,
    EastBlob,
    EastDict,
    EastFunction,
    EastMatrix,
    EastNone,
    EastNull,
    EastOption,
    EastRef,
    EastSet,
    EastSome,
    EastStruct,
    EastValue,
    EastVariant,
    EastVector,
    # singletons / helpers
    deref,
    dtype_matches_element,
    east_null,
    east_ref,
    ensure_utc_datetime,
    # value guards
    is_east_array,
    is_east_blob,
    is_east_dict,
    is_east_matrix,
    is_east_null,
    is_east_option,
    is_east_ref,
    is_east_set,
    is_east_struct,
    is_east_variant,
    is_east_vector,
    # validation / inference
    is_value_of,
    set_ref,
    type_of,
)

__all__ = [
    # --- value classes ---
    "EastValue",
    "EastNull",
    "east_null",
    "EastBlob",
    "EastVector",
    "EastMatrix",
    "EastArray",
    "EastSet",
    "EastDict",
    "EastStruct",
    "EastVariant",
    "EastOption",
    "EastSome",
    "EastNone",
    "EastFunction",
    "EastRef",
    "east_ref",
    "deref",
    "set_ref",
    "ensure_utc_datetime",
    # --- dtype helpers ---
    "EAST_ELEMENT_TO_DTYPE",
    "dtype_matches_element",
    # --- value guards ---
    "is_east_null",
    "is_east_blob",
    "is_east_vector",
    "is_east_matrix",
    "is_east_array",
    "is_east_set",
    "is_east_dict",
    "is_east_struct",
    "is_east_variant",
    "is_east_option",
    "is_east_ref",
    # --- validation / inference ---
    "is_value_of",
    "type_of",
    # --- runtime validation / coercion ---
    "EastTypeError",
    "assert_value_of",
    "explain_value_of",
    "coerce_to",
    # --- ergonomic constructors ---
    "variant",
    "some",
    "none",
    "match",
    "struct",
    "array",
    # --- core type alias + TypedDicts ---
    "EastType",
    "StructFieldDef",
    "VariantCaseDef",
    "DictValueTypeDef",
    "FunctionTypeValue",
    "AsyncFunctionTypeValue",
    # --- primitive type singletons ---
    "NullType",
    "BooleanType",
    "IntegerType",
    "FloatType",
    "StringType",
    "BlobType",
    "DateTimeType",
    "NeverType",
    # --- type constructors ---
    "VectorType",
    "MatrixType",
    "ArrayType",
    "SetType",
    "DictType",
    "RefType",
    "StructType",
    "VariantType",
    "FunctionType",
    "AsyncFunctionType",
    "RecursiveTypeRef",
    "RecursiveType",
    "SomeType",
    "OptionType",
    # --- type helpers ---
    "field_names",
    "field_types",
    "field_index",
    "case_names",
    "case_types",
    "case_type",
    "get_option_inner_type",
    # --- type guards ---
    "is_null_type",
    "is_boolean_type",
    "is_integer_type",
    "is_float_type",
    "is_string_type",
    "is_blob_type",
    "is_datetime_type",
    "is_never_type",
    "is_vector_type",
    "is_matrix_type",
    "is_ref_type",
    "is_array_type",
    "is_set_type",
    "is_dict_type",
    "is_struct_type",
    "is_variant_type",
    "is_function_type",
    "is_async_function_type",
    "is_recursive_type",
    "is_option_type",
    # --- type predicates / comparison ---
    "is_data_type",
    "first_mutable_path",
    "is_immutable_type",
    "recursive_type",
    "type_equal",
    "is_type_equal",
    "is_subtype",
    "type_union",
    "type_intersect",
    "TypeMismatchError",
]
