#!/usr/bin/env python3
#
# Copyright (c) 2025 Elara AI Pty Ltd
# Licensed under the Business Source License 1.1. See LICENSE.md for details.
#
"""Build script for Cython acceleration modules.

Auto-discovers all .pyx files under the east/ package and compiles them
to C extensions in-place. Compiled .so files sit next to their .pyx sources
and are picked up by the import shims in the corresponding .py modules.

Usage:
    python packages/east-py/scripts/build_cython.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def main() -> None:
    # Resolve paths relative to this script's package root
    package_root = Path(__file__).resolve().parent.parent
    east_dir = package_root / "east"

    # Discover all .pyx files
    pyx_files = sorted(east_dir.rglob("*.pyx"))
    if not pyx_files:
        print("No .pyx files found under", east_dir)
        return

    print(f"Found {len(pyx_files)} Cython module(s):")
    for f in pyx_files:
        print(f"  {f.relative_to(package_root)}")

    try:
        from Cython.Build import cythonize
    except ImportError:
        print(
            "\nError: Cython not installed. Install with:\n"
            "  uv pip install 'cython>=3.0.0' 'setuptools>=69.0.0'\n"
            "Or:  uv sync --extra cython --package east-py",
            file=sys.stderr,
        )
        sys.exit(1)

    from setuptools import Distribution, Extension
    from setuptools.command.build_ext import build_ext

    # Build Extension objects
    extensions = []
    for pyx_path in pyx_files:
        # Convert file path to dotted module name
        rel = pyx_path.relative_to(package_root)
        module_name = str(rel.with_suffix("")).replace(os.sep, ".")
        extensions.append(Extension(module_name, [str(pyx_path)]))

    # Cythonize with performance directives
    ext_modules = cythonize(
        extensions,
        compiler_directives={
            "language_level": 3,
            "boundscheck": False,
            "wraparound": False,
        },
    )

    # Build in-place
    dist = Distribution({"ext_modules": ext_modules})
    cmd = build_ext(dist)
    cmd.inplace = True
    cmd.ensure_finalized()

    # Build from the package root so paths resolve correctly
    original_dir = os.getcwd()
    os.chdir(package_root)
    try:
        cmd.run()
    finally:
        os.chdir(original_dir)

    # Clean up intermediate .c files generated by Cython
    removed = 0
    for pyx_path in pyx_files:
        c_file = pyx_path.with_suffix(".c")
        if c_file.exists():
            c_file.unlink()
            removed += 1

    print(f"\nBuild complete. Cython modules compiled in-place ({removed} intermediate .c files removed).")


if __name__ == "__main__":
    main()
