/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Dual-licensed under AGPL-3.0 and commercial license. See LICENSE for details.
 */

/**
 * Blend slot recipe — the workbench assembly surface: target panels with
 * the stacked composition bar (hatched headroom remainder + axis),
 * allocation rows under the event-state grammar, predicted-metric rows
 * with trust chips, the objective/actions foot, and the compare diff
 * table. Bare like Table / Planner — identity chrome is host composition.
 */

import { defineSlotRecipe } from "@chakra-ui/react";

export const blendSlotRecipe = defineSlotRecipe({
    className: "elara-blend",
    slots: [
        "root", "targets", "panel", "panelHead", "panelBadge", "panelTitle", "panelCap",
        "compositionBar", "segment", "headroom", "axis", "axisTick",
        "allocList", "allocRow", "allocGrip", "allocBody", "allocLabel", "allocSublabel",
        "amountInput", "amountText", "share", "pinBadge", "allocAction", "dragGhost",
        "metricList", "metricRow", "metricLabel", "metricValue", "trustChip", "bandText",
        "panelFoot", "objective",
        "diff", "diffRow", "verdict",
    ],
    base: {
        root: { background: "bg.surface" },
        targets: {
            display: "flex",
            gap: "{spacing.4}",
            alignItems: "stretch",
            "&[data-mode=portfolio]": { overflowX: "auto", paddingBottom: "{spacing.2}" },
        },
        panel: {
            flex: "1",
            minWidth: "0",
            display: "flex",
            flexDirection: "column",
            gap: "{spacing.2}",
            padding: "{spacing.4}",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.md}",
            background: "bg.surface",
            /* Compact hosts (#353): the fixed 300px basis yields to the
             * container so the portfolio panel stacks instead of overflowing. */
            "&[data-mode=portfolio]": { minWidth: "min(300px, 100%)", flex: "0 1 300px" },
        },
        panelHead: {
            display: "flex",
            alignItems: "baseline",
            gap: "{spacing.2}",
        },
        panelBadge: {
            fontFamily: "mono",
            fontSize: "10px",
            fontWeight: "700",
            color: "{colors.brand.700}",
            background: "{colors.brandTint}",
            paddingX: "{spacing.1.5}",
            borderRadius: "{radii.xs}",
        },
        panelTitle: {
            fontFamily: "mono",
            fontSize: "11px",
            fontWeight: "600",
            letterSpacing: "0.14em",
            lineHeight: "normal",
            textTransform: "uppercase",
            color: "fg",
        },
        panelCap: {
            marginLeft: "auto",
            fontFamily: "mono",
            fontSize: "10px",
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        /* Stacked composition — segments per allocation, hatched headroom. */
        compositionBar: {
            display: "flex",
            height: "22px",
            borderRadius: "{radii.sm}",
            overflow: "hidden",
            borderWidth: "1px",
            borderColor: "border.subtle",
        },
        segment: {
            height: "100%",
            "&[data-state=committed]": { background: "{colors.brand.500}" },
            "&[data-state=added]": {
                background: "{colors.brand.200}",
                backgroundImage: "repeating-linear-gradient(135deg, transparent 0 4px, {colors.brand.300} 4px 6px)",
            },
            "&[data-state=removed]": {
                background: "bg.warning.subtle",
                backgroundImage: "repeating-linear-gradient(135deg, transparent 0 4px, {colors.status.warn} 4px 5px)",
                opacity: "0.7",
            },
            "&[data-state=model]": { background: "{colors.brand.100}" },
            "& + &": { borderLeftWidth: "1px", borderLeftColor: "{colors.white}" },
        },
        headroom: {
            height: "100%",
            backgroundImage: "repeating-linear-gradient(45deg, {colors.border.subtle} 0 1px, transparent 1px 7px)",
        },
        axis: {
            display: "flex",
            justifyContent: "space-between",
            fontFamily: "mono",
            fontSize: "9px",
            color: "fg.subtle",
            fontVariantNumeric: "tabular-nums",
        },
        axisTick: {},
        allocList: {
            display: "flex",
            flexDirection: "column",
            gap: "{spacing.1}",
        },
        allocRow: {
            display: "flex",
            alignItems: "center",
            gap: "{spacing.2}",
            paddingX: "{spacing.2}",
            paddingY: "{spacing.1.5}",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.sm}",
            "&[data-state=added]": { borderStyle: "dashed", borderColor: "{colors.brand.600}" },
            "&[data-state=removed]": { opacity: "0.55", textDecoration: "line-through" },
            "&[data-draggable]": { cursor: "grab" },
            "&[data-dragging]": { opacity: "0.4" },
        },
        allocGrip: {
            color: "fg.subtle",
            fontSize: "9px",
            flexShrink: "0",
            opacity: "0",
            transition: "opacity {durations.fast}",
            "[data-draggable]:hover &": { opacity: "1" },
        },
        allocBody: {
            flex: "1",
            minWidth: "0",
            display: "flex",
            flexDirection: "column",
        },
        allocLabel: {
            fontFamily: "mono",
            fontSize: "{fontSizes.control}",
            fontWeight: "600",
            color: "fg",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        allocSublabel: {
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.08em",
            lineHeight: "normal",
            textTransform: "uppercase",
            color: "fg.subtle",
        },
        amountInput: {
            width: "76px",
            fontFamily: "mono",
            fontSize: "{fontSizes.control}",
            fontVariantNumeric: "tabular-nums",
            textAlign: "right",
            color: "fg",
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "{radii.sm}",
            paddingX: "{spacing.1.5}",
            paddingY: "2px",
            outline: "none",
            _focusVisible: { borderColor: "border.focus" },
        },
        amountText: {
            fontFamily: "mono",
            fontSize: "{fontSizes.control}",
            fontVariantNumeric: "tabular-nums",
            color: "fg",
        },
        share: {
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            fontVariantNumeric: "tabular-nums",
            whiteSpace: "nowrap",
            minWidth: "56px",
            textAlign: "right",
        },
        pinBadge: {
            color: "fg.muted",
            fontSize: "10px",
            flexShrink: "0",
        },
        allocAction: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: "10px",
            color: "fg.muted",
            background: "transparent",
            border: "none",
            padding: "2px",
            cursor: "pointer",
            opacity: "0",
            transition: "opacity {durations.fast}",
            "[data-state]:hover > &": { opacity: "1" },
            "&:hover": { color: "fg.danger" },
        },
        /* (The empty-destination affordance moved to the shared `dropHint`
           recipe (#267) — the renderer mounts the shared `DropHint`.) */
        dragGhost: {
            fontFamily: "mono",
            fontSize: "{fontSizes.control}",
            fontWeight: "600",
            color: "fg",
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "{radii.sm}",
            boxShadow: "md",
            paddingX: "{spacing.2}",
            paddingY: "2px",
        },
        metricList: {
            borderTopWidth: "1px",
            borderTopColor: "border.subtle",
            paddingTop: "{spacing.2}",
            display: "flex",
            flexDirection: "column",
            gap: "{spacing.1}",
        },
        metricRow: {
            display: "flex",
            alignItems: "baseline",
            gap: "{spacing.2}",
        },
        metricLabel: {
            fontFamily: "mono",
            fontSize: "10px",
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "fg.muted",
            flex: "1",
        },
        metricValue: {
            fontFamily: "mono",
            fontSize: "{fontSizes.control}",
            fontWeight: "600",
            color: "fg",
            fontVariantNumeric: "tabular-nums",
        },
        trustChip: {
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.06em",
            color: "fg.subtle",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.full}",
            paddingX: "{spacing.1.5}",
        },
        bandText: {
            fontFamily: "mono",
            fontSize: "9px",
            color: "fg.subtle",
            fontVariantNumeric: "tabular-nums",
        },
        // The foot anchors to the panel bottom; the shared `commitBar` slots
        // supply the rule, grid, and button chrome (#266).
        panelFoot: {
            marginTop: "auto",
        },
        objective: {
            fontFamily: "mono",
            fontSize: "10px",
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "fg.muted",
        },
        /* (The action buttons moved to the shared `commitBar` slots (#266) —
           Apply = btnPrimary, Discard = btnDanger, Reset = btn — so the
           apply/discard surface reads as the same chrome family as the
           Planner review foot and the DecisionQueue staged footer.) */
        /* Compare foot — derived diff table + verdict. */
        diff: {
            marginTop: "{spacing.3}",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.md}",
            overflow: "hidden",
        },
        diffRow: {
            display: "grid",
            gridTemplateColumns: "2fr 1fr 1fr 1fr",
            gap: "{spacing.2}",
            paddingX: "{spacing.3}",
            paddingY: "{spacing.1.5}",
            fontFamily: "mono",
            fontSize: "{fontSizes.control}",
            color: "fg",
            fontVariantNumeric: "tabular-nums",
            borderBottomWidth: "1px",
            borderBottomColor: "border.subtle",
            "&:last-of-type": { borderBottomWidth: "0" },
            "&[data-head]": {
                fontSize: "10px",
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: "fg.muted",
                background: "bg.panel",
            },
            "& [data-delta]": { fontWeight: "600" },
        },
        verdict: {
            paddingX: "{spacing.3}",
            paddingY: "{spacing.2}",
            fontFamily: "mono",
            fontSize: "10px",
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "fg.muted",
            background: "bg.panel",
            borderTopWidth: "1px",
            borderTopColor: "border.subtle",
        },
    },
});
