/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Dual-licensed under AGPL-3.0 and commercial license. See LICENSE for details.
 */

/**
 * Flowchart slot recipe — the state-transition flowchart per the
 * `Flowchart` design spec: 44px eyebrow (slice cluster left; orientation
 * segment + freshness chip right), body canvas (lane bands, node cards,
 * H/V links), 38px derived-count footer. Node cards are 116×40 r6 with a
 * mono 12/700 code line and a 10.5px muted label; hover cards are paper /
 * rule-strong / shadow-md / r6; the inspector floats at 320px.
 */

import { defineSlotRecipe } from "@chakra-ui/react";

export const flowchartSlotRecipe = defineSlotRecipe({
    className: "elara-flowchart",
    slots: [
        "root", "eyebrow", "eyebrowLeft", "eyebrowRight",
        "orientationSegment", "freshnessChip", "freshnessDot", "freshnessDate",
        "body", "scroll", "canvasWrap",
        "node", "ghostNode", "nodeCode", "nodeLabel", "nodeBadge",
        "legend", "legendTitle", "legendRow",
        "minimap",
        "footer", "footerStrong", "footerNeg", "footerSplit",
        "hoverCard", "hoverHead", "hoverCode", "hoverKind",
        "hoverRow", "hoverRowKey", "hoverRowVal", "hoverFoot",
        "inspector", "inspectorHead", "inspectorEyebrow", "inspectorTitle",
        "inspectorSubtitle", "inspectorEvidence", "inspectorEvidenceLabel",
        "inspectorEvidenceValue", "inspectorEvidenceUnit", "inspectorMeta",
        "inspectorFields", "inspectorFieldsLabel", "inspectorFieldRow",
        "inspectorFieldKey", "inspectorFieldVal", "inspectorChips", "inspectorChip",
        "inspectorNotes",
    ],
    base: {
        /* Bare like Table / Planner — identity chrome is host composition. */
        root: {
            background: "bg.surface",
            display: "flex",
            flexDirection: "column",
            minHeight: 0,
            position: "relative",
        },

        /* ── eyebrow — one row, 44px, never wraps ─────────────────────── */
        eyebrow: {
            height: "44px",
            flexShrink: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: "3",
            paddingX: "3",
            borderBottomWidth: "1px",
            borderColor: "border.subtle",
            overflow: "hidden",
        },
        eyebrowLeft: {
            display: "flex",
            alignItems: "center",
            gap: "2",
            minWidth: 0,
            flex: "1 1 auto",
            overflow: "hidden",
        },
        /* Right zone, fixed: orientation segment then the freshness chip. */
        eyebrowRight: {
            display: "flex",
            alignItems: "center",
            gap: "2",
            flexShrink: 0,
        },
        orientationSegment: {
            display: "flex",
            alignItems: "stretch",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "4px",
            overflow: "hidden",
            "& > button": {
                fontFamily: "mono",
                fontSize: "10px",
                fontWeight: "600",
                letterSpacing: "0.5px",
                paddingX: "2",
                paddingY: "1",
                color: "fg.muted",
                background: "bg.panel",
                cursor: "pointer",
                _hover: { color: "fg" },
            },
            "& > button[data-active]": {
                background: "bg.surface",
                color: "fg",
            },
            "& > button + button": {
                borderLeftWidth: "1px",
                borderColor: "border.subtle",
            },
        },
        freshnessChip: {
            display: "flex",
            alignItems: "center",
            gap: "1.5",
            fontFamily: "mono",
            fontSize: "10px",
            fontWeight: "600",
            color: "fg.muted",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "full",
            paddingX: "2.5",
            paddingY: "1",
            whiteSpace: "nowrap",
        },
        freshnessDot: {
            width: "6px",
            height: "6px",
            borderRadius: "full",
            background: "status.pos",
            flexShrink: 0,
        },
        freshnessDate: { color: "fg.subtle", fontWeight: "400" },

        /* ── body ─────────────────────────────────────────────────────── */
        body: {
            flex: "1 1 0%",
            minHeight: 0,
            position: "relative",
        },
        scroll: {
            position: "absolute",
            inset: 0,
            overflow: "auto",
        },
        canvasWrap: {
            position: "relative",
        },

        /* ── node cards — 116×40, r6, mono code + muted label ─────────── */
        node: {
            position: "absolute",
            boxSizing: "border-box",
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "6px",
            padding: "4px 10px",
            cursor: "pointer",
            "&[data-selected]": {
                borderWidth: "1.5px",
                borderColor: "brand.600",
            },
        },
        ghostNode: {
            position: "absolute",
            boxSizing: "border-box",
            background: "bg.surface",
            borderWidth: "1px",
            borderStyle: "dashed",
            borderColor: "status.neg",
            borderRadius: "6px",
            padding: "4px 10px",
            cursor: "pointer",
            "& > div:first-of-type": { color: "status.neg" },
        },
        nodeCode: {
            fontFamily: "mono",
            fontSize: "12px",
            fontWeight: "700",
            lineHeight: "1.3",
            color: "fg",
            display: "flex",
            alignItems: "center",
            gap: "6px",
        },
        nodeLabel: {
            fontSize: "10.5px",
            color: "fg.muted",
            lineHeight: "1.1",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        nodeBadge: {
            marginLeft: "auto",
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            color: "fg.subtle",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "3px",
            padding: "0 3px",
            lineHeight: "1.4",
            whiteSpace: "nowrap",
            "& + &": { marginLeft: "4px" },
        },

        /* ── legend ───────────────────────────────────────────────────── */
        legend: {
            position: "absolute",
            left: "16px",
            bottom: "16px",
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "6px",
            padding: "10px 14px",
            display: "flex",
            flexDirection: "column",
            gap: "6px",
        },
        legendTitle: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "2px",
            textTransform: "uppercase",
            color: "fg.subtle",
            marginBottom: "2px",
        },
        legendRow: {
            display: "flex",
            alignItems: "center",
            gap: "8px",
            fontSize: "10.5px",
            color: "fg.muted",
        },

        /* ── minimap ──────────────────────────────────────────────────── */
        minimap: {
            position: "absolute",
            right: "16px",
            bottom: "16px",
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "6px",
            padding: "6px",
            lineHeight: 0,
        },

        /* ── footer — 38px, derived count only ────────────────────────── */
        footer: {
            height: "38px",
            flexShrink: 0,
            display: "flex",
            alignItems: "center",
            gap: "1.5",
            paddingX: "3",
            borderTopWidth: "1px",
            borderColor: "border.subtle",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            overflow: "hidden",
        },
        footerStrong: { color: "fg", fontWeight: "700" },
        footerNeg: { color: "status.neg", fontWeight: "600" },
        footerSplit: { marginLeft: "auto", color: "fg.subtle" },

        /* ── hover card — paper · rule-strong · shadow-md · r6 ────────── */
        hoverCard: {
            position: "absolute",
            zIndex: 10,
            width: "260px",
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "6px",
            boxShadow: "md",
            paddingBottom: "6px",
            pointerEvents: "auto",
        },
        hoverHead: {
            display: "flex",
            alignItems: "baseline",
            justifyContent: "space-between",
            gap: "2",
            padding: "8px 12px 6px",
            borderBottomWidth: "1px",
            borderColor: "border.subtle",
        },
        hoverCode: {
            fontFamily: "mono",
            fontSize: "12px",
            fontWeight: "700",
            color: "fg",
        },
        hoverKind: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "1px",
            textTransform: "uppercase",
            color: "fg.subtle",
        },
        /* key/value glance rows — numerals mono tabular */
        hoverRow: {
            display: "flex",
            gap: "3",
            padding: "3px 12px",
            fontSize: "10.5px",
        },
        hoverRowKey: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "1px",
            textTransform: "uppercase",
            color: "fg.subtle",
            width: "64px",
            flexShrink: 0,
            paddingTop: "1px",
        },
        hoverRowVal: {
            color: "fg",
            fontVariantNumeric: "tabular-nums",
            minWidth: 0,
        },
        /* paper-2 footer with the keyboard route */
        hoverFoot: {
            marginTop: "4px",
            padding: "5px 12px 0",
            borderTopWidth: "1px",
            borderColor: "border.subtle",
            background: "bg.panel",
            fontFamily: "mono",
            fontSize: "9px",
            color: "fg.subtle",
            paddingBottom: "5px",
            marginBottom: "-6px",
            borderBottomRadius: "6px",
        },

        /* ── inspector — floats beside the frame, 320px ───────────────── */
        inspector: {
            position: "absolute",
            top: "12px",
            right: "12px",
            bottom: "12px",
            width: "320px",
            zIndex: 9,
            background: "bg.surface",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "6px",
            boxShadow: "md",
            overflow: "auto",
            padding: "14px 16px",
        },
        inspectorHead: {
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            marginBottom: "6px",
            "& > button": {
                cursor: "pointer",
                color: "fg.subtle",
                fontSize: "14px",
                lineHeight: 1,
                _hover: { color: "fg" },
            },
        },
        inspectorEyebrow: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "1.5px",
            textTransform: "uppercase",
            color: "fg.subtle",
        },
        inspectorTitle: {
            fontFamily: "mono",
            fontSize: "16px",
            fontWeight: "700",
            fontVariantNumeric: "tabular-nums",
            color: "fg",
        },
        inspectorSubtitle: {
            fontSize: "11px",
            color: "fg.muted",
            marginTop: "1px",
        },
        inspectorEvidence: {
            marginTop: "12px",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "6px",
            padding: "10px 12px",
            background: "bg.panel",
        },
        inspectorEvidenceLabel: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "1.5px",
            textTransform: "uppercase",
            color: "fg.subtle",
        },
        inspectorEvidenceValue: {
            fontFamily: "mono",
            fontSize: "22px",
            fontWeight: "700",
            fontVariantNumeric: "tabular-nums",
            color: "fg",
            display: "flex",
            alignItems: "baseline",
            gap: "1.5",
        },
        inspectorEvidenceUnit: {
            fontSize: "11px",
            fontWeight: "600",
            color: "fg.muted",
        },
        inspectorMeta: {
            fontSize: "10.5px",
            color: "fg.muted",
            marginTop: "2px",
        },
        inspectorFields: { marginTop: "12px" },
        inspectorFieldsLabel: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "1.5px",
            textTransform: "uppercase",
            color: "fg.subtle",
            marginBottom: "6px",
        },
        inspectorFieldRow: { marginBottom: "8px" },
        inspectorFieldKey: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "1px",
            textTransform: "uppercase",
            color: "fg.muted",
            marginBottom: "2px",
        },
        inspectorFieldVal: {
            fontSize: "11px",
            color: "fg",
            fontVariantNumeric: "tabular-nums",
        },
        inspectorChips: {
            display: "flex",
            flexWrap: "wrap",
            gap: "4px",
        },
        inspectorChip: {
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "4px",
            padding: "1px 6px",
            background: "bg.surface",
        },
        inspectorNotes: {
            marginTop: "12px",
            fontSize: "11px",
            color: "fg.muted",
            lineHeight: "1.45",
        },
    },
});
