/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Dual-licensed under AGPL-3.0 and commercial license. See LICENSE for details.
 */

/** The Roster mock's grid, using shared builder text, draft states and footer. */
import { defineSlotRecipe } from "@chakra-ui/react";
import { fontAwesomeSize } from "../icon-size.js";
import { builderFooter, builderFooterItem } from "./builder-footer.js";
import { planElementDrafted, planElementFocus, planElementSelected, planRowFocus } from "./plan/focus.js";
import { INSPECTOR_SECTION, INSPECTOR_STATUS } from "./inspector.js";
import { moveGhostSlots, moveGhostBase } from "./time/move-ghost.js";

export const rosterBuilderSlotRecipe = defineSlotRecipe({
    className: "east-roster-builder",
    slots: [...moveGhostSlots, "root", "main", "scroll", "grid", "row", "gutter", "head", "shiftHead", "shiftLabel", "time", "group", "groupLabel",
        "rowHead", "eyebrow", "title", "detail", "requirement", "coverageHead", "metric", "coverageBar", "coverageSegment", "coverageTick", "skillLine", "skillCode",
        "cell", "cellHead", "chips", "assignment", "assignmentName", "badge", "flag", "activity", "fit", "grip", "chipAction", "dropStrip", "landing", "openPosition", "proposal", "proposalMark", "proposalName", "proposalReason", "proposalAction",
        "weekCell", "weekValue", "weekFill", "weekFillValue", "issueDot", "delta", "peopleHead", "peopleCell", "agenda", "agendaGroup", "card", "cardHead", "actions", "pane", "paneFoot", "section", "status",
        "footer", "footerItem", "legendItem", "legendSwatch", "toolbarRange", "rangeTitle", "toolbarText", "error", "empty", "picker", "pickerRow", "pickerDot", "summary", "stat", "statValue", "statLabel", "issue", "issueTitle", "issueDetail", "issueActions"],
    base: {
        ...moveGhostBase,
        root: { height: "100%", minHeight: 0, minWidth: 0, display: "flex", flexDirection: "column", background: "bg.surface", color: "fg" },
        main: { flex: 1, minHeight: 0, minWidth: 0, overflow: "hidden", display: "flex", flexDirection: "column" },
        scroll: { flex: 1, minHeight: 0, minWidth: 0, overflow: "auto", overscrollBehavior: "contain" },
        grid: { minWidth: "832px", "&[data-period=week]": { minWidth: "862px" }, "&[data-layout=people]": { minWidth: "1100px" } },
        row: { display: "grid", gridTemplateColumns: "148px repeat(var(--roster-columns), minmax(0, 1fr))", borderBottomWidth: "1px", borderColor: "border.subtle" },
        gutter: { position: "sticky", left: 0, zIndex: 3, background: "bg.surface", borderRightWidth: "1px", borderColor: "border.subtle" },
        head: { position: "sticky", top: 0, zIndex: 5, background: "bg.surface" },
        shiftHead: { minHeight: "52px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "flex-start", textAlign: "left", gap: "4px", padding: "8px 12px", borderLeftWidth: "1px", borderColor: "border.subtle", ...planRowFocus,
            "&[data-week]": { minHeight: "52px", padding: "4px", alignItems: "center", textAlign: "center" }, "&[data-selected]": { background: "brand.subtle" } },
        shiftLabel: { textStyle: "eyebrow", color: "fg.muted", whiteSpace: "nowrap" },
        time: { textStyle: "mono.xs", color: "fg.subtle", whiteSpace: "nowrap" },
        group: { display: "flex", width: "100%", textAlign: "left", alignItems: "center", gap: "8px", minHeight: "38px", padding: "7px 16px", background: "bg.panel", borderBottomWidth: "1px", borderColor: "border.subtle", ...planRowFocus, "& svg": fontAwesomeSize("10px") },
        groupLabel: { textStyle: "h5" },
        rowHead: { padding: "12px 16px", display: "flex", flexDirection: "column", alignItems: "flex-start", gap: "5px", textAlign: "left", ...planRowFocus },
        eyebrow: { textStyle: "caption.eyebrow" },
        title: { textStyle: "body.sm", fontWeight: "semibold", minWidth: 0, overflow: "hidden", textOverflow: "ellipsis" },
        detail: { textStyle: "mono.xs", color: "fg.muted", overflowWrap: "anywhere" },
        requirement: { minWidth: 0, padding: "10px 12px", display: "flex", flexDirection: "column", gap: "7px", borderLeftWidth: "1px", borderColor: "border.subtle", textAlign: "left", ...planRowFocus },
        coverageHead: { display: "flex", flexWrap: "wrap", alignItems: "baseline", gap: "6px", minWidth: 0 },
        metric: { textStyle: "num", "&[data-tone=warning]": { color: "fg.warning" }, "&[data-tone=danger]": { color: "fg.danger" } },
        coverageBar: { height: "10px", position: "relative", background: "bg.subtle", borderRadius: "2px", overflow: "visible" },
        coverageSegment: { position: "absolute", top: 0, bottom: 0, background: "brand.solid", "&[data-kind=agency]": { background: "teal.500" }, "&[data-kind=overtime]": { background: "purple.500" },
            "&[data-kind=requested]": { background: "transparent", border: "1px dashed", borderColor: "teal.500" }, "&[data-kind=open]": { background: "transparent", border: "1px dashed", borderColor: "fg.warning" } },
        coverageTick: { position: "absolute", top: "-2px", bottom: "-2px", borderLeft: "1px solid", borderColor: "fg", pointerEvents: "none" },
        skillLine: { display: "grid", gridTemplateColumns: "22px minmax(0, 1fr) auto auto", alignItems: "baseline", gap: "6px", textStyle: "body.sm", "&[data-tone=warning]": { color: "fg.warning" }, "&[data-tone=success]": { color: "fg.success" } },
        skillCode: { textStyle: "mono.xs", color: "fg.subtle" },
        cell: { position: "relative", minWidth: 0, padding: "8px 8px 10px", borderLeftWidth: "1px", borderColor: "border.subtle", display: "flex", flexDirection: "column", gap: "4px", "& [data-roster-landing]": { display: "none" }, "&[data-drop-active]": { background: "brand.subtle", "& [data-roster-landing]": { display: "flex" } }, "&[data-drop-active][data-roster-landing-tone=warning]": { background: "bg.warning.subtle", outlineColor: "fg.warning" }, "&[data-drop-invalid] [data-roster-landing]": { display: "flex" } },
        cellHead: { textStyle: "mono.xs", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "5px", textAlign: "left", marginBottom: "2px", color: "fg.muted", "&[data-open]": { color: "fg.warning" } },
        chips: { display: "flex", flexDirection: "column", gap: "4px", minWidth: 0 },
        assignment: { display: "flex", alignItems: "center", gap: "5px", minHeight: "26px", padding: "0 6px", minWidth: 0, border: "1px solid", borderColor: "border.subtle", borderRadius: "3px", background: "bg.surface", cursor: "pointer",
            "&[data-added], &[data-moved]": { borderStyle: "dashed" }, "&[data-layout=people]": { flexWrap: "wrap", gap: "3px", padding: "3px", "& [data-roster-assignment-name]": { flexBasis: "60%" }, "& [data-roster-grip]": { display: "none" } },
            "&[data-density=compact]": { minHeight: "22px" }, "&[data-agency]": { background: "bg.panel" }, "&[data-request]": { borderStyle: "dashed", background: "transparent" },
            ...planElementDrafted, ...planElementSelected, ...planElementFocus,
            "&[data-tone=warning]": { borderColor: "fg.warning" }, "&[data-tone=danger]": { borderColor: "fg.danger", background: "bg.danger.subtle" },
            "&[data-removed]": { textDecoration: "line-through", background: "bg.warning.subtle", color: "fg.subtle" }, "&[data-dragging]": { opacity: 0.4 },
            "&:hover [data-roster-grip], &:focus-within [data-roster-grip]": { opacity: 0.45 }, "&:hover [data-roster-chip-action], &:focus-within [data-roster-chip-action]": { opacity: 1 } },
        assignmentName: { textStyle: "body.sm", fontWeight: "medium", flex: 1, minWidth: 0, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
        badge: { textStyle: "mono.xs", fontSize: "label.xs", color: "fg.muted", flexShrink: 0, "&[data-lead]": { color: "brand.fg", fontWeight: "bold" } },
        flag: { "& svg": fontAwesomeSize("9px"), maxWidth: "70px", overflow: "hidden", textOverflow: "ellipsis", flexShrink: 1, textStyle: "mono.xs", fontSize: "label.xs", whiteSpace: "nowrap", color: "fg.warning", "&[data-tone=danger]": { color: "fg.danger" } },
        activity: { textStyle: "mono.xs", minWidth: "22px", padding: "0 3px", border: "1px solid", borderColor: "border.subtle", borderRadius: "2px", "&[data-empty]": { borderStyle: "dashed", color: "fg.faint" } },
        fit: { textStyle: "mono.xs", fontSize: "label.xs", color: "fg.subtle", whiteSpace: "nowrap" },
        grip: { display: "inline-flex", opacity: 0, flexShrink: 0, cursor: "grab", ...fontAwesomeSize("8px"), width: "7px" },
        chipAction: { display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, opacity: 0, color: "fg.subtle", ...fontAwesomeSize("9px"), width: "16px", height: "20px", _hover: { color: "fg" }, _focusVisible: { opacity: 1 }, _hoverNone: { opacity: 1 } },
        dropStrip: { textStyle: "mono.xs", minHeight: "28px", color: "fg.subtle", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", padding: "4px 2px", marginTop: "4px", borderTop: "1px dashed", borderColor: "border.subtle" },
        landing: { textStyle: "mono.xs", minHeight: "26px", padding: "4px 8px", border: "1px dashed", borderColor: "brand.solid", borderRadius: "3px", color: "brand.fg", overflowWrap: "anywhere", "&[data-tone=warning]": { color: "fg.warning", borderColor: "fg.warning", background: "bg.warning.subtle" }, "&[data-tone=danger]": { color: "fg.danger", borderColor: "fg.danger", background: "bg.danger.subtle" } },
        openPosition: { textStyle: "mono.xs", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "6px", border: "1px dashed", borderColor: "fg.warning", padding: "4px 6px", borderRadius: "3px", color: "fg.warning" },
        proposal: { borderStyle: "dashed", borderColor: "border.emphasized", background: "transparent", padding: "0 3px 0 6px", _hover: { borderColor: "fg.subtle" } },
        proposalMark: { color: "brand.fg", fontWeight: "semibold", letterSpacing: "0.1em", textTransform: "uppercase" },
        proposalName: { fontStyle: "italic", color: "fg.muted", textAlign: "left", ...planRowFocus },
        proposalReason: { whiteSpace: "nowrap", flexShrink: 0, fontSize: "label.xs" },
        proposalAction: { opacity: 1, width: "18px", height: "18px", borderRadius: "3px", "&[data-accept]": { border: "1px solid", borderColor: "border.emphasized", background: "bg.surface", color: "fg.success", _hover: { borderColor: "fg.success" } }, _hover: { background: "bg.panel" } },
        weekCell: { padding: "5px 2px", textAlign: "center", borderLeftWidth: "1px", borderColor: "border.subtle", minWidth: 0, ...planRowFocus, "&[data-drop-active]": { background: "brand.subtle" } },
        delta: { textStyle: "mono.xs", marginLeft: "auto", whiteSpace: "nowrap", color: "fg.success", "&[data-tone=warning]": { color: "fg.warning" } },
        weekFill: { height: "3px", background: "bg.subtle", marginTop: "4px", overflow: "hidden" },
        weekFillValue: { height: "100%", background: "brand.solid" },
        issueDot: { width: "4px", height: "4px", borderRadius: "50%", background: "fg.warning", margin: "4px auto 0" },
        weekValue: { textStyle: "mono.xs", "&[data-tone=warning]": { color: "fg.warning" }, "&[data-tone=danger]": { color: "fg.danger" } },
        peopleHead: { padding: "6px 12px", display: "flex", flexDirection: "column", gap: "3px", minHeight: "50px", justifyContent: "center", textAlign: "left", ...planRowFocus, "&[data-tone=warning]": { color: "fg.warning" } },
        peopleCell: { display: "flex", flexDirection: "column", justifyContent: "center", gap: "3px", padding: "6px", borderLeftWidth: "1px", borderColor: "border.subtle", minWidth: 0, "&[data-selected]": { background: "bg.panel" }, "&[data-drop-active]": { background: "brand.subtle" } },
        agenda: { padding: "12px", display: "flex", flexDirection: "column", gap: "16px", minWidth: 0, background: "bg.panel" },
        agendaGroup: { display: "flex", flexDirection: "column", gap: "8px", minWidth: 0 },
        card: { padding: "12px", display: "flex", flexDirection: "column", gap: "8px", border: "1px solid", borderColor: "border.subtle", borderRadius: "sm", background: "bg.surface", minWidth: 0, ...planElementDrafted, ...planElementSelected, ...planElementFocus },
        cardHead: { textStyle: "title.row", textAlign: "left", minWidth: 0, overflowWrap: "anywhere" },
        actions: { display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "center" },
        pane: { display: "flex", flexDirection: "column", minHeight: 0, height: "100%", minWidth: 0 },
        paneFoot: { flexShrink: 0, padding: "12px", borderTopWidth: "1px", borderColor: "border.subtle" },
        section: { ...INSPECTOR_SECTION, gap: "12px" },
        status: INSPECTOR_STATUS,
        footer: builderFooter, footerItem: builderFooterItem,
        legendItem: { display: "inline-flex", alignItems: "center", gap: "5px", flexShrink: 0 },
        legendSwatch: { position: "relative", top: "auto", bottom: "auto", width: "12px", height: "8px", flexShrink: 0, "&[data-kind=needed]": { width: "2px", height: "12px" } },
        toolbarRange: { display: "flex", alignItems: "baseline", gap: "8px", whiteSpace: "nowrap" },
        rangeTitle: { textStyle: "h5", whiteSpace: "nowrap" }, toolbarText: builderFooterItem,
        error: { textStyle: "body.sm", color: "fg.danger", overflowWrap: "anywhere" },
        empty: { padding: "16px", textStyle: "body.sm", color: "fg.muted" },
        picker: { display: "flex", flexDirection: "column", gap: "4px", minWidth: 0 },
        pickerRow: { display: "flex", alignItems: "center", gap: "10px", padding: "8px", minHeight: "36px", textAlign: "left", textStyle: "mono.sm", borderRadius: "sm", "&[data-selected]": { background: "brand.subtle" }, ...planRowFocus },
        pickerDot: { width: "6px", height: "6px", borderRadius: "50%", border: "1px solid", borderColor: "fg.subtle", "&[data-state=published]": { background: "fg.success", borderColor: "fg.success" }, "&[data-state=draft]": { background: "brand.solid", borderColor: "brand.solid" } },
        summary: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "16px", padding: "16px", borderBottomWidth: "1px", borderColor: "border.subtle" },
        stat: { display: "flex", flexDirection: "column", gap: "4px" }, statValue: { textStyle: "num-lg" }, statLabel: { textStyle: "caption.eyebrow" },
        issue: { ...INSPECTOR_SECTION, gap: "6px", borderLeft: "2px solid", borderLeftColor: "fg.warning", "&[data-tone=danger]": { borderLeftColor: "fg.danger" }, "&[data-tone=info]": { borderLeftColor: "brand.solid" } },
        issueTitle: { textStyle: "body.sm", fontWeight: "semibold", textAlign: "left" }, issueDetail: { textStyle: "mono.xs", color: "fg.muted" }, issueActions: { display: "flex", gap: "8px", flexWrap: "wrap" },
    },
});
