/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Dual-licensed under AGPL-3.0 and commercial license. See LICENSE for details.
 */

/**
 * Sheet slot recipe — the planning spreadsheet's visual vocabulary
 * (`Sheet Spec.md` §7, B§11), every value a semantic token so the dark theme
 * comes for free.
 *
 *   - Card: `bg.surface`, no border of its own (the host frames a component,
 *     as with Plan); 120 px bottom pad. One rule per seam: toolbar and
 *     header `border.strong` below, strip and footer `border.subtle` above.
 *   - Header: sticky, two lines — label mono 10/600/.16em uppercase
 *     `fg.subtle`; sub mono 9 `fg.subtle` ellipsised; 1 px `border.subtle`
 *     column dividers; `border.strong` bottom.
 *   - Gutter: 80 px `bg.panel`; row number mono 10 right-aligned in 26 px
 *     (brand 600 for a hit); 18 × 18 r-sm action buttons; 3 px brand bar
 *     when the row is selected.
 *   - Cells: min-height 36, padding 6/10, 1 px `border.subtle` bottom and
 *     right; text 13 `fg`; mono values 12; ghosts `fg.subtle`; unit mono 9.5.
 *   - Selection: 2 px inset brand ring at inset −1; range wash brandTint at
 *     .55; the editor overlays at inset −1 with a 2 px ring (z 10); a parse
 *     error ring in the neg hue (z 11).
 *   - Strip: `bg.panel` band, 6/20 padding; label mono 9/600/.13em uppercase
 *     brand; chips mono 11 (armed: 600 on brandTint + inset ring).
 *   - Footer: 8/20; counts mono 11; key hint mono 10; message mono 10.5
 *     right-aligned; transport mono 10.
 *
 * @packageDocumentation
 */

import { defineSlotRecipe } from "@chakra-ui/react";

export const sheetSlotRecipe = defineSlotRecipe({
    className: "elara-sheet",
    slots: [
        "root", "frame", "card", "body",
        "toolbar", "toolbarCount", "toolbarBadge",
        "header", "headerGutter", "headerCell", "headerLabel", "headerSub",
        "row", "rowBlank", "gutter", "gutterNumber", "gutterButton", "gutterBar",
        "cell", "cellText", "cellMono", "cellWord", "cellNum", "cellUnit", "cellGhost", "cellDot",
        "ring", "rangeWash", "hatch", "nextTarget", "takeButton",
        "editor", "editorField", "editorMirror", "editorGhost", "editorInput", "editorResolve", "editorBadge", "editorError",
        "linkGrid", "half", "halfLabel", "chip", "chipDashed", "chipPicked", "chipMeta", "lockTag", "lockWarn", "arrow",
        "band", "bandRule", "bandPill",
        "strip", "stripLabel", "stripChips", "stripChip", "stripChipOn", "stripChipFlat", "stripMeta", "stripKeys",
        "footer", "footerCounts", "footerHint", "footerMessage", "footerTransport",
        "diagnostic",
    ],
    base: {
        root: {
            display: "flex",
            flexDirection: "column",
            minWidth: "0",
            fontFamily: "body",
            color: "fg",
            fontFeatureSettings: '"tnum" 1',
        },
        frame: {
            display: "flex",
            flexDirection: "column",
            minHeight: "0",
        },
        card: {
            background: "bg.surface",
            overflow: "hidden",
            outline: "none",
            position: "relative",
            minHeight: "0",
        },
        body: {
            paddingBottom: "120px",
        },
        toolbar: {
            display: "flex",
            alignItems: "center",
            gap: "{spacing.3}",
            paddingX: "20px",
            paddingY: "8px",
            background: "bg.surface",
            borderBottomWidth: "1px",
            borderBottomColor: "border.subtle",
            minWidth: "0",
        },
        toolbarCount: {
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        toolbarBadge: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "fg.subtle",
            background: "bg.muted",
            borderRadius: "{radii.sm}",
            paddingX: "6px",
            height: "20px",
            display: "inline-flex",
            alignItems: "center",
            whiteSpace: "nowrap",
        },
        header: {
            display: "grid",
            background: "bg.surface",
            borderBottomWidth: "1px",
            borderBottomColor: "border.strong",
        },
        headerGutter: {
            background: "bg.panel",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
        },
        headerCell: {
            paddingX: "10px",
            paddingY: "7px",
            display: "flex",
            flexDirection: "column",
            gap: "1px",
            overflow: "hidden",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
        },
        headerLabel: {
            fontFamily: "mono",
            fontSize: "10px",
            fontWeight: "600",
            letterSpacing: "0.16em",
            textTransform: "uppercase",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        headerSub: {
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.04em",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        row: {
            display: "grid",
            position: "relative",
            borderBottomWidth: "1px",
            borderBottomColor: "border.subtle",
            "&[data-proposed]": {
                "&::before": {
                    content: '""',
                    position: "absolute",
                    left: "0",
                    right: "0",
                    top: "-1px",
                    borderTopWidth: "1px",
                    borderTopStyle: "dashed",
                    borderTopColor: "border.strong",
                    pointerEvents: "none",
                    zIndex: "3",
                },
            },
        },
        rowBlank: {},
        gutter: {
            paddingX: "4px",
            display: "flex",
            alignItems: "center",
            gap: "3px",
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            background: "bg.panel",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
            cursor: "pointer",
            userSelect: "none",
            position: "relative",
            _hover: { background: "bg.muted", color: "fg.muted" },
        },
        gutterNumber: {
            width: "26px",
            textAlign: "right",
            flex: "none",
            // Breathing room before the ✓ × → buttons: the number is right-aligned, so without it a digit touches the first button.
            marginRight: "3px",
            "&[data-hit]": { color: "brand.solid", fontWeight: "600" },
        },
        gutterButton: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            width: "18px",
            height: "18px",
            flex: "none",
            borderWidth: "1px",
            borderColor: "brand.solid",
            borderRadius: "{radii.sm}",
            color: "brand.solid",
            background: "bg.surface",
            cursor: "pointer",
            fontSize: "9px",
            _hover: { background: "brand.solid", color: "brand.contrast" },
            "&[data-reject]": {
                borderColor: "border.strong",
                color: "fg.subtle",
                _hover: { background: "bg.surface", borderColor: "fg.danger", color: "fg.danger" },
            },
        },
        gutterBar: {
            position: "absolute",
            left: "0",
            top: "0",
            bottom: "0",
            width: "3px",
            background: "brand.solid",
            pointerEvents: "none",
            zIndex: "4",
        },
        cell: {
            position: "relative",
            minHeight: "36px",
            paddingX: "10px",
            paddingY: "6px",
            display: "flex",
            alignItems: "center",
            overflow: "visible",
            cursor: "default",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
            minWidth: "0",
            _hover: { background: "bg.panel" },
        },
        cellText: {
            fontSize: "13px",
            color: "fg",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
            position: "relative",
            zIndex: "1",
        },
        cellMono: {
            fontFamily: "mono",
            fontSize: "12px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            position: "relative",
            zIndex: "1",
        },
        cellWord: {
            fontFamily: "mono",
            fontSize: "10px",
            fontWeight: "600",
            letterSpacing: "0.08em",
            color: "fg.muted",
            textTransform: "uppercase",
            whiteSpace: "nowrap",
            position: "relative",
            zIndex: "1",
        },
        cellNum: {
            marginLeft: "auto",
            fontFamily: "mono",
            fontSize: "12px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            position: "relative",
            zIndex: "1",
        },
        cellUnit: {
            fontFamily: "mono",
            fontSize: "9.5px",
            color: "fg.subtle",
            marginLeft: "4px",
            position: "relative",
            zIndex: "1",
        },
        cellGhost: {
            fontSize: "12.5px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
            position: "relative",
            zIndex: "1",
            "&[data-mono]": { fontFamily: "mono", fontSize: "12px" },
            "&[data-num]": { fontFamily: "mono", fontSize: "12px", marginLeft: "auto" },
        },
        cellDot: {
            width: "6px",
            height: "6px",
            borderRadius: "{radii.full}",
            marginRight: "6px",
            flex: "none",
            position: "relative",
            zIndex: "1",
            background: "fg.subtle",
            "&[data-tone=success]": { background: "status.pos" },
            "&[data-tone=danger]": { background: "status.neg" },
            "&[data-tone=warning]": { background: "status.warn" },
            "&[data-tone=info]": { background: "brand.solid" },
        },
        ring: {
            position: "absolute",
            inset: "-1px",
            boxShadow: "inset 0 0 0 2px var(--chakra-colors-brand-solid)",
            pointerEvents: "none",
            zIndex: "4",
            // The row under the sticky header: the header would cover the ring's top pixel, so it stays inside the cell.
            "[data-first] &": { top: "0" },
        },
        rangeWash: {
            position: "absolute",
            inset: "0",
            background: "brandTint",
            opacity: "0.55",
            pointerEvents: "none",
        },
        hatch: {
            position: "absolute",
            inset: "0",
            pointerEvents: "none",
            backgroundImage: "repeating-linear-gradient(135deg, transparent 0 5px, color-mix(in srgb, var(--chakra-colors-brand-solid) 7%, transparent) 5px 6px)",
        },
        nextTarget: {
            position: "absolute",
            left: "9px",
            right: "9px",
            bottom: "3px",
            borderBottomWidth: "1.5px",
            borderBottomStyle: "dotted",
            borderBottomColor: "brand.solid",
            pointerEvents: "none",
            zIndex: "2",
        },
        takeButton: {
            position: "absolute",
            right: "4px",
            top: "50%",
            transform: "translateY(-50%)",
            zIndex: "5",
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            width: "18px",
            height: "18px",
            borderWidth: "1px",
            borderColor: "brand.solid",
            borderRadius: "{radii.sm}",
            background: "bg.surface",
            color: "brand.solid",
            cursor: "pointer",
            fontSize: "9px",
            _hover: { background: "brand.solid", color: "brand.contrast" },
        },
        editor: {
            position: "absolute",
            left: "-1px",
            right: "-1px",
            top: "-1px",
            minHeight: "calc(100% + 2px)",
            "[data-first] &": { top: "0", minHeight: "calc(100% + 1px)" },
            zIndex: "10",
            background: "bg.surface",
            boxShadow: "inset 0 0 0 2px var(--chakra-colors-brand-solid)",
            display: "flex",
            alignItems: "center",
            gap: "4px",
            paddingX: "10px",
            overflow: "hidden",
        },
        editorField: {
            position: "relative",
            flex: "1",
            minWidth: "36px",
            height: "100%",
            display: "flex",
            alignItems: "center",
        },
        editorMirror: {
            position: "absolute",
            inset: "0",
            display: "flex",
            alignItems: "center",
            pointerEvents: "none",
            whiteSpace: "pre",
            overflow: "hidden",
            fontFamily: "mono",
            fontSize: "12.5px",
        },
        editorGhost: {
            color: "fg.subtle",
        },
        editorInput: {
            width: "100%",
            border: "none",
            outline: "none",
            background: "transparent",
            fontFamily: "mono",
            fontSize: "12.5px",
            color: "fg",
            padding: "0",
            minWidth: "0",
        },
        editorResolve: {
            display: "inline-flex",
            alignItems: "center",
            gap: "5px",
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        editorBadge: {
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.05em",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        editorError: {
            position: "absolute",
            inset: "-1px",
            boxShadow: "inset 0 0 0 2px var(--chakra-colors-status-neg)",
            pointerEvents: "none",
            zIndex: "11",
            "[data-first] &": { top: "0" },
        },
        linkGrid: {
            flex: "1",
            minWidth: "0",
            display: "grid",
            gridTemplateColumns: "minmax(0,1fr) 16px minmax(0,1fr)",
            alignItems: "stretch",
            position: "relative",
            zIndex: "1",
        },
        half: {
            minWidth: "0",
            display: "flex",
            flexWrap: "wrap",
            gap: "4px",
            alignItems: "flex-start",
            alignContent: "flex-start",
            minHeight: "20px",
            "&[data-half=from]": { paddingRight: "3px", justifyContent: "flex-end" },
            "&[data-half=to]": { paddingLeft: "3px" },
        },
        halfLabel: {
            display: "inline-flex",
            alignItems: "center",
            height: "20px",
            fontFamily: "mono",
            fontSize: "8.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "fg.subtle",
        },
        chip: {
            display: "inline-flex",
            alignItems: "center",
            gap: "4px",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.muted",
            background: "bg.muted",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.sm}",
            paddingX: "4px",
            paddingY: "1px",
            whiteSpace: "nowrap",
        },
        chipDashed: {
            display: "inline-flex",
            alignItems: "center",
            gap: "4px",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.subtle",
            background: "transparent",
            borderWidth: "1px",
            borderStyle: "dashed",
            borderColor: "fg.subtle",
            borderRadius: "{radii.sm}",
            paddingX: "4px",
            paddingY: "1px",
            whiteSpace: "nowrap",
            opacity: "0.85",
        },
        chipPicked: {
            display: "inline-flex",
            alignItems: "center",
            fontFamily: "mono",
            fontSize: "10.5px",
            fontWeight: "600",
            color: "brand.contrast",
            background: "brand.solid",
            borderWidth: "1px",
            borderColor: "brand.solid",
            borderRadius: "{radii.sm}",
            paddingX: "4px",
            paddingY: "1px",
            whiteSpace: "nowrap",
        },
        chipMeta: {
            color: "fg.subtle",
            fontSize: "9px",
            letterSpacing: "0.03em",
        },
        lockTag: {
            display: "inline-flex",
            alignItems: "center",
            height: "20px",
            fontFamily: "mono",
            fontSize: "8.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "fg.subtle",
            background: "bg.muted",
            borderRadius: "{radii.sm}",
            paddingX: "6px",
            whiteSpace: "nowrap",
        },
        lockWarn: {
            display: "inline-flex",
            alignItems: "center",
            height: "20px",
            fontFamily: "mono",
            fontSize: "8.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "status.warn",
            background: "bg.warning.subtle",
            borderRadius: "{radii.sm}",
            paddingX: "6px",
            whiteSpace: "nowrap",
        },
        arrow: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            height: "20px",
            color: "fg.subtle",
            fontSize: "10px",
        },
        band: {
            position: "relative",
            height: "22px",
            display: "flex",
            alignItems: "center",
            justifyContent: "flex-start",
            paddingLeft: "84px",
        },
        bandRule: {
            position: "absolute",
            left: "0",
            right: "0",
            top: "50%",
            borderTopWidth: "1px",
            borderTopStyle: "dashed",
            borderTopColor: "border.strong",
            pointerEvents: "none",
        },
        bandPill: {
            position: "relative",
            paddingX: "10px",
            paddingY: "1px",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.sm}",
            background: "bg.surface",
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.06em",
            color: "fg.subtle",
            cursor: "pointer",
            whiteSpace: "nowrap",
        },
        strip: {
            display: "flex",
            alignItems: "center",
            gap: "10px",
            paddingX: "20px",
            paddingY: "6px",
            background: "bg.panel",
            borderTopWidth: "1px",
            borderTopColor: "border.subtle",
            overflow: "hidden",
            minWidth: "0",
        },
        stripLabel: {
            flex: "none",
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "0.13em",
            textTransform: "uppercase",
            color: "brand.solid",
            whiteSpace: "nowrap",
        },
        stripChips: {
            display: "flex",
            alignItems: "center",
            gap: "4px",
            overflow: "hidden",
            minWidth: "0",
        },
        stripChip: {
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.subtle",
            paddingX: "7px",
            paddingY: "1px",
            borderRadius: "{radii.sm}",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
            cursor: "pointer",
            _hover: { background: "bg.muted", color: "fg.muted" },
        },
        stripChipOn: {
            fontFamily: "mono",
            fontSize: "11px",
            fontWeight: "600",
            color: "brand.fg",
            background: "brandTint",
            borderRadius: "{radii.sm}",
            paddingX: "7px",
            paddingY: "1px",
            whiteSpace: "nowrap",
            cursor: "pointer",
            boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--chakra-colors-brand-solid) 40%, transparent)",
            _hover: { boxShadow: "inset 0 0 0 1px var(--chakra-colors-brand-solid)" },
            "&[data-pending]": {
                background: "transparent",
                fontWeight: "400",
                color: "fg.subtle",
                boxShadow: "none",
                borderWidth: "1px",
                borderStyle: "dashed",
                borderColor: "border.strong",
            },
        },
        stripChipFlat: {
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.muted",
            paddingX: "7px",
            paddingY: "1px",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        stripMeta: {
            marginLeft: "auto",
            flex: "none",
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.muted",
            whiteSpace: "nowrap",
        },
        stripKeys: {
            flex: "none",
            fontFamily: "mono",
            fontSize: "9.5px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        footer: {
            display: "flex",
            alignItems: "center",
            gap: "18px",
            paddingX: "20px",
            paddingY: "8px",
            background: "bg.surface",
            borderTopWidth: "1px",
            borderTopColor: "border.subtle",
            minWidth: "0",
        },
        footerCounts: {
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            display: "inline-flex",
            gap: "6px",
            "& [data-tone=success]": { color: "status.pos" },
            "& [data-tone=danger]": { color: "status.neg" },
            "& [data-tone=warning]": { color: "status.warn" },
            "& [data-tone=info]": { color: "status.info" },
        },
        footerHint: {
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            letterSpacing: "0.04em",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        footerMessage: {
            marginLeft: "auto",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        footerTransport: {
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        diagnostic: {
            padding: "20px",
            fontFamily: "mono",
            fontSize: "10px",
            letterSpacing: "0.06em",
            color: "fg.danger",
        },
    },
    variants: {
        size: {
            sm: { cell: { minHeight: "27px", paddingY: "3px", paddingX: "8px" }, headerCell: { paddingY: "4px", paddingX: "8px" } },
            md: {},
            lg: { cell: { minHeight: "42px", paddingY: "9px", paddingX: "12px" }, headerCell: { paddingY: "9px", paddingX: "12px" } },
        },
    },
    defaultVariants: { size: "md" },
});
