/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Dual-licensed under AGPL-3.0 and commercial license. See LICENSE for details.
 */

/**
 * Sheet slot recipe — the planning spreadsheet's visual vocabulary
 * (`Sheet Spec.md` §7, B§11), every value a semantic token so the dark theme
 * comes for free.
 *
 *   - Card: `bg.surface`, no border of its own (the host frames a component,
 *     as with Plan); 120 px bottom pad. One rule per seam: toolbar and
 *     header `border.strong` below, strip and footer `border.subtle` above.
 *   - Header: sticky, two lines — label mono 10/600/.16em uppercase
 *     `fg.subtle`; sub mono 9 `fg.subtle` ellipsised; 1 px `border.subtle`
 *     column dividers; `border.strong` bottom.
 *   - Gutter: 80 px `bg.panel`; row number mono 10 right-aligned in 26 px
 *     (brand 600 for a hit); 18 × 18 r-sm action buttons; 3 px brand bar
 *     when the row is selected.
 *   - Cells: min-height 36, padding 6/10, 1 px `border.subtle` bottom and
 *     right; text 13 `fg`; mono values 12; ghosts `fg.subtle`; unit mono 9.5.
 *   - Selection: 2 px inset brand ring at inset −1; range wash brandTint at
 *     .55; the editor overlays at inset −1 with a 2 px ring (z 10); a parse
 *     error ring in the neg hue (z 11). The ring IS the field chrome: the
 *     common fields it holds (the date field's segments, the number field
 *     and its stepper column, the text input) drop their own border and
 *     focus ring inside it.
 *   - Strip: `bg.panel` band, 6/20 padding; label mono 9/600/.13em uppercase
 *     brand; chips mono 11 (armed: 600 on brandTint + inset ring).
 *   - Footer: 8/20; counts mono 11; key hint mono 10; message mono 10.5
 *     right-aligned; transport mono 10.
 *   - Tabs: 30 px mono 10.5/600/.12em uppercase; active `inset 0 -2px 0`
 *     ink; counts `fg.subtle`; dirty dot 5 px brand; × 14 px → neg;
 *     `+ TAB` 22 px r-sm 1 px `border.strong` mono 9.5/600.
 *   - Context switch: r-md, options mono 10, active brandTint.
 *   - Bands: 22 px; 1 px dashed `border.strong` at 50 %; pill mono 9
 *     `fg.subtle` on `bg.surface` 1 px `border.subtle` r-sm; the lens band's
 *     pill opens on hover (`shadow.xs`) with brand controls.
 *   - A phone (the adaptive contract, #346): the grid scrolls sideways under
 *     a gutter that stays put (`position: sticky`), the toolbar keeps its one
 *     row through its ladder, and on a coarse pointer the small controls grow
 *     (gutter buttons, ✓ take, × close, the band's controls, the context
 *     options, the strip's chips), the editor's type goes to 16 px so a
 *     phone never zooms into it, and the band's controls — hover-revealed on
 *     a desktop — stay open where nothing can hover (`_hoverNone`).
 *
 * @packageDocumentation
 */

import { defineSlotRecipe } from "@chakra-ui/react";

export const sheetSlotRecipe = defineSlotRecipe({
    className: "elara-sheet",
    slots: [
        "root", "frame", "card", "body",
        "toolbar", "toolbarRailGroup", "toolbarCluster", "toolbarCount", "toolbarBadge",
        "tabs", "tab", "tabLabel", "tabCount", "tabDot", "tabClose", "tabAdd", "tabMore", "tabRename",
        "contextSwitch", "contextLabel", "contextOption",
        "header", "headerGutter", "headerCell", "headerLabel", "headerSub",
        "row", "rowBlank", "gutter", "gutterNumber", "gutterButton", "gutterBar",
        "cell", "cellText", "cellMono", "cellWord", "cellNum", "cellUnit", "cellGhost", "cellDot",
        "ring", "rangeWash", "hatch", "nextTarget", "takeButton",
        "editor", "editorField", "editorMirror", "editorGhost", "editorInput", "editorResolve", "editorBadge", "editorError",
        "editorNumber", "editorNumberInput", "editorStepper", "editorDate",
        "linkGrid", "half", "halfLabel", "chip", "chipDashed", "chipPicked", "chipMeta", "lockTag", "lockWarn", "arrow",
        "band", "bandRule", "bandPill", "bandControl", "bandCount",
        "strip", "stripLabel", "stripChips", "stripChip", "stripChipOn", "stripChipFlat", "stripMeta", "stripKeys",
        "footer", "footerCounts", "footerHint", "footerMessage", "footerTransport",
        "diagnostic",
    ],
    base: {
        root: {
            display: "flex",
            flexDirection: "column",
            minWidth: "0",
            fontFamily: "body",
            color: "fg",
            fontFeatureSettings: '"tnum" 1',
        },
        frame: {
            display: "flex",
            flexDirection: "column",
            minHeight: "0",
        },
        card: {
            background: "bg.surface",
            overflow: "hidden",
            outline: "none",
            position: "relative",
            minHeight: "0",
        },
        body: {
            paddingBottom: "120px",
        },
        // ONE row, always: nothing wraps and nothing scrolls. The rail group
        // takes whatever is left after the tabs, the context switch and the
        // count, and folds its rail to fit — down to the icon, which is the
        // group's floor. Only past that floor do the tabs shrink (and fold
        // into their `+n` menu); at their own floor they report, and the
        // toolbar climbs its ladder (`data-tight`): 1 drops the count, 2 the
        // context label, 3 the `+ TAB` label and the whole-sheet count, 4
        // caps the tab names, 5 drops the context switch, closes the strip
        // up and drops every count.
        // `clip`, not `hidden`: a scroll container's minimum height is 0,
        // and in a fixed-height frame the column flex would squash the row.
        toolbar: {
            display: "flex",
            flexWrap: "nowrap",
            alignItems: "center",
            gap: "{spacing.3}",
            paddingX: "20px",
            paddingY: "8px",
            background: "bg.surface",
            borderBottomWidth: "1px",
            borderBottomColor: "border.subtle",
            overflow: "clip",
            flexShrink: "0",
        },
        // Basis 0 and a `min-content` floor: the group is the leftover's
        // taker, never a claimant — the flex algorithm hands it the slack
        // and takes from the tabs only once the group is at its floor.
        toolbarRailGroup: {
            display: "flex",
            alignItems: "center",
            justifyContent: "flex-end",
            gap: "{spacing.3}",
            flex: "1 1 0",
            minWidth: "min-content",
        },
        // Inline-size containment: the rail's content never inflates the
        // group's floor (a nested `min-width: auto` would carry every chip
        // up), so the floor is the icon's width. The rail fills the box and
        // hugs its end; past 640px the box stops growing.
        toolbarCluster: {
            display: "flex",
            flex: "1 1 0",
            // The icon rung's trigger: the pill, its gap, the chevron.
            minWidth: "52px",
            maxWidth: "640px",
            contain: "inline-size",
        },
        toolbarCount: {
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            flex: "none",
        },
        toolbarBadge: {
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "fg.subtle",
            background: "bg.muted",
            borderRadius: "{radii.sm}",
            paddingX: "6px",
            height: "20px",
            display: "inline-flex",
            alignItems: "center",
            whiteSpace: "nowrap",
        },
        // The strip never scrolls: it folds its trailing tabs into a `+n` menu.
        tabs: {
            display: "flex",
            alignItems: "stretch",
            gap: "16px",
            minWidth: "0",
            flex: "0 1 auto",
            overflow: "hidden",
            // The toolbar's last rung: the strip closes up and its counts go.
            "[data-tight='5'] &": { gap: "10px" },
        },
        tab: {
            display: "inline-flex",
            alignItems: "center",
            lineHeight: "1",
            gap: "7px",
            height: "30px",
            _coarse: { height: "40px" },
            paddingX: "2px",
            flex: "none",
            color: "fg.subtle",
            fontFamily: "mono",
            fontSize: "10.5px",
            fontWeight: "600",
            letterSpacing: "0.12em",
            textTransform: "uppercase",
            whiteSpace: "nowrap",
            cursor: "pointer",
            userSelect: "none",
            _hover: { color: "fg.muted" },
            "&[data-active]": { boxShadow: "inset 0 -2px 0 var(--chakra-colors-fg)", color: "fg", cursor: "default" },
        },
        // The name ellipsises past 200px, and past 72px once the toolbar's
        // ladder caps it — the count, the dot and the × always show whole.
        tabLabel: {
            minWidth: "0",
            maxWidth: "200px",
            overflow: "hidden",
            textOverflow: "ellipsis",
            "[data-tight='4'] &, [data-tight='5'] &": { maxWidth: "72px" },
        },
        tabCount: {
            color: "fg.subtle",
            fontWeight: "500",
            // The whole-sheet tab's count is the first thing a tight toolbar drops from the strip; at the last rung every count goes.
            "[data-tight='3'] [data-tab='all'] &, [data-tight='4'] [data-tab='all'] &, [data-tight='5'] &": { display: "none" },
        },
        tabDot: {
            width: "5px",
            height: "5px",
            flex: "none",
            borderRadius: "{radii.full}",
            background: "brand.solid",
        },
        tabClose: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            width: "14px",
            height: "14px",
            color: "fg.subtle",
            cursor: "pointer",
            fontSize: "9px",
            _hover: { color: "fg.danger" },
            _coarse: { width: "24px", height: "24px", fontSize: "12px" },
        },
        tabAdd: {
            flex: "none",
            display: "inline-flex",
            alignItems: "center",
            lineHeight: "1",
            gap: "4px",
            alignSelf: "center",
            height: "22px",
            paddingX: "7px",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "{radii.sm}",
            color: "fg.subtle",
            fontFamily: "mono",
            fontSize: "9.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            cursor: "pointer",
            whiteSpace: "nowrap",
            userSelect: "none",
            _hover: { borderColor: "brand.solid", color: "brand.solid" },
            _coarse: { height: "32px", paddingX: "10px" },
            // Icon-only from the toolbar's third rung; the title still says what it does.
            "[data-tight='3'] &, [data-tight='4'] &, [data-tight='5'] &": { gap: "0", paddingX: "5px", "& > [data-slot=tabAddLabel]": { display: "none" } },
        },
        tabMore: {
            display: "inline-flex",
            alignItems: "center",
            lineHeight: "1",
            gap: "5px",
            height: "30px",
            _coarse: { height: "40px" },
            paddingX: "2px",
            flex: "none",
            color: "fg.subtle",
            fontFamily: "mono",
            fontSize: "10.5px",
            fontWeight: "600",
            letterSpacing: "0.12em",
            whiteSpace: "nowrap",
            cursor: "pointer",
            userSelect: "none",
            _hover: { color: "fg.muted" },
        },
        tabRename: {
            width: "120px",
            border: "none",
            outline: "none",
            borderBottomWidth: "2px",
            borderBottomColor: "fg",
            background: "transparent",
            fontFamily: "mono",
            fontSize: "10.5px",
            fontWeight: "600",
            letterSpacing: "0.12em",
            textTransform: "uppercase",
            color: "fg",
            padding: "0",
            // A phone zooms into type under 16 px.
            _coarse: { fontSize: "16px" },
        },
        contextSwitch: {
            display: "flex",
            alignItems: "center",
            gap: "2px",
            height: "30px",
            paddingX: "6px",
            flex: "none",
            borderWidth: "1px",
            borderColor: "border.strong",
            borderRadius: "{radii.md}",
            background: "bg.surface",
            _coarse: { height: "40px" },
            // The toolbar's last rung: the tabs keep the row.
            "[data-tight='5'] &": { display: "none" },
        },
        contextLabel: {
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.1em",
            color: "fg.subtle",
            textTransform: "uppercase",
            marginRight: "4px",
        },
        contextOption: {
            paddingX: "8px",
            paddingY: "2px",
            _coarse: { paddingX: "10px", paddingY: "8px" },
            border: "none",
            background: "transparent",
            borderRadius: "{radii.sm}",
            color: "fg.subtle",
            fontFamily: "mono",
            fontSize: "10px",
            cursor: "pointer",
            _hover: { background: "bg.muted", color: "fg.muted" },
            "&[data-on]": { background: "brandTint", color: "brand.fg", fontWeight: "600" },
        },
        header: {
            display: "grid",
            background: "bg.surface",
            borderBottomWidth: "1px",
            borderBottomColor: "border.strong",
        },
        // The gutters stay put while the grid scrolls sideways (a phone).
        headerGutter: {
            background: "bg.panel",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
            position: "sticky",
            left: "0",
            zIndex: "1",
        },
        headerCell: {
            paddingX: "10px",
            paddingY: "7px",
            display: "flex",
            flexDirection: "column",
            gap: "1px",
            overflow: "hidden",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
        },
        headerLabel: {
            fontFamily: "mono",
            fontSize: "10px",
            lineHeight: "1.3",
            fontWeight: "600",
            letterSpacing: "0.16em",
            textTransform: "uppercase",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        headerSub: {
            fontFamily: "mono",
            fontSize: "9px",
            lineHeight: "1.3",
            letterSpacing: "0.04em",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        row: {
            display: "grid",
            position: "relative",
            borderBottomWidth: "1px",
            borderBottomColor: "border.subtle",
            "&[data-proposed]": {
                "&::before": {
                    content: '""',
                    position: "absolute",
                    left: "0",
                    right: "0",
                    top: "-1px",
                    borderTopWidth: "1px",
                    borderTopStyle: "dashed",
                    borderTopColor: "border.strong",
                    pointerEvents: "none",
                    zIndex: "3",
                },
            },
        },
        rowBlank: {},
        gutter: {
            paddingX: "4px",
            display: "flex",
            alignItems: "center",
            gap: "3px",
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            background: "bg.panel",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
            cursor: "pointer",
            userSelect: "none",
            position: "sticky",
            left: "0",
            zIndex: "5",
            _hover: { background: "bg.muted", color: "fg.muted" },
        },
        gutterNumber: {
            width: "26px",
            textAlign: "right",
            flex: "none",
            // Breathing room before the ✓ × → buttons: the number is right-aligned, so without it a digit touches the first button.
            marginRight: "3px",
            "&[data-hit]": { color: "brand.solid", fontWeight: "600" },
        },
        gutterButton: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            width: "18px",
            height: "18px",
            flex: "none",
            borderWidth: "1px",
            borderColor: "brand.solid",
            borderRadius: "{radii.sm}",
            color: "brand.solid",
            background: "bg.surface",
            cursor: "pointer",
            fontSize: "9px",
            _coarse: { width: "26px", height: "26px", fontSize: "12px" },
            _hover: { background: "brand.solid", color: "brand.contrast" },
            "&[data-reject]": {
                borderColor: "border.strong",
                color: "fg.subtle",
                _hover: { background: "bg.surface", borderColor: "fg.danger", color: "fg.danger" },
            },
        },
        gutterBar: {
            position: "absolute",
            left: "0",
            top: "0",
            bottom: "0",
            width: "3px",
            background: "brand.solid",
            pointerEvents: "none",
            zIndex: "4",
        },
        cell: {
            position: "relative",
            minHeight: "36px",
            paddingX: "10px",
            paddingY: "6px",
            display: "flex",
            alignItems: "center",
            overflow: "visible",
            cursor: "default",
            borderRightWidth: "1px",
            borderRightColor: "border.subtle",
            minWidth: "0",
            _hover: { background: "bg.panel" },
        },
        cellText: {
            fontSize: "13px",
            color: "fg",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
            position: "relative",
            zIndex: "1",
        },
        cellMono: {
            fontFamily: "mono",
            fontSize: "12px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            position: "relative",
            zIndex: "1",
        },
        cellWord: {
            fontFamily: "mono",
            fontSize: "10px",
            fontWeight: "600",
            letterSpacing: "0.08em",
            color: "fg.muted",
            textTransform: "uppercase",
            whiteSpace: "nowrap",
            position: "relative",
            zIndex: "1",
        },
        cellNum: {
            marginLeft: "auto",
            fontFamily: "mono",
            fontSize: "12px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            position: "relative",
            zIndex: "1",
        },
        cellUnit: {
            fontFamily: "mono",
            fontSize: "9.5px",
            color: "fg.subtle",
            marginLeft: "4px",
            position: "relative",
            zIndex: "1",
        },
        cellGhost: {
            fontSize: "12.5px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
            position: "relative",
            zIndex: "1",
            "&[data-mono]": { fontFamily: "mono", fontSize: "12px" },
            "&[data-num]": { fontFamily: "mono", fontSize: "12px", marginLeft: "auto" },
        },
        cellDot: {
            width: "6px",
            height: "6px",
            borderRadius: "{radii.full}",
            marginRight: "6px",
            flex: "none",
            position: "relative",
            zIndex: "1",
            background: "fg.subtle",
            "&[data-tone=success]": { background: "status.pos" },
            "&[data-tone=danger]": { background: "status.neg" },
            "&[data-tone=warning]": { background: "status.warn" },
            "&[data-tone=info]": { background: "brand.solid" },
        },
        ring: {
            position: "absolute",
            inset: "-1px",
            boxShadow: "inset 0 0 0 2px var(--chakra-colors-brand-solid)",
            pointerEvents: "none",
            zIndex: "4",
            // The row under the sticky header: the header would cover the ring's top pixel, so it stays inside the cell.
            "[data-first] &": { top: "0" },
        },
        rangeWash: {
            position: "absolute",
            inset: "0",
            background: "brandTint",
            opacity: "0.55",
            pointerEvents: "none",
        },
        hatch: {
            position: "absolute",
            inset: "0",
            pointerEvents: "none",
            backgroundImage: "repeating-linear-gradient(135deg, transparent 0 5px, color-mix(in srgb, var(--chakra-colors-brand-solid) 7%, transparent) 5px 6px)",
        },
        nextTarget: {
            position: "absolute",
            left: "9px",
            right: "9px",
            bottom: "3px",
            borderBottomWidth: "1.5px",
            borderBottomStyle: "dotted",
            borderBottomColor: "brand.solid",
            pointerEvents: "none",
            zIndex: "2",
        },
        takeButton: {
            position: "absolute",
            right: "4px",
            top: "50%",
            transform: "translateY(-50%)",
            zIndex: "5",
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            width: "18px",
            height: "18px",
            borderWidth: "1px",
            borderColor: "brand.solid",
            borderRadius: "{radii.sm}",
            background: "bg.surface",
            color: "brand.solid",
            cursor: "pointer",
            fontSize: "9px",
            _coarse: { width: "26px", height: "26px", fontSize: "12px" },
            _hover: { background: "brand.solid", color: "brand.contrast" },
        },
        editor: {
            position: "absolute",
            left: "-1px",
            right: "-1px",
            top: "-1px",
            minHeight: "calc(100% + 2px)",
            "[data-first] &": { top: "0", minHeight: "calc(100% + 1px)" },
            zIndex: "10",
            background: "bg.surface",
            boxShadow: "inset 0 0 0 2px var(--chakra-colors-brand-solid)",
            display: "flex",
            alignItems: "center",
            gap: "4px",
            paddingX: "10px",
            overflow: "hidden",
        },
        editorField: {
            position: "relative",
            flex: "1",
            minWidth: "36px",
            height: "100%",
            display: "flex",
            alignItems: "center",
        },
        editorMirror: {
            position: "absolute",
            inset: "0",
            display: "flex",
            alignItems: "center",
            pointerEvents: "none",
            whiteSpace: "pre",
            overflow: "hidden",
            fontFamily: "mono",
            fontSize: "12.5px",
            _coarse: { fontSize: "16px" },
        },
        editorGhost: {
            color: "fg.subtle",
        },
        editorInput: {
            width: "100%",
            border: "none",
            outline: "none",
            background: "transparent",
            fontFamily: "mono",
            fontSize: "12.5px",
            color: "fg",
            padding: "0",
            minWidth: "0",
            // A phone zooms into type under 16 px; the mirror follows, so the ghost keeps its place.
            _coarse: { fontSize: "16px" },
        },
        // The common number field inside the ring: no border, no focus ring
        // of its own, the stepper column kept on its right edge.
        editorNumber: {
            flex: "1",
            minWidth: "0",
            alignSelf: "stretch",
            minHeight: "0",
            borderWidth: "0",
            borderRadius: "0",
            boxShadow: "none",
            background: "transparent",
            _focusWithin: { boxShadow: "none", borderColor: "transparent" },
            _hover: { borderColor: "transparent" },
        },
        editorNumberInput: {
            fontFamily: "mono",
            fontSize: "12.5px",
            fontWeight: "400",
            color: "fg",
            paddingInline: "0",
            paddingBlock: "0",
            minHeight: "0",
            _coarse: { fontSize: "16px", minHeight: "0" },
        },
        editorStepper: {
            marginLeft: "6px",
        },
        // The common date field inside the ring: the segments in the sheet's mono.
        editorDate: {
            flex: "1",
            minWidth: "0",
            display: "flex",
            alignItems: "center",
            fontFamily: "mono",
            fontSize: "12.5px",
            color: "fg",
            _coarse: { fontSize: "16px" },
        },
        editorResolve: {
            display: "inline-flex",
            alignItems: "center",
            gap: "5px",
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        editorBadge: {
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.05em",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        editorError: {
            position: "absolute",
            inset: "-1px",
            boxShadow: "inset 0 0 0 2px var(--chakra-colors-status-neg)",
            pointerEvents: "none",
            zIndex: "11",
            "[data-first] &": { top: "0" },
        },
        linkGrid: {
            flex: "1",
            minWidth: "0",
            display: "grid",
            gridTemplateColumns: "minmax(0,1fr) 16px minmax(0,1fr)",
            alignItems: "stretch",
            position: "relative",
            zIndex: "1",
        },
        half: {
            minWidth: "0",
            display: "flex",
            flexWrap: "wrap",
            gap: "4px",
            alignItems: "flex-start",
            alignContent: "flex-start",
            minHeight: "20px",
            "&[data-half=from]": { paddingRight: "3px", justifyContent: "flex-end" },
            "&[data-half=to]": { paddingLeft: "3px" },
        },
        halfLabel: {
            display: "inline-flex",
            alignItems: "center",
            height: "20px",
            fontFamily: "mono",
            fontSize: "8.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "fg.subtle",
        },
        chip: {
            display: "inline-flex",
            alignItems: "center",
            lineHeight: "14px",
            gap: "4px",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.muted",
            background: "bg.muted",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.sm}",
            paddingX: "4px",
            paddingY: "1px",
            whiteSpace: "nowrap",
        },
        chipDashed: {
            display: "inline-flex",
            alignItems: "center",
            lineHeight: "14px",
            gap: "4px",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.subtle",
            background: "transparent",
            borderWidth: "1px",
            borderStyle: "dashed",
            borderColor: "fg.subtle",
            borderRadius: "{radii.sm}",
            paddingX: "4px",
            paddingY: "1px",
            whiteSpace: "nowrap",
            opacity: "0.85",
        },
        chipPicked: {
            display: "inline-flex",
            alignItems: "center",
            lineHeight: "14px",
            fontFamily: "mono",
            fontSize: "10.5px",
            fontWeight: "600",
            color: "brand.contrast",
            background: "brand.solid",
            borderWidth: "1px",
            borderColor: "brand.solid",
            borderRadius: "{radii.sm}",
            paddingX: "4px",
            paddingY: "1px",
            whiteSpace: "nowrap",
        },
        chipMeta: {
            color: "fg.subtle",
            fontSize: "9px",
            letterSpacing: "0.03em",
        },
        lockTag: {
            display: "inline-flex",
            alignItems: "center",
            height: "20px",
            fontFamily: "mono",
            fontSize: "8.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "fg.subtle",
            background: "bg.muted",
            borderRadius: "{radii.sm}",
            paddingX: "6px",
            whiteSpace: "nowrap",
        },
        lockWarn: {
            display: "inline-flex",
            alignItems: "center",
            height: "20px",
            fontFamily: "mono",
            fontSize: "8.5px",
            fontWeight: "600",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: "status.warn",
            background: "bg.warning.subtle",
            borderRadius: "{radii.sm}",
            paddingX: "6px",
            whiteSpace: "nowrap",
        },
        arrow: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            height: "20px",
            color: "fg.subtle",
            fontSize: "10px",
        },
        band: {
            position: "relative",
            height: "22px",
            display: "flex",
            alignItems: "center",
            justifyContent: "flex-start",
            paddingLeft: "84px",
            _coarse: { height: "32px", paddingLeft: "100px" },
        },
        bandRule: {
            position: "absolute",
            left: "0",
            right: "0",
            top: "50%",
            borderTopWidth: "1px",
            borderTopStyle: "dashed",
            borderTopColor: "border.strong",
            pointerEvents: "none",
        },
        bandPill: {
            position: "relative",
            display: "inline-flex",
            alignItems: "center",
            gap: "8px",
            paddingX: "10px",
            paddingY: "1px",
            borderWidth: "1px",
            borderColor: "border.subtle",
            borderRadius: "{radii.sm}",
            background: "bg.surface",
            fontFamily: "mono",
            fontSize: "9px",
            letterSpacing: "0.06em",
            color: "fg.subtle",
            cursor: "pointer",
            whiteSpace: "nowrap",
            // The lens band's controls open on hover — the only shadow in the sheet (B§11).
            "& [data-slot=bandControl]": { display: "none" },
            "&[data-lens]:hover": { boxShadow: "xs", "& [data-slot=bandControl]": { display: "inline-flex" } },
            // Where nothing can hover they stay open.
            _hoverNone: { "&[data-lens] [data-slot=bandControl]": { display: "inline-flex" } },
            _coarse: { paddingY: "4px", gap: "10px" },
        },
        bandControl: {
            display: "inline-flex",
            alignItems: "center",
            gap: "3px",
            paddingX: "4px",
            _coarse: { paddingX: "8px", paddingY: "4px" },
            borderRadius: "{radii.sm}",
            color: "brand.solid",
            fontWeight: "600",
            cursor: "pointer",
            _hover: { background: "brandTint" },
        },
        bandCount: {
            cursor: "pointer",
        },
        strip: {
            display: "flex",
            alignItems: "center",
            gap: "10px",
            paddingX: "20px",
            paddingY: "6px",
            background: "bg.panel",
            borderTopWidth: "1px",
            borderTopColor: "border.subtle",
            overflow: "hidden",
            minWidth: "0",
        },
        stripLabel: {
            flex: "none",
            fontFamily: "mono",
            fontSize: "9px",
            fontWeight: "600",
            letterSpacing: "0.13em",
            textTransform: "uppercase",
            color: "brand.solid",
            whiteSpace: "nowrap",
        },
        stripChips: {
            display: "flex",
            alignItems: "center",
            gap: "4px",
            overflow: "hidden",
            minWidth: "0",
        },
        stripChip: {
            fontFamily: "mono",
            fontSize: "11px",
            _coarse: { paddingY: "6px" },
            color: "fg.subtle",
            paddingX: "7px",
            paddingY: "1px",
            borderRadius: "{radii.sm}",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
            cursor: "pointer",
            _hover: { background: "bg.muted", color: "fg.muted" },
        },
        stripChipOn: {
            fontFamily: "mono",
            fontSize: "11px",
            _coarse: { paddingY: "6px" },
            fontWeight: "600",
            color: "brand.fg",
            background: "brandTint",
            borderRadius: "{radii.sm}",
            paddingX: "7px",
            paddingY: "1px",
            whiteSpace: "nowrap",
            cursor: "pointer",
            boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--chakra-colors-brand-solid) 40%, transparent)",
            _hover: { boxShadow: "inset 0 0 0 1px var(--chakra-colors-brand-solid)" },
            "&[data-pending]": {
                background: "transparent",
                fontWeight: "400",
                color: "fg.subtle",
                boxShadow: "none",
                borderWidth: "1px",
                borderStyle: "dashed",
                borderColor: "border.strong",
            },
        },
        stripChipFlat: {
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.muted",
            paddingX: "7px",
            paddingY: "1px",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        stripMeta: {
            marginLeft: "auto",
            flex: "none",
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.muted",
            whiteSpace: "nowrap",
        },
        stripKeys: {
            flex: "none",
            fontFamily: "mono",
            fontSize: "9.5px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        footer: {
            display: "flex",
            alignItems: "center",
            gap: "18px",
            paddingX: "20px",
            paddingY: "8px",
            background: "bg.surface",
            borderTopWidth: "1px",
            borderTopColor: "border.subtle",
            minWidth: "0",
        },
        footerCounts: {
            fontFamily: "mono",
            fontSize: "11px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            display: "inline-flex",
            gap: "6px",
            "& [data-tone=success]": { color: "status.pos" },
            "& [data-tone=danger]": { color: "status.neg" },
            "& [data-tone=warning]": { color: "status.warn" },
            "& [data-tone=info]": { color: "status.info" },
        },
        footerHint: {
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            letterSpacing: "0.04em",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        footerMessage: {
            marginLeft: "auto",
            fontFamily: "mono",
            fontSize: "10.5px",
            color: "fg.muted",
            whiteSpace: "nowrap",
            overflow: "hidden",
            textOverflow: "ellipsis",
        },
        footerTransport: {
            fontFamily: "mono",
            fontSize: "10px",
            color: "fg.subtle",
            whiteSpace: "nowrap",
        },
        diagnostic: {
            padding: "20px",
            fontFamily: "mono",
            fontSize: "10px",
            letterSpacing: "0.06em",
            color: "fg.danger",
        },
    },
    variants: {
        size: {
            sm: { cell: { minHeight: "27px", paddingY: "3px", paddingX: "8px" }, headerCell: { paddingY: "4px", paddingX: "8px" } },
            md: {},
            lg: { cell: { minHeight: "42px", paddingY: "9px", paddingX: "12px" }, headerCell: { paddingY: "9px", paddingX: "12px" } },
        },
    },
    defaultVariants: { size: "md" },
});
