/*
 * CLI --profile gate.
 *
 * Spawns the built `east-c` binary over the profile fixtures (generated by
 * tests/generate_fixtures.mjs) and pins the report: a helper called 100 times
 * from a loop appears with its call count and the source location of its
 * Function node, a platform function is an entry of its own placed by the call
 * that reached it, `exec --profile` and EAST_PROFILE profile as `run
 * --profile` does, EAST_PROFILE_INTERVAL prints the report while the work
 * runs, the program's answer is unchanged by profiling, and nothing is printed
 * without the flag or the variable.
 */
#include <east/compat.h>

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef _WIN32
#include <sys/wait.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static char *read_text(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)len + 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, (size_t)len, f);
    buf[rd] = '\0';
    fclose(f);
    return buf;
}

/* Copies a fixture into the working directory, where a unit naming it by a
 * relative path runs. */
static int copy_fixture(const char *fixtures, const char *name)
{
    char from[2048];
    snprintf(from, sizeof(from), "%s/%s", fixtures, name);
    FILE *in = fopen(from, "rb");
    if (!in) return -1;
    FILE *out = fopen(name, "wb");
    if (!out) {
        fclose(in);
        return -1;
    }
    char buf[8192];
    size_t n;
    while ((n = fread(buf, 1, sizeof(buf), in)) > 0)
        fwrite(buf, 1, n, out);
    fclose(in);
    fclose(out);
    return 0;
}

/* Runs one CLI invocation with stdout and stderr captured; returns the exit
 * code (-1 on spawn failure). */
static int run_cli(const char *cmdline, const char *out_path, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    snprintf(full, sizeof(full), "\"%s > \"%s\" 2> \"%s\"\"", cmdline, out_path, err_path);
#else
    snprintf(full, sizeof(full), "%s > \"%s\" 2> \"%s\"", cmdline, out_path, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif
    return rc;
}

/* How many times `needle` occurs in `text`. */
static size_t occurrences(const char *text, const char *needle)
{
    size_t n = 0;
    for (const char *p = text ? strstr(text, needle) : NULL; p; p = strstr(p + 1, needle))
        n++;
    return n;
}

/* The line of `text` that holds `needle`, copied into `buf`, or "" when none
 * does. */
static const char *line_with(const char *text, const char *needle, char *buf, size_t cap)
{
    buf[0] = '\0';
    const char *hit = text ? strstr(text, needle) : NULL;
    if (!hit) return buf;
    const char *start = hit;
    while (start > text && start[-1] != '\n')
        start--;
    const char *end = strchr(hit, '\n');
    size_t len = end ? (size_t)(end - start) : strlen(start);
    if (len >= cap) len = cap - 1;
    memcpy(buf, start, len);
    buf[len] = '\0';
    return buf;
}

static bool sanitizer_clean(const char *err)
{
    return !err ||
           (strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL);
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    const char *bin = argv[1], *fixtures = argv[2];
    char cmd[2048], line[1024];
    unsetenv("EAST_PROFILE");
    unsetenv("EAST_PROFILE_INTERVAL");

    /* With the flag: the answer on stdout, the profile on stderr. */
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/profile_calls.beast2\" --profile", bin, fixtures);
    int rc = run_cli(cmd, "profile_out.txt", "profile_err.txt");
    CHECK(rc == 0, "profile: expected exit 0, got %d", rc);
    char *out = read_text("profile_out.txt");
    char *err = read_text("profile_err.txt");
    CHECK(out && strstr(out, "100") != NULL, "profile: the program must still answer 100, got: %s",
          out ? out : "(none)");
    CHECK(err && strstr(err, "Profile (self time") != NULL, "profile: epilogue header missing:\n%s",
          err ? err : "(none)");
    CHECK(err && strstr(err, "100 calls") != NULL,
          "profile: the helper must be listed with 100 calls:\n%s", err ? err : "(none)");
    CHECK(err && strstr(err, "generate_fixtures.mjs:") != NULL,
          "profile: the helper must be placed at its source location:\n%s", err ? err : "(none)");
    CHECK(err && strstr(err, "still running") == NULL,
          "profile: no report while it runs without EAST_PROFILE_INTERVAL:\n%s",
          err ? err : "(none)");
    CHECK(sanitizer_clean(err), "profile: sanitizer report in CLI stderr:\n%s", err);
    free(out);
    free(err);

    /* Without the flag: the same answer and no profile. */
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/profile_calls.beast2\"", bin, fixtures);
    rc = run_cli(cmd, "noprofile_out.txt", "noprofile_err.txt");
    CHECK(rc == 0, "no profile: expected exit 0, got %d", rc);
    out = read_text("noprofile_out.txt");
    err = read_text("noprofile_err.txt");
    CHECK(out && strstr(out, "100") != NULL, "no profile: the program must answer 100");
    CHECK(err && strstr(err, "Profile") == NULL, "no profile: nothing must be printed:\n%s",
          err ? err : "(none)");
    free(out);
    free(err);

    /* EAST_PROFILE profiles without the flag; "0" does not. */
    setenv("EAST_PROFILE", "1", 1);
    rc = run_cli(cmd, "envprofile_out.txt", "envprofile_err.txt");
    CHECK(rc == 0, "EAST_PROFILE: expected exit 0, got %d", rc);
    err = read_text("envprofile_err.txt");
    CHECK(err && strstr(err, "Profile (self time") != NULL && strstr(err, "100 calls") != NULL,
          "EAST_PROFILE=1: the profile must be printed without the flag:\n%s",
          err ? err : "(none)");
    free(err);
    setenv("EAST_PROFILE", "0", 1);
    rc = run_cli(cmd, "envprofile_out.txt", "envprofile_err.txt");
    CHECK(rc == 0, "EAST_PROFILE=0: expected exit 0, got %d", rc);
    err = read_text("envprofile_err.txt");
    CHECK(err && strstr(err, "Profile") == NULL, "EAST_PROFILE=0: nothing must be printed:\n%s",
          err ? err : "(none)");
    free(err);
    unsetenv("EAST_PROFILE");

    /* A platform function is an entry of its own, named after it and placed
     * by the call that reached it; the helper calling it is another. */
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/profile_platform.beast2\" -p std --profile", bin,
             fixtures);
    rc = run_cli(cmd, "platform_out.txt", "platform_err.txt");
    CHECK(rc == 0, "platform: expected exit 0, got %d", rc);
    out = read_text("platform_out.txt");
    err = read_text("platform_err.txt");
    CHECK(out && occurrences(out, "step") == 3, "platform: the program must log 3 steps, got: %s",
          out ? out : "(none)");
    line_with(err, "console_log", line, sizeof(line));
    CHECK(strstr(line, "3 calls") != NULL &&
              strstr(line, "platform function  called at ") != NULL &&
              strstr(line, "generate_fixtures.mjs:") != NULL,
          "platform: console_log must be its own entry with 3 calls, placed by its call:\n%s",
          err ? err : "(none)");
    CHECK(occurrences(err, "3 calls") == 2,
          "platform: the helper and the platform function must each be listed with 3 calls:\n%s",
          err ? err : "(none)");
    CHECK(sanitizer_clean(err), "platform: sanitizer report in CLI stderr:\n%s", err);
    free(out);
    free(err);

    /* exec --profile: the unit's work profiled, the report after the outcome. */
    CHECK(copy_fixture(fixtures, "profile_calls.beast2") == 0 &&
              copy_fixture(fixtures, "profile_unit.beast2") == 0,
          "exec: the unit's fixtures cannot be copied");
    snprintf(cmd, sizeof(cmd), "\"%s\" exec profile_unit.beast2 --profile", bin);
    rc = run_cli(cmd, "exec_out.txt", "exec_err.txt");
    CHECK(rc == 0, "exec: expected exit 0, got %d", rc);
    err = read_text("exec_err.txt");
    CHECK(err && strstr(err, "Profile (self time") != NULL && strstr(err, "100 calls") != NULL,
          "exec --profile: the profile must be printed:\n%s", err ? err : "(none)");
    CHECK(sanitizer_clean(err), "exec: sanitizer report in CLI stderr:\n%s", err);
    free(err);
    snprintf(cmd, sizeof(cmd), "\"%s\" exec profile_unit.beast2", bin);
    rc = run_cli(cmd, "exec_out.txt", "exec_err.txt");
    CHECK(rc == 0, "exec: expected exit 0, got %d", rc);
    err = read_text("exec_err.txt");
    CHECK(err && strstr(err, "Profile") == NULL,
          "exec: nothing must be printed without --profile:\n%s", err ? err : "(none)");
    free(err);

    /* EAST_PROFILE_INTERVAL: the report so far while the work runs (an
     * interval of a microsecond is due many times over 100 calls), and the
     * final report after it. */
    setenv("EAST_PROFILE_INTERVAL", "0.000001", 1);
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/profile_calls.beast2\" --profile", bin, fixtures);
    rc = run_cli(cmd, "interval_out.txt", "interval_err.txt");
    CHECK(rc == 0, "interval: expected exit 0, got %d", rc);
    out = read_text("interval_out.txt");
    err = read_text("interval_err.txt");
    CHECK(out && strstr(out, "100") != NULL, "interval: the program must still answer 100");
    CHECK(err && strstr(err, "s, still running (self time") != NULL,
          "interval: a report must be printed while the work runs:\n%.2000s", err ? err : "(none)");
    CHECK(err && strstr(err, "\nProfile (self time") != NULL && strstr(err, "100 calls") != NULL,
          "interval: the final report must follow:\n%.2000s", err ? err : "(none)");
    CHECK(sanitizer_clean(err), "interval: sanitizer report in CLI stderr");
    free(out);
    free(err);

    /* An interval that is not a number of seconds is said, and ignored. */
    setenv("EAST_PROFILE_INTERVAL", "often", 1);
    rc = run_cli(cmd, "badinterval_out.txt", "badinterval_err.txt");
    CHECK(rc == 0, "bad interval: expected exit 0, got %d", rc);
    err = read_text("badinterval_err.txt");
    CHECK(err && strstr(err, "Warning: EAST_PROFILE_INTERVAL takes a number of seconds greater "
                             "than 0, not often") != NULL,
          "bad interval: the warning is missing:\n%s", err ? err : "(none)");
    CHECK(err && strstr(err, "still running") == NULL && strstr(err, "Profile (self time") != NULL,
          "bad interval: only the final report is printed:\n%s", err ? err : "(none)");
    free(err);
    unsetenv("EAST_PROFILE_INTERVAL");

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli profile gate: all checks passed\n");
    return 0;
}
