/*
 * CLI --emit gate (issue #507).
 *
 * Spawns the built `east-c` binary over the checked-in IR fixtures in
 * tests/fixtures (generated by tests/generate_fixtures.mjs from the TS
 * side, mirroring east-node-cli/src/runner.spec.ts) and validates the
 * emitted beast2 blobs with east-c's own readers:
 *
 *   1. producer      — `run --emit array`: 2500 emissions land segmented
 *                      + indexed (pages open, exact counts, keyed reads);
 *   2. stream fold   — `run --emit array --stream 0 -i events.beast2`:
 *                      running sums over a TS-paged-written input blob, so
 *                      this case is also a cross-runtime decode of
 *                      TS-writer bytes;
 *   3. dict producer — `run --emit dict`: 1000 ascending pairs decode with
 *                      exact size and keyed content;
 *   4. out-of-order  — `run --emit dict` on a descending emitter: exit
 *                      code 1, the canonical strictly-ascending message on
 *                      stderr, and no index in the aborted output.
 *
 * Run under ASan/LSan (run_leak_check.sh's build-asan configuration) the
 * spawned CLI is itself instrumented; every case scans the child's stderr
 * for sanitizer reports, so an emit-sink lifetime regression — including
 * the error path, where the sink is freed without finish — fails the gate
 * even when the exit code is the expected non-zero.
 */
#include <east/east.h>
#include <east/type_of_type.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef _WIN32
#include <sys/wait.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static uint8_t *read_file(const char *path, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(len > 0 ? (size_t)len : 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, (size_t)len, f);
    fclose(f);
    *out_len = rd;
    return buf;
}

/* Runs one CLI invocation with stderr captured to `err_path`; returns the
 * child's exit code (-1 on spawn failure) and fails the gate if the child's
 * stderr carries a sanitizer report. */
static int run_cli(const char *cmdline, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    /* cmd.exe strips a leading quote unless the whole line is re-quoted. */
    snprintf(full, sizeof(full), "\"%s 2> \"%s\"\"", cmdline, err_path);
#else
    snprintf(full, sizeof(full), "%s 2> \"%s\"", cmdline, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif

    size_t err_len = 0;
    uint8_t *err = read_file(err_path, &err_len);
    if (err) {
        /* NUL-terminate for strstr (read_file allocates at least 1 byte). */
        uint8_t *text = realloc(err, err_len + 1);
        if (text) {
            err = text;
            err[err_len] = '\0';
            CHECK(strstr((const char *)err, "AddressSanitizer") == NULL &&
                      strstr((const char *)err, "LeakSanitizer") == NULL,
                  "sanitizer report in CLI stderr:\n%s", (const char *)err);
        }
        free(err);
    }
    return rc;
}

/* Reads the captured stderr and asserts it contains `needle`. */
static void check_stderr_contains(const char *err_path, const char *needle)
{
    size_t len = 0;
    uint8_t *err = read_file(err_path, &len);
    CHECK(err != NULL, "cannot read %s", err_path);
    if (!err) return;
    uint8_t *text = realloc(err, len + 1);
    if (!text) {
        free(err);
        return;
    }
    text[len] = '\0';
    CHECK(strstr((const char *)text, needle) != NULL, "stderr missing \"%s\"; got:\n%s", needle,
          (const char *)text);
    free(text);
}

/* east_array_get borrows — no release. */
static int64_t integer_at(EastValue *arr, size_t index)
{
    EastValue *v = east_array_get(arr, index);
    return v ? v->data.integer : INT64_MIN;
}

static void test_producer(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_producer.beast2", err[64] = "emit_err_producer.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_producer.beast2\" --emit array -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "producer: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "producer: no output written");
    if (!data) return;

    EastType *at = east_array_type(&east_integer_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, at);
    CHECK(pages != NULL, "producer: emitted blob carries no index");
    if (pages) {
        CHECK(east_beast2_pages_element_count(pages) == 2500, "producer: element count %zu",
              east_beast2_pages_element_count(pages));
        CHECK(east_beast2_pages_segment_count(pages) > 1, "producer: expected multiple segments");
        CHECK(east_beast2_pages_self_contained(pages), "producer: segments not self-contained");
        EastValue *row = east_beast2_pages_element(pages, 1234);
        CHECK(row != NULL && row->data.integer == 2468, "producer: element(1234) wrong");
        if (row) east_value_release(row);
        east_beast2_pages_free(pages);
    }

    EastValue *whole = east_beast2_decode_full(data, len, at);
    CHECK(whole != NULL, "producer: whole decode failed");
    if (whole) {
        CHECK(whole->data.array.len == 2500, "producer: decoded length %zu", whole->data.array.len);
        CHECK(integer_at(whole, 0) == 0 && integer_at(whole, 2499) == 4998,
              "producer: decoded values wrong");
        east_value_release(whole);
    }
    free(data);
}

static void test_stream_fold(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_fold.beast2", err[64] = "emit_err_fold.txt";
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_fold.beast2\" --emit array --stream 0 -i \"%s/events.beast2\" "
             "-o %s",
             bin, fixtures, fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "fold: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "fold: no output written");
    if (!data) return;

    EastType *at = east_array_type(&east_integer_type);
    EastValue *sums = east_beast2_decode_full(data, len, at);
    CHECK(sums != NULL, "fold: decode failed");
    if (sums) {
        CHECK(sums->data.array.len == 2500, "fold: length %zu", sums->data.array.len);
        /* Running sums of [0..2500): prefix k holds k*(k+1)/2. */
        CHECK(integer_at(sums, 0) == 0, "fold: first sum wrong");
        CHECK(integer_at(sums, 99) == 4950, "fold: sum(99) wrong");
        CHECK(integer_at(sums, 2499) == 3123750, "fold: final sum wrong");
        east_value_release(sums);
    }
    free(data);
}

static void test_dict(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_dict.beast2", err[64] = "emit_err_dict.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict.beast2\" --emit dict -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "dict: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "dict: no output written");
    if (!data) return;

    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
    CHECK(pages != NULL, "dict: emitted blob carries no index");
    if (pages) {
        CHECK(east_beast2_pages_element_count(pages) == 1000, "dict: pair count %zu",
              east_beast2_pages_element_count(pages));
        east_beast2_pages_free(pages);
    }

    EastValue *dict = east_beast2_decode_full(data, len, dt);
    CHECK(dict != NULL, "dict: decode failed");
    if (dict) {
        CHECK(dict->data.dict.len == 1000, "dict: decoded size %zu", dict->data.dict.len);
        EastValue *key = east_integer(42);
        /* east_dict_get borrows — no release of the returned value. */
        EastValue *row = east_dict_get(dict, key);
        CHECK(row != NULL && strcmp(row->data.string.data, "row-42") == 0, "dict: get(42) wrong");
        east_value_release(key);
        east_value_release(dict);
    }
    free(data);
}

static void test_dict_out_of_order(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_disorder.beast2", err[64] = "emit_err_disorder.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict_disorder.beast2\" --emit dict -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 1, "disorder: expected exit 1, got %d", rc);
    check_stderr_contains(err, "strictly ascending in East key order");

    /* The aborted sink must not leave an indexed blob behind. */
    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    if (data) {
        EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
        Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
        CHECK(pages == NULL, "disorder: aborted output unexpectedly carries an index");
        if (pages) east_beast2_pages_free(pages);
        free(data);
    }
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    east_type_of_type_init();

    test_producer(argv[1], argv[2]);
    test_stream_fold(argv[1], argv[2]);
    test_dict(argv[1], argv[2]);
    test_dict_out_of_order(argv[1], argv[2]);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli emit gate: all checks passed\n");
    return 0;
}
