/*
 * CLI lazy paged-input gate (#516, #539, #1033).
 *
 * Spawns the built `east-c` binary over the checked-in IR fixtures in
 * tests/fixtures (generated by tests/generate_fixtures.mjs from the TS side).
 * Every collection input opens lazily unless `--decode whole` (or a unit's
 * `decode`) says to decode it whole, whatever it weighs, and the gate pins
 * what the verbose account shows of each — that the input opened lazily, what
 * reading it cost, and what decoding it whole came to:
 *
 *   1. collapsed shape gate — a nested-container element shape opens lazily
 *      AND frozen, from a blob and from a manifest directory, so a write
 *      through a read-out element raises the uniform error instead of landing
 *      (the lazy service itself is pinned by test_paged_value);
 *   2. residency — a lazily opened input is mapped, not read: the verbose
 *      header says so, and the runner's account of the input pins what a
 *      keyed read into a wide input cost — every fence probed once, ONE
 *      segment decoded of many — on every operating system alike. The
 *      `--decode whole` control decodes the input before the program runs and
 *      says what it holds in memory. Peak RSS is only the coarse cross-check
 *      that the lazy run stays below the control: a mapping's residency is the
 *      kernel's decision (a large-folio page cache makes a whole file resident
 *      around a handful of touched pages), so it cannot pin the segment cost,
 *      and it is skipped where it measures nothing — on Windows both runs read
 *      the file whole, and a sanitizer build's shadow memory dominates RSS;
 *   3. what a lazy read came to — an operation the pager cannot serve decodes
 *      the input whole and says what that came to, and reads that land at
 *      random beyond the segments the pager keeps say so;
 *   4. manifests — a manifest-rooted input, as e3 stages one, pages over its
 *      directory's segment files: one segment decoded for a keyed read, the
 *      input weighed by its segments rather than the manifest's own file;
 *   5. exec — a run unit over that input, the protocol e3 runs a task
 *      through and the only form whose stderr reaches its log, reads it as the
 *      unit's `decode` says and gives the account `run -v` gives.
 *
 * The errors a lazily opened input raises — a write to it, a write through a
 * read-out element, a keyed read of a corrupt blob — are runner protocol
 * corpus cases, which test_cli_exec runs.
 *
 * Runs in the ASan tree too (leak-check's ctest pass), where the spawned
 * CLI is itself instrumented; each case scans the child's stderr for
 * sanitizer reports.
 */
#include <east/compat.h>
#include <east/east.h>
#include <east/type_of_type.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef _WIN32
#include <sys/wait.h>
#endif

/* The test binary is built in the same tree as the CLI it spawns, so its own
 * instrumentation says whether the child's RSS means anything. */
#if defined(__SANITIZE_ADDRESS__)
#define RSS_COMPARABLE 0
#elif defined(__has_feature)
#if __has_feature(address_sanitizer)
#define RSS_COMPARABLE 0
#endif
#endif
#ifndef RSS_COMPARABLE
#ifdef _WIN32
#define RSS_COMPARABLE 0
#else
#define RSS_COMPARABLE 1
#endif
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static char *read_text(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(len > 0 ? (size_t)len + 1 : 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, len > 0 ? (size_t)len : 0, f);
    buf[rd] = '\0';
    fclose(f);
    return buf;
}

/* Runs one CLI invocation with stdout and stderr captured; returns the
 * child's exit code (-1 on spawn failure) and fails the gate on a sanitizer
 * report in the child's stderr. An environment variable a case sets rides the
 * command line, so the ASan tree needs no harness plumbing. */
static int run_cli(const char *cmdline, const char *out_path, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    snprintf(full, sizeof(full), "\"%s 1> \"%s\" 2> \"%s\"\"", cmdline, out_path, err_path);
#else
    snprintf(full, sizeof(full), "%s 1> \"%s\" 2> \"%s\"", cmdline, out_path, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif
    char *err = read_text(err_path);
    if (err) {
        CHECK(strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL,
              "sanitizer report in CLI stderr:\n%s", err);
        free(err);
    }
    return rc;
}

static void check_file_contains(const char *path, const char *needle)
{
    char *text = read_text(path);
    CHECK(text != NULL, "cannot read %s", path);
    if (!text) return;
    CHECK(strstr(text, needle) != NULL, "%s missing \"%s\"; got:\n%s", path, needle, text);
    free(text);
}

static void check_file_lacks(const char *path, const char *needle)
{
    char *text = read_text(path);
    CHECK(text != NULL, "cannot read %s", path);
    if (!text) return;
    CHECK(strstr(text, needle) == NULL, "%s holds \"%s\"; got:\n%s", path, needle, text);
    free(text);
}

/* The env prefix that keeps a pager to the one segment it decoded last, so
 * reads that alternate between segments decode each again. `system` runs
 * through the shell on POSIX; on Windows `set VAR=…&&` is the equivalent. */
#ifdef _WIN32
#define ONE_SEGMENT_ENV "set EAST_PAGED_CACHE_BYTES=1&& "
#else
#define ONE_SEGMENT_ENV "EAST_PAGED_CACHE_BYTES=1 "
#endif

static void test_paged_shape_gate(const char *bin, const char *fixtures)
{
    char cmd[2048];
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/paged_nested_mutate.beast2\" -i \"%s/paged_nested.beast2\" -v", bin,
             fixtures, fixtures);
    int rc = run_cli(cmd, "paged_out_nested.txt", "paged_err_nested.txt");
    CHECK(rc == 1, "collapsed gate: expected exit 1, got %d", rc);
    /* The nested-container shape opens lazily AND frozen, so the write
     * through the read-out element raises the uniform error instead of
     * landing in the input. The whole frozen decode refuses the write the same
     * way, so the verbose account is what says the gate admitted the shape. */
    check_file_contains("paged_err_nested.txt",
                        "cannot mutate a frozen value (task inputs are immutable)");
    check_file_contains("paged_err_nested.txt", "input 0: opened lazily");
}

/* A Dict<Integer, String> of `rows` wide rows. */
static EastValue *wide_table(EastType *dt, size_t rows)
{
    EastValue *dict = east_dict_new(dt->data.dict.key, dt->data.dict.value);
    char text[260];
    for (size_t i = 0; i < rows; i++) {
        /* 200-byte rows with a per-row prefix — plain data, no hydration
         * shortcut, and a wire size the process cannot hide in its baseline. */
        int n = snprintf(text, sizeof(text), "row-%zu-", i);
        if (n < 0 || n >= 200) n = 199;
        memset(text + n, 'a' + (int)(i % 26), 200 - (size_t)n);
        text[200] = '\0';
        EastValue *k = east_integer((int64_t)i);
        EastValue *v = east_string(text);
        east_dict_set(dict, k, v);
        east_value_release(k);
        east_value_release(v);
    }
    return dict;
}

/* The rows the wide fixtures hold: keys 0 to WIDE_ROWS - 1. */
#define WIDE_ROWS 160000

/* Writes the wide table of `rows` rows as an uncompressed paged blob (codec
 * none, so wire size is logical size) to `path`; returns the file size or 0
 * on failure. */
static size_t write_wide_table(const char *path, size_t rows)
{
    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    EastValue *dict = wide_table(dt, rows);
    ByteBuffer *buf = east_beast2_encode_paged(dict, dt, EAST_BEAST2_CODEC_NONE);
    east_value_release(dict);
    if (!buf) return 0;
    FILE *f = fopen(path, "wb");
    size_t written = f ? fwrite(buf->data, 1, buf->len, f) : 0;
    if (f) fclose(f);
    size_t len = buf->len;
    byte_buffer_free(buf);
    return written == len ? len : 0;
}

/* Parses "  Peak RSS: <n> MB|KB" from the verbose stderr into bytes; -1 when
 * absent (the runner could not report it). */
static double parse_peak_rss_bytes(const char *err)
{
    const char *p = strstr(err, "Peak RSS:");
    if (!p) return -1;
    double n = 0;
    char unit[8] = {0};
    if (sscanf(p + 9, " %lf %7s", &n, unit) != 2) return -1;
    if (strcmp(unit, "MB") == 0) return n * 1024.0 * 1024.0;
    if (strcmp(unit, "KB") == 0) return n * 1024.0;
    return -1;
}

/* Parses "  input 0: <decoded> of <segments> segments decoded, <fences> fences
 * probed" from the verbose stderr; false when the line is absent. */
static bool parse_paging_account(const char *err, size_t *decoded, size_t *segments, size_t *fences)
{
    const char *p = strstr(err, "input 0: ");
    while (p) {
        unsigned long d = 0, s = 0, f = 0;
        if (sscanf(p, "input 0: %lu of %lu segments decoded, %lu fences probed", &d, &s, &f) == 3) {
            *decoded = (size_t)d;
            *segments = (size_t)s;
            *fences = (size_t)f;
            return true;
        }
        p = strstr(p + 1, "input 0: ");
    }
    return false;
}

/* Whether the line `prefix` starts in `err` ends saying the resident memory
 * decoding the input added — "+<size> resident" — in megabytes when `in_mb`. */
static bool says_resident(const char *err, const char *prefix, bool in_mb)
{
    const char *line = strstr(err, prefix);
    if (!line) return false;
    const char *end = strstr(line, " resident");
    const char *eol = strpbrk(line, "\r\n");
    if (!end || (eol && end > eol) || line[strlen(prefix)] != '+') return false;
    return !in_mb || (end - 2 >= line && strncmp(end - 2, "MB", 2) == 0);
}

/* Whether the verbose account says input 0 was decoded whole as it loaded,
 * and the resident memory that added: in megabytes when `in_mb`. */
static bool reports_decoded_whole(const char *err, bool in_mb)
{
    return says_resident(err, "input 0: decoded whole — ", in_mb);
}

static void test_paged_residency(const char *bin, const char *fixtures, const char *table)
{
    /* The same keyed read twice, each its own process: lazily (the file
     * mapped, one segment decoded), and decoded whole before the program runs
     * (the whole file read and decoded). */
    char cmd[2048];
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_has.beast2\" -i \"%s\" -v", bin, fixtures,
             table);
    int rc = run_cli(cmd, "paged_out_wide.txt", "paged_err_wide.txt");
    CHECK(rc == 0, "paged residency run (lazy): expected exit 0, got %d", rc);
    check_file_contains("paged_out_wide.txt", "true");
    check_file_contains("paged_err_wide.txt", "input 0: opened lazily");

    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_has.beast2\" -i \"%s\" --decode whole -v",
             bin, fixtures, table);
    rc = run_cli(cmd, "paged_out_eager.txt", "paged_err_eager.txt");
    CHECK(rc == 0, "paged residency run (whole): expected exit 0, got %d", rc);
    check_file_contains("paged_out_eager.txt", "true");

    char *lazy_err = read_text("paged_err_wide.txt");
    char *eager_err = read_text("paged_err_eager.txt");
    if (lazy_err && eager_err) {
        CHECK(strstr(eager_err, "opened lazily") == NULL, "--decode whole opened lazily");
        /* What the input holds in memory once decoded whole: tens of
         * megabytes, beside the file's weight. */
        CHECK(reports_decoded_whole(eager_err, RSS_COMPARABLE),
              "--decode whole does not say what the input holds in memory:\n%s", eager_err);
        CHECK(!reports_decoded_whole(lazy_err, false), "the lazy run decoded the input whole");
        /* The exact account: the first keyed read probes every fence once
         * and decodes the one segment the key lands in — never the file. */
        size_t decoded = 0, segments = 0, fences = 0;
        bool accounted = parse_paging_account(lazy_err, &decoded, &segments, &fences);
        CHECK(accounted, "the lazy run reports its paging account:\n%s", lazy_err);
        if (accounted) {
            CHECK(segments >= 8, "wide fixture has too few segments: %zu", segments);
            CHECK(decoded == 1, "keyed read decoded %zu of %zu segments (expected 1)", decoded,
                  segments);
            CHECK(fences == segments, "keyed read probed %zu fences of %zu segments", fences,
                  segments);
        }
        CHECK(strstr(eager_err, "segments decoded") == NULL, "--decode whole reports paging");
        /* The coarse cross-check: the whole decode pays the file's bytes plus
         * every decoded row, so the lazy run must sit below it. */
        double lazy_peak = parse_peak_rss_bytes(lazy_err);
        double eager_peak = parse_peak_rss_bytes(eager_err);
        if (RSS_COMPARABLE && lazy_peak >= 0 && eager_peak >= 0) {
            CHECK(lazy_peak < eager_peak, "lazy peak %.1f MB not below whole peak %.1f MB",
                  lazy_peak / (1024.0 * 1024.0), eager_peak / (1024.0 * 1024.0));
        }
    }
    free(lazy_err);
    free(eager_err);

    /* `--decode lazy` says what the default does; anything else is refused. */
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_has.beast2\" -i \"%s\" --decode lazy -v", bin,
             fixtures, table);
    rc = run_cli(cmd, "paged_out_wide.txt", "paged_err_wide.txt");
    CHECK(rc == 0, "paged residency run (--decode lazy): expected exit 0, got %d", rc);
    check_file_contains("paged_err_wide.txt", "input 0: opened lazily");
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_has.beast2\" -i \"%s\" --decode eager", bin,
             fixtures, table);
    rc = run_cli(cmd, "paged_out_wide.txt", "paged_err_wide.txt");
    CHECK(rc == 1, "--decode eager: expected exit 1, got %d", rc);
    check_file_contains("paged_err_wide.txt", "--decode takes lazy or whole, not eager");

    remove("paged_out_wide.txt");
    remove("paged_err_wide.txt");
    remove("paged_out_eager.txt");
    remove("paged_err_eager.txt");
}

/* What a lazy read came to, when it is not a few segments: an operation the
 * pager cannot serve decodes the input whole — once, saying what that came to
 * — and reads that alternate between segments beyond what the pager keeps
 * decode each again, which the account says, with what decoding it whole would
 * do instead. */
static void test_paged_account(const char *bin, const char *fixtures, const char *table)
{
    char cmd[2048];
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_hydrate.beast2\" -i \"%s\" -v", bin, fixtures,
             table);
    int rc = run_cli(cmd, "account_out.txt", "account_err.txt");
    CHECK(rc == 0, "hydrate: expected exit 0, got %d", rc);
    check_file_contains("account_out.txt", "160000");
    check_file_contains("account_err.txt", "input 0: opened lazily");
    char *err = read_text("account_err.txt");
    if (err) {
        CHECK(says_resident(err, "input 0: decoded whole (an operation the pager cannot serve) — ",
                            RSS_COMPARABLE),
              "the hydrate does not say what the whole decode came to:\n%s", err);
        free(err);
    }

    /* Keys 0 and 159000 in turn, 200 reads, over a pager keeping one
     * segment: each read decodes its segment again. */
    snprintf(cmd, sizeof(cmd),
             ONE_SEGMENT_ENV "\"%s\" run \"%s/paged_scatter.beast2\" -i \"%s\" -v", bin, fixtures,
             table);
    rc = run_cli(cmd, "account_out.txt", "account_err.txt");
    CHECK(rc == 0, "scatter: expected exit 0, got %d", rc);
    check_file_contains("account_out.txt", "200");
    err = read_text("account_err.txt");
    if (err) {
        unsigned long decodes = 0, segments = 0, fences = 0;
        const char *line = strstr(err, "input 0: ");
        bool parsed = false;
        while (line && !parsed) {
            parsed = sscanf(line, "input 0: %lu segment decodes of its %lu segments, %lu fences",
                            &decodes, &segments, &fences) == 3;
            line = strstr(line + 1, "input 0: ");
        }
        CHECK(parsed && decodes == 200 && segments >= 8 && fences == segments,
              "the scattered reads' account (%lu decodes, %lu segments, %lu fences):\n%s", decodes,
              segments, fences, err);
        CHECK(strstr(err, "its reads land at random beyond the segments kept, so decoding it "
                          "whole would decode each once") != NULL,
              "the account does not say decoding it whole would decode each segment once:\n%s",
              err);
        free(err);
    }
    snprintf(cmd, sizeof(cmd),
             ONE_SEGMENT_ENV "\"%s\" run \"%s/paged_scatter.beast2\" -i \"%s\" --decode whole -v",
             bin, fixtures, table);
    rc = run_cli(cmd, "account_out.txt", "account_err.txt");
    CHECK(rc == 0, "scatter (whole): expected exit 0, got %d", rc);
    check_file_contains("account_out.txt", "200");
    check_file_lacks("account_err.txt", "segment decodes");

    remove("account_out.txt");
    remove("account_err.txt");
}

/* Removes a manifest directory: the objects its manifest names, the objects
 * directory, and the manifest. */
static void remove_manifest_dir(const char *path)
{
    char *bytes = NULL;
    FILE *f = fopen(path, "rb");
    long len = 0;
    if (f) {
        fseek(f, 0, SEEK_END);
        len = ftell(f);
        fseek(f, 0, SEEK_SET);
        bytes = malloc(len > 0 ? (size_t)len : 1);
        if (bytes) len = (long)fread(bytes, 1, (size_t)len, f);
        fclose(f);
    }
    EastValue *manifest = NULL;
    if (bytes && east_beast2_read_manifest((uint8_t *)bytes, (size_t)len, &manifest) == 1) {
        char object[1024];
        EastValue *entries = east_struct_get_field_idx(manifest, 5);
        for (size_t i = 0; i <= east_array_len(entries); i++) {
            /* Each segment, then the header. */
            EastValue *hash = i < east_array_len(entries)
                                  ? east_struct_get_field_idx(east_array_get(entries, i), 0)
                                  : east_struct_get_field_idx(manifest, 4);
            snprintf(object, sizeof(object), "%s.segments/%s.beast2", path, hash->data.string.data);
            remove(object);
        }
        east_value_release(manifest);
    }
    free(bytes);
    char dir[1024];
    snprintf(dir, sizeof(dir), "%s.segments", path);
    rmdir(dir);
    remove(path);
}

/* Writes a run unit — `program` on `input`, its value output and its result at
 * the paths given, the input read as `whole` says, as e3 stages one — to
 * `path`. */
static bool write_run_unit(const char *path, const char *program, const char *input,
                           const char *output, const char *result, bool whole)
{
    EastType *unit_t = east_unit_type();
    EastType *work_t = unit_t->data.struct_.fields[0].type;
    EastType *run_t = work_t->data.variant.cases[east_variant_type_case_idx(work_t, "run")].type;
    EastType *output_t = run_t->data.struct_.fields[2].type;
    EastType *decode_t = run_t->data.struct_.fields[3].type;
    EastValue *inputs = east_array_new(&east_string_type);
    EastValue *in = east_string(input);
    east_array_push(inputs, in);
    east_value_release(in);
    EastValue *out = east_string(output);
    EastValue *run_fields[4] = {east_string(program), inputs,
                                east_variant_new("value", out, output_t),
                                east_variant_new(whole ? "whole" : "lazy", east_null(), decode_t)};
    east_value_release(out);
    EastValue *run = east_struct_new_owned(
        (const char *[]){"program", "inputs", "output", "decode"}, run_fields, 4, run_t);
    EastValue *unit_fields[5] = {east_variant_new("run", run, work_t),
                                 east_array_new(&east_string_type), east_integer(1),
                                 east_boolean(false), east_string(result)};
    east_value_release(run);
    EastValue *unit =
        east_struct_new_owned((const char *[]){"work", "platforms", "threads", "fetch", "result"},
                              unit_fields, 5, unit_t);
    ByteBuffer *bytes = unit ? east_beast2_encode_full(unit, unit_t) : NULL;
    if (unit) east_value_release(unit);
    FILE *f = bytes ? fopen(path, "wb") : NULL;
    bool ok = f && fwrite(bytes->data, 1, bytes->len, f) == bytes->len;
    if (f) ok = fclose(f) == 0 && ok;
    if (bytes) byte_buffer_free(bytes);
    return ok;
}

/* Whether the -v account weighs input 0, `path`, in megabytes — the
 * collection its manifest names — rather than the manifest's few kilobytes. */
static bool input_weighed_in_mb(const char *err, const char *path)
{
    char line[1100];
    snprintf(line, sizeof(line), "input 0: %s  (", path);
    const char *at = strstr(err, line);
    if (!at) return false;
    const char *close = strchr(at + strlen(line), ')');
    return close && close - 2 >= at && strncmp(close - 2, "MB", 2) == 0;
}

/* A manifest-rooted input — how e3 stages a collection input for a runner
 * that opens manifests — pages over its directory's segment files: a keyed
 * read decodes one segment, the -v account weighs the segments rather than
 * the manifest's own few kilobytes, and `--decode whole` reads the same value
 * whole. */
static void test_paged_manifest(const char *bin, const char *fixtures)
{
    const char *table = "paged_wide_manifest.beast2";
    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    EastValue *dict = wide_table(dt, WIDE_ROWS);
    bool written = east_beast2_write_manifest_dir(dict, dt, EAST_BEAST2_CODEC_NONE, table);
    east_value_release(dict);
    CHECK(written, "the manifest directory was not written");
    if (!written) return;

    char cmd[2048];
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_has.beast2\" -i \"%s\" -v", bin, fixtures,
             table);
    int rc = run_cli(cmd, "manifest_out.txt", "manifest_err.txt");
    CHECK(rc == 0, "manifest run (lazy): expected exit 0, got %d", rc);
    check_file_contains("manifest_out.txt", "true");
    check_file_contains("manifest_err.txt", "input 0: opened lazily");
    char *err = read_text("manifest_err.txt");
    if (err) {
        size_t decoded = 0, segments = 0, fences = 0;
        bool accounted = parse_paging_account(err, &decoded, &segments, &fences);
        CHECK(accounted, "the manifest run reports its paging account:\n%s", err);
        CHECK(!accounted || (segments >= 8 && decoded == 1),
              "a keyed read of the manifest decoded %zu of %zu segments (expected 1)", decoded,
              segments);
        CHECK(input_weighed_in_mb(err, table),
              "the manifest input is not weighed by its segments:\n%s", err);
        free(err);
    }

    /* exec -v gives the same account for the same read, run as a unit that
     * reads its input lazily. */
    const char *unit = "manifest_unit.beast2";
    char program[1024];
    snprintf(program, sizeof(program), "%s/paged_has.beast2", fixtures);
    CHECK(write_run_unit(unit, program, table, "manifest_exec_out.beast2",
                         "manifest_exec_result.beast2", false),
          "the unit was not written");
    snprintf(cmd, sizeof(cmd), "\"%s\" exec \"%s\" -v", bin, unit);
    rc = run_cli(cmd, "manifest_out.txt", "manifest_err.txt");
    CHECK(rc == 0, "manifest exec (lazy): expected exit 0, got %d", rc);
    err = read_text("manifest_err.txt");
    if (err) {
        CHECK(strstr(err, "input 0: opened lazily") != NULL,
              "exec -v does not say the input opened lazily:\n%s", err);
        size_t decoded = 0, segments = 0, fences = 0;
        bool accounted = parse_paging_account(err, &decoded, &segments, &fences);
        CHECK(accounted && segments >= 8 && decoded == 1,
              "exec -v does not report the keyed read's paging account:\n%s", err);
        CHECK(input_weighed_in_mb(err, table),
              "exec -v does not weigh the input by its segments:\n%s", err);
        free(err);
    }
    snprintf(cmd, sizeof(cmd), "\"%s\" exec \"%s\"", bin, unit);
    rc = run_cli(cmd, "manifest_out.txt", "manifest_err.txt");
    CHECK(rc == 0, "manifest exec (quiet): expected exit 0, got %d", rc);
    err = read_text("manifest_err.txt");
    CHECK(err && strstr(err, "input 0:") == NULL, "exec without -v reports its inputs:\n%s",
          err ? err : "");
    free(err);
    remove("manifest_exec_out.beast2");
    remove("manifest_exec_result.beast2");

    /* A unit whose `decode` is whole decodes its input before the program
     * runs, and says what it holds in memory. */
    CHECK(write_run_unit(unit, program, table, "manifest_exec_out.beast2",
                         "manifest_exec_result.beast2", true),
          "the whole unit was not written");
    snprintf(cmd, sizeof(cmd), "\"%s\" exec \"%s\" -v", bin, unit);
    rc = run_cli(cmd, "manifest_out.txt", "manifest_err.txt");
    CHECK(rc == 0, "manifest exec (whole): expected exit 0, got %d", rc);
    err = read_text("manifest_err.txt");
    if (err) {
        CHECK(strstr(err, "opened lazily") == NULL, "a whole unit opened its input lazily:\n%s",
              err);
        CHECK(reports_decoded_whole(err, RSS_COMPARABLE),
              "a whole unit does not say what its input holds in memory:\n%s", err);
        CHECK(strstr(err, "segments decoded") == NULL, "a whole unit reports paging:\n%s", err);
        free(err);
    }
    remove(unit);
    remove("manifest_exec_out.beast2");
    remove("manifest_exec_result.beast2");

    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_has.beast2\" -i \"%s\" --decode whole -v",
             bin, fixtures, table);
    rc = run_cli(cmd, "manifest_out.txt", "manifest_err.txt");
    CHECK(rc == 0, "manifest run (whole): expected exit 0, got %d", rc);
    check_file_contains("manifest_out.txt", "true");
    check_file_lacks("manifest_err.txt", "opened lazily");

    remove_manifest_dir(table);
    remove("manifest_out.txt");
    remove("manifest_err.txt");
}

/* The nested fixture as a manifest directory, the form e3 stages a stored
 * collection in: the manifest opener gates the shape for itself, so it opens
 * the nested rows lazily AND frozen too. */
static void test_paged_shape_gate_manifest(const char *bin, const char *fixtures)
{
    char fixture[1024];
    snprintf(fixture, sizeof(fixture), "%s/paged_nested.beast2", fixtures);
    FILE *f = fopen(fixture, "rb");
    CHECK(f != NULL, "cannot open %s", fixture);
    if (!f) return;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t *bytes = malloc(len > 0 ? (size_t)len : 1);
    size_t rd = bytes ? fread(bytes, 1, len > 0 ? (size_t)len : 0, f) : 0;
    fclose(f);
    EastType *type = bytes && rd == (size_t)len ? east_beast2_extract_type(bytes, rd) : NULL;
    EastValue *rows = type ? east_beast2_decode_full(bytes, rd, type) : NULL;
    free(bytes);
    const char *table = "paged_nested_manifest.beast2";
    bool written =
        rows && east_beast2_write_manifest_dir(rows, type, EAST_BEAST2_CODEC_NONE, table);
    if (rows) east_value_release(rows);
    if (type) east_type_release(type);
    CHECK(written, "the nested manifest directory was not written");
    if (!written) return;

    char cmd[2048];
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/paged_nested_mutate.beast2\" -i \"%s\" -v", bin,
             fixtures, table);
    int rc = run_cli(cmd, "manifest_nested_out.txt", "manifest_nested_err.txt");
    CHECK(rc == 1, "manifest gate: expected exit 1, got %d", rc);
    check_file_contains("manifest_nested_err.txt",
                        "cannot mutate a frozen value (task inputs are immutable)");
    check_file_contains("manifest_nested_err.txt", "input 0: opened lazily");

    remove_manifest_dir(table);
    remove("manifest_nested_out.txt");
    remove("manifest_nested_err.txt");
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    east_type_of_type_init();

    test_paged_shape_gate(argv[1], argv[2]);

    /* 160k rows of ~200 bytes: ~33 MB on the wire, an order of magnitude
     * above the CLI's baseline RSS, in dozens of segments. */
    const char *table = "paged_wide_table.beast2";
    size_t wire = write_wide_table(table, WIDE_ROWS);
    CHECK(wire > 16u * 1024u * 1024u, "wide fixture too small: %zu bytes", wire);
    if (wire > 0) {
        test_paged_residency(argv[1], argv[2], table);
        test_paged_account(argv[1], argv[2], table);
    }
    remove(table);

    test_paged_manifest(argv[1], argv[2]);
    test_paged_shape_gate_manifest(argv[1], argv[2]);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli paged gate: all checks passed\n");
    return 0;
}
