/*
 * CLI --emit gate (issues #507, #518, #770).
 *
 * Spawns the built `east-c` binary over the checked-in IR fixtures in
 * tests/fixtures (generated by tests/generate_fixtures.mjs from the TS
 * side, mirroring east-node-cli/src/runner.spec.ts) and validates the
 * emitted beast2 blobs with east-c's own readers:
 *
 *   1. producer      — `run --emit array`: 2500 emissions land segmented
 *                      + indexed (pages open, exact counts, keyed reads);
 *   2. stream fold   — `run --emit array --stream 0 -i events.beast2`:
 *                      running sums over a TS-paged-written input blob, so
 *                      this case is also a cross-runtime decode of
 *                      TS-writer bytes;
 *   3. dict producer — `run --emit dict`: 1000 ascending pairs decode with
 *                      exact size and keyed content;
 *   4. out-of-order  — `run --emit dict` on a descending emitter: exit 0
 *                      since #518 (the sink establishes canonical order),
 *                      the transition notice on stderr, and the canonical
 *                      two-pair dict in the output;
 *   5. shuffled      — the same 1000 pairs as case 3 emitted in shuffled
 *                      order under a tiny EAST_EMIT_RUN_ELEMENTS: dozens
 *                      of spill runs merge to a blob byte-identical to
 *                      case 3's, and the runs are cleaned up;
 *   6. duplicate     — the surviving hard error: exit 1, the canonical
 *                      duplicate-key message, no index in the aborted
 *                      output;
 *   7. fold contract — `--merge` (dict) and `--union` (set) over sequences
 *                      with duplicate keys write exactly the bytes the
 *                      flag-less sink writes for the folded sequence, on
 *                      the ascending path and under run caps that fold in
 *                      the tail, across runs and across merge passes;
 *   8. bounded runs  — under a 64-entry run cap, 50k and 400k out-of-order
 *                      emissions report the same peak entries, peak bytes
 *                      and runs per pass in the -v epilogue, only more
 *                      passes; a byte cap below one run's bytes spills by
 *                      bytes;
 *   9. lifeline      — with EAST_EXIT_WITH_PARENT=1 the runner exits once
 *                      its stdin pipe closes, mid-computation (bounded
 *                      wait, 10 s).
 *
 * Run under ASan/LSan (run_leak_check.sh's build-asan configuration) the
 * spawned CLI is itself instrumented; every case scans the child's stderr
 * for sanitizer reports, so an emit-sink lifetime regression — including
 * the error path, where the sink is freed without finish — fails the gate
 * even when the exit code is the expected non-zero.
 */
#include <east/east.h>
#include <east/type_of_type.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static uint8_t *read_file(const char *path, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(len > 0 ? (size_t)len : 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, (size_t)len, f);
    fclose(f);
    *out_len = rd;
    return buf;
}

/* Runs one CLI invocation with stderr captured to `err_path`; returns the
 * child's exit code (-1 on spawn failure) and fails the gate if the child's
 * stderr carries a sanitizer report. */
static int run_cli(const char *cmdline, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    /* cmd.exe strips a leading quote unless the whole line is re-quoted. */
    snprintf(full, sizeof(full), "\"%s 2> \"%s\"\"", cmdline, err_path);
#else
    snprintf(full, sizeof(full), "%s 2> \"%s\"", cmdline, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif

    size_t err_len = 0;
    uint8_t *err = read_file(err_path, &err_len);
    if (err) {
        /* NUL-terminate for strstr (read_file allocates at least 1 byte). */
        uint8_t *text = realloc(err, err_len + 1);
        if (text) {
            err = text;
            err[err_len] = '\0';
            CHECK(strstr((const char *)err, "AddressSanitizer") == NULL &&
                      strstr((const char *)err, "LeakSanitizer") == NULL,
                  "sanitizer report in CLI stderr:\n%s", (const char *)err);
        }
        free(err);
    }
    return rc;
}

/* Reads the captured stderr and asserts it contains `needle`. */
static void check_stderr_contains(const char *err_path, const char *needle)
{
    size_t len = 0;
    uint8_t *err = read_file(err_path, &len);
    CHECK(err != NULL, "cannot read %s", err_path);
    if (!err) return;
    uint8_t *text = realloc(err, len + 1);
    if (!text) {
        free(err);
        return;
    }
    text[len] = '\0';
    CHECK(strstr((const char *)text, needle) != NULL, "stderr missing \"%s\"; got:\n%s", needle,
          (const char *)text);
    free(text);
}

/* A whole file as a NUL-terminated string, or NULL when it cannot be read. */
static char *read_text(const char *path)
{
    size_t len = 0;
    uint8_t *data = read_file(path, &len);
    if (!data) return NULL;
    uint8_t *text = realloc(data, len + 1);
    if (!text) {
        free(data);
        return NULL;
    }
    text[len] = '\0';
    return (char *)text;
}

/* Whether `path` names a readable file. */
static bool file_exists(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    fclose(f);
    return true;
}

/* Whether two files hold the same bytes (false when either is unreadable). */
static bool same_bytes(const char *path_a, const char *path_b)
{
    size_t len_a = 0, len_b = 0;
    uint8_t *a = read_file(path_a, &len_a);
    uint8_t *b = read_file(path_b, &len_b);
    bool same = a && b && len_a == len_b && memcmp(a, b, len_a) == 0;
    free(a);
    free(b);
    return same;
}

/* east_array_get borrows — no release. */
static int64_t integer_at(EastValue *arr, size_t index)
{
    EastValue *v = east_array_get(arr, index);
    return v ? v->data.integer : INT64_MIN;
}

static void test_producer(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_producer.beast2", err[64] = "emit_err_producer.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_producer.beast2\" --emit array -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "producer: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "producer: no output written");
    if (!data) return;

    EastType *at = east_array_type(&east_integer_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, at);
    CHECK(pages != NULL, "producer: emitted blob carries no index");
    if (pages) {
        CHECK(east_beast2_pages_element_count(pages) == 2500, "producer: element count %zu",
              east_beast2_pages_element_count(pages));
        CHECK(east_beast2_pages_segment_count(pages) > 1, "producer: expected multiple segments");
        CHECK(east_beast2_pages_self_contained(pages), "producer: segments not self-contained");
        EastValue *row = east_beast2_pages_element(pages, 1234);
        CHECK(row != NULL && row->data.integer == 2468, "producer: element(1234) wrong");
        if (row) east_value_release(row);
        east_beast2_pages_free(pages);
    }

    EastValue *whole = east_beast2_decode_full(data, len, at);
    CHECK(whole != NULL, "producer: whole decode failed");
    if (whole) {
        CHECK(whole->data.array.len == 2500, "producer: decoded length %zu", whole->data.array.len);
        CHECK(integer_at(whole, 0) == 0 && integer_at(whole, 2499) == 4998,
              "producer: decoded values wrong");
        east_value_release(whole);
    }
    free(data);
}

static void test_stream_fold(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_fold.beast2", err[64] = "emit_err_fold.txt";
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_fold.beast2\" --emit array --stream 0 -i \"%s/events.beast2\" "
             "-o %s",
             bin, fixtures, fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "fold: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "fold: no output written");
    if (!data) return;

    EastType *at = east_array_type(&east_integer_type);
    EastValue *sums = east_beast2_decode_full(data, len, at);
    CHECK(sums != NULL, "fold: decode failed");
    if (sums) {
        CHECK(sums->data.array.len == 2500, "fold: length %zu", sums->data.array.len);
        /* Running sums of [0..2500): prefix k holds k*(k+1)/2. */
        CHECK(integer_at(sums, 0) == 0, "fold: first sum wrong");
        CHECK(integer_at(sums, 99) == 4950, "fold: sum(99) wrong");
        CHECK(integer_at(sums, 2499) == 3123750, "fold: final sum wrong");
        east_value_release(sums);
    }
    free(data);
}

static void test_dict(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_dict.beast2", err[64] = "emit_err_dict.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict.beast2\" --emit dict -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "dict: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "dict: no output written");
    if (!data) return;

    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
    CHECK(pages != NULL, "dict: emitted blob carries no index");
    if (pages) {
        CHECK(east_beast2_pages_element_count(pages) == 1000, "dict: pair count %zu",
              east_beast2_pages_element_count(pages));
        east_beast2_pages_free(pages);
    }

    EastValue *dict = east_beast2_decode_full(data, len, dt);
    CHECK(dict != NULL, "dict: decode failed");
    if (dict) {
        CHECK(dict->data.dict.len == 1000, "dict: decoded size %zu", dict->data.dict.len);
        EastValue *key = east_integer(42);
        /* east_dict_get borrows — no release of the returned value. */
        EastValue *row = east_dict_get(dict, key);
        CHECK(row != NULL && strcmp(row->data.string.data, "row-42") == 0, "dict: get(42) wrong");
        east_value_release(key);
        east_value_release(dict);
    }
    free(data);
}

/* Sets (value != NULL) or clears (value == NULL) an environment variable the
 * spawned CLI inherits — the sink's run caps. */
static void set_env(const char *name, const char *value)
{
#ifdef _WIN32
    _putenv_s(name, value ? value : "");
#else
    if (value)
        setenv(name, value, 1);
    else
        unsetenv(name);
#endif
}

static void test_dict_out_of_order(const char *bin, const char *fixtures)
{
    /* Since issue #518 the sink absorbs out-of-order emission (demote →
     * spill → merge) instead of erroring; the transition is reported on
     * stderr and the output is the canonical dict. */
    char cmd[2048], out[64] = "emit_out_disorder.beast2", err[64] = "emit_err_disorder.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict_disorder.beast2\" --emit dict -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "disorder: expected exit 0, got %d", rc);
    check_stderr_contains(err, "left ascending order");
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "disorder: no output written");
    if (!data) return;
    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
    CHECK(pages != NULL, "disorder: merged blob carries no index");
    if (pages) east_beast2_pages_free(pages);
    EastValue *dict = east_beast2_decode_full(data, len, dt);
    CHECK(dict != NULL, "disorder: decode failed");
    if (dict) {
        CHECK(dict->data.dict.len == 2, "disorder: decoded size %zu", dict->data.dict.len);
        EastValue *key = east_integer(1);
        /* east_dict_get borrows — no release of the returned value. */
        EastValue *row = east_dict_get(dict, key);
        CHECK(row != NULL && strcmp(row->data.string.data, "a") == 0, "disorder: get(1) wrong");
        east_value_release(key);
        east_value_release(dict);
    }
    free(data);
}

static void test_dict_shuffled(const char *bin, const char *fixtures)
{
    /* The shuffled producer emits the same 1000 pairs as emit_dict; a tiny
     * run cap forces dozens of spill runs, and the merged output must be
     * byte-identical to the ordered producer's blob, with the runs cleaned
     * up afterwards. */
    char cmd[2048];
    char out_ordered[64] = "emit_out_dict_ordered.beast2", err1[64] = "emit_err_ordered.txt";
    char out_shuffled[64] = "emit_out_dict_shuffled.beast2", err2[64] = "emit_err_shuffled.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict.beast2\" --emit dict -o %s", bin,
             fixtures, out_ordered);
    int rc = run_cli(cmd, err1);
    CHECK(rc == 0, "shuffled: ordered control expected exit 0, got %d", rc);
    set_env("EAST_EMIT_RUN_ELEMENTS", "32");
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict_shuffled.beast2\" --emit dict -o %s", bin,
             fixtures, out_shuffled);
    rc = run_cli(cmd, err2);
    set_env("EAST_EMIT_RUN_ELEMENTS", NULL);
    CHECK(rc == 0, "shuffled: expected exit 0, got %d", rc);
    check_stderr_contains(err2, "left ascending order");
    if (rc != 0) return;

    size_t len_a = 0, len_b = 0;
    uint8_t *a = read_file(out_ordered, &len_a);
    uint8_t *b = read_file(out_shuffled, &len_b);
    CHECK(a != NULL && b != NULL, "shuffled: outputs missing");
    if (a && b) {
        CHECK(len_a == len_b && memcmp(a, b, len_a) == 0,
              "shuffled: merged blob is not byte-identical to the ordered blob (%zu vs %zu bytes)",
              len_a, len_b);
    }
    free(a);
    free(b);

    char runpath[96];
    snprintf(runpath, sizeof(runpath), "%s.run0", out_shuffled);
    FILE *rf = fopen(runpath, "rb");
    CHECK(rf == NULL, "shuffled: spill run left behind");
    if (rf) fclose(rf);
}

static void test_dict_nested_shuffled(const char *bin, const char *fixtures)
{
    /* The out-of-order path encodes every emission at the emit and merges
     * runs of bytes, decoding keys only. With a nested value type and a
     * tiny run cap the shuffled producer must still yield a blob byte-
     * identical to the ascending producer's, decode to the same content,
     * and account for its spills in the -v epilogue. */
    char cmd[2048];
    char out_ordered[64] = "emit_out_nested_ordered.beast2", err1[64] = "emit_err_nested_o.txt";
    char out_shuffled[64] = "emit_out_nested_shuffled.beast2", err2[64] = "emit_err_nested_s.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_nested.beast2\" --emit dict -o %s", bin,
             fixtures, out_ordered);
    int rc = run_cli(cmd, err1);
    CHECK(rc == 0, "nested: ordered control expected exit 0, got %d", rc);
    set_env("EAST_EMIT_RUN_ELEMENTS", "40");
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_nested_shuffled.beast2\" --emit dict -o %s -v",
             bin, fixtures, out_shuffled);
    rc = run_cli(cmd, err2);
    set_env("EAST_EMIT_RUN_ELEMENTS", NULL);
    CHECK(rc == 0, "nested: shuffled expected exit 0, got %d", rc);
    check_stderr_contains(err2, "left ascending order");
    check_stderr_contains(err2, "spill(s), peak");
    if (rc != 0) return;

    size_t len_a = 0, len_b = 0;
    uint8_t *a = read_file(out_ordered, &len_a);
    uint8_t *b = read_file(out_shuffled, &len_b);
    CHECK(a != NULL && b != NULL, "nested: outputs missing");
    if (a && b) {
        CHECK(len_a == len_b && memcmp(a, b, len_a) == 0,
              "nested: merged blob is not byte-identical to the ordered blob (%zu vs %zu bytes)",
              len_a, len_b);
    }

    /* Dict<Integer, Struct{label: String, items: Array<Struct{x: Integer, y: Float}>}> */
    const char *item_names[2] = {"x", "y"};
    EastType *item_types[2] = {&east_integer_type, &east_float_type};
    EastType *item_t = east_struct_type(item_names, item_types, 2);
    EastType *items_t = east_array_type(item_t);
    const char *val_names[2] = {"label", "items"};
    EastType *val_types[2] = {&east_string_type, items_t};
    EastType *val_t = east_struct_type(val_names, val_types, 2);
    EastType *dt = east_dict_type(&east_integer_type, val_t);
    if (b) {
        Beast2Pages *pages = east_beast2_pages_new(b, len_b, dt);
        CHECK(pages != NULL, "nested: merged blob carries no index");
        if (pages) {
            CHECK(east_beast2_pages_element_count(pages) == 300, "nested: pair count %zu",
                  east_beast2_pages_element_count(pages));
            east_beast2_pages_free(pages);
        }
        EastValue *dict = east_beast2_decode_full(b, len_b, dt);
        CHECK(dict != NULL, "nested: decode failed");
        if (dict) {
            CHECK(dict->data.dict.len == 300, "nested: decoded size %zu", dict->data.dict.len);
            EastValue *key = east_integer(42);
            /* east_dict_get borrows — no release of the returned value. */
            EastValue *row = east_dict_get(dict, key);
            CHECK(row != NULL && row->kind == EAST_VAL_STRUCT, "nested: get(42) missing");
            if (row && row->kind == EAST_VAL_STRUCT) {
                EastValue *label = east_struct_get_field(row, "label");
                EastValue *items = east_struct_get_field(row, "items");
                CHECK(label && strcmp(label->data.string.data, "row-42") == 0,
                      "nested: get(42).label wrong");
                CHECK(items && east_array_len(items) == 3, "nested: get(42).items length wrong");
                if (items && east_array_len(items) == 3) {
                    EastValue *x1 = east_struct_get_field(east_array_get(items, 1), "x");
                    CHECK(x1 && x1->data.integer == 43, "nested: get(42).items[1].x wrong");
                }
            }
            east_value_release(key);
            east_value_release(dict);
        }
    }
    free(a);
    free(b);

    char runpath[96];
    snprintf(runpath, sizeof(runpath), "%s.run1", out_shuffled);
    FILE *rf = fopen(runpath, "rb");
    CHECK(rf == NULL, "nested: spill run left behind");
    if (rf) fclose(rf);
}

static void test_dict_duplicate(const char *bin, const char *fixtures)
{
    /* Duplicate keys are the surviving hard error of the old strictly-
     * ascending contract: exit 1, the canonical message, and no index in
     * the aborted output. */
    char cmd[2048], out[64] = "emit_out_duplicate.beast2", err[64] = "emit_err_duplicate.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict_duplicate.beast2\" --emit dict -o %s",
             bin, fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 1, "duplicate: expected exit 1, got %d", rc);
    check_stderr_contains(err, "duplicate Dict key emitted");

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    if (data) {
        EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
        Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
        CHECK(pages == NULL, "duplicate: aborted output unexpectedly carries an index");
        if (pages) east_beast2_pages_free(pages);
        free(data);
    }
}

static void test_snapshot_guard(const char *bin, const char *fixtures)
{
    /* The snapshot manifest (format v1) carries no streaming flags, so a
     * captured emit invocation would replay with the wrong arity — the CLI
     * must refuse the combination at capture time (issue #508). */
    char cmd[2048], err[64] = "emit_err_snapshot.txt";
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_producer.beast2\" --emit array -o emit_out_snap.beast2 "
             "--snapshot emit_snap.east-snapshot",
             bin, fixtures);
    int rc = run_cli(cmd, err);
    CHECK(rc == 1, "snapshot guard: expected exit 1, got %d", rc);
    check_stderr_contains(err, "--snapshot does not capture --emit/--stream");
}

static void test_fold_contract(const char *bin, const char *fixtures)
{
    /* Issue #770: with --merge (dict) or --union (set) the sink folds equal
     * keys in emission order, and the file is byte-identical to what the
     * flag-less sink writes for the folded sequence. The ascending sequence
     * folds on the straight-through path — key 999 into a full batch's last
     * entry; the scattered one demotes, a duplicate of a prefix key follows,
     * and each run cap moves its folds: all into the tail (the default),
     * across 50-odd runs (16), across the 400-odd runs of a two-pass merge
     * (2). */
    static const struct {
        const char *program; /* <program>.beast2 emits, <program>_folded.beast2 its fold */
        const char *run_cap; /* EAST_EMIT_RUN_ELEMENTS, or NULL for the default */
        bool demotes;
    } cases[] = {
        {"emit_merge_ascending", NULL, false}, {"emit_merge_scattered", NULL, true},
        {"emit_merge_scattered", "16", true},  {"emit_merge_scattered", "2", true},
        {"emit_union_ascending", NULL, false}, {"emit_union_scattered", NULL, true},
        {"emit_union_scattered", "16", true},  {"emit_union_scattered", "2", true},
    };
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        const char *program = cases[i].program;
        const char *cap = cases[i].run_cap ? cases[i].run_cap : "default";
        bool dict = strncmp(program, "emit_merge", strlen("emit_merge")) == 0;
        char cmd[4096], flags[1100], expected[64], folded[64], err[64];
        snprintf(expected, sizeof(expected), "emit_out_fold%zu_expected.beast2", i);
        snprintf(folded, sizeof(folded), "emit_out_fold%zu.beast2", i);
        snprintf(err, sizeof(err), "emit_err_fold%zu.txt", i);
        if (dict)
            snprintf(flags, sizeof(flags), "--emit dict --merge \"%s/emit_merge_concat.beast2\"",
                     fixtures);
        else
            snprintf(flags, sizeof(flags), "--emit set --union");

        snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/%s_folded.beast2\" --emit %s -o %s", bin,
                 fixtures, program, dict ? "dict" : "set", expected);
        int rc = run_cli(cmd, err);
        CHECK(rc == 0, "fold %s: the folded control expected exit 0, got %d", program, rc);

        set_env("EAST_EMIT_RUN_ELEMENTS", cases[i].run_cap);
        snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/%s.beast2\" %s -o %s", bin, fixtures, program,
                 flags, folded);
        rc = run_cli(cmd, err);
        set_env("EAST_EMIT_RUN_ELEMENTS", NULL);
        CHECK(rc == 0, "fold %s (run cap %s): expected exit 0, got %d", program, cap, rc);
        if (rc != 0) continue;

        char *text = read_text(err);
        bool demoted = text && strstr(text, "left ascending order") != NULL;
        CHECK(demoted == cases[i].demotes,
              "fold %s (run cap %s): expected the %s path; stderr:\n%s", program, cap,
              cases[i].demotes ? "buffered" : "ascending", text ? text : "");
        free(text);
        CHECK(same_bytes(expected, folded),
              "fold %s (run cap %s): not byte-identical to the flag-less sink's output for the "
              "folded sequence",
              program, cap);

        char run0[96], pass_run0[96];
        snprintf(run0, sizeof(run0), "%s.run0", folded);
        snprintf(pass_run0, sizeof(pass_run0), "%s.run0.p1", folded);
        CHECK(!file_exists(run0) && !file_exists(pass_run0),
              "fold %s (run cap %s): temporary runs left behind", program, cap);
    }
}

/* The -v epilogue of the sink's buffered path: `emit: merged <k> source(s) in
 * <p> pass(es) (<n> runs per pass); <s> spill(s), peak <e> entries / <bytes>
 * buffered, ...`. */
typedef struct {
    bool found;
    unsigned long long sources, passes, runs_per_pass, spills, peak_entries;
    char peak_bytes[32]; /* as printed, e.g. "384 B " */
} EmitEpilogue;

static EmitEpilogue read_epilogue(const char *err_path)
{
    EmitEpilogue e;
    memset(&e, 0, sizeof(e));
    char *text = read_text(err_path);
    const char *at = text ? strstr(text, "emit: merged ") : NULL;
    if (at) {
        e.found = sscanf(at,
                         "emit: merged %llu source(s) in %llu pass(es) (%llu runs per pass); "
                         "%llu spill(s), peak %llu entries / %31[^b]buffered",
                         &e.sources, &e.passes, &e.runs_per_pass, &e.spills, &e.peak_entries,
                         e.peak_bytes) == 6;
    }
    free(text);
    return e;
}

static void test_bounded_runs(const char *bin, const char *fixtures)
{
    /* Issue #770 gate (a): the sink's memory is bounded by its run caps, not
     * by the output. Under a 64-entry run cap, 50,000 and 400,000 out-of-order
     * emissions (every element encoded in the same number of bytes) hold the
     * same peak entries and bytes and merge at most 64 runs at once; only the
     * passes grow — 783 sources (the demoted prefix, 781 spills, the tail)
     * merge in 2 passes, 6,251 in 3. A byte cap below one run's bytes spills
     * by bytes: fewer entries per run than the element cap allows. */
    char cmd[2048];
    set_env("EAST_EMIT_RUN_ELEMENTS", "64");
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_scatter_50k.beast2\" --emit set -o emit_out_scatter_50k.beast2 "
             "-v",
             bin, fixtures);
    int rc_small = run_cli(cmd, "emit_err_scatter_50k.txt");
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_scatter_400k.beast2\" --emit set -o "
             "emit_out_scatter_400k.beast2 -v",
             bin, fixtures);
    int rc_large = run_cli(cmd, "emit_err_scatter_400k.txt");
    set_env("EAST_EMIT_RUN_BYTES", "256");
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_scatter_50k.beast2\" --emit set -o "
             "emit_out_scatter_bytes.beast2 -v",
             bin, fixtures);
    int rc_bytes = run_cli(cmd, "emit_err_scatter_bytes.txt");
    set_env("EAST_EMIT_RUN_BYTES", NULL);
    set_env("EAST_EMIT_RUN_ELEMENTS", NULL);
    CHECK(rc_small == 0 && rc_large == 0 && rc_bytes == 0,
          "bounded runs: expected exit 0, got %d (50k), %d (400k), %d (byte cap)", rc_small,
          rc_large, rc_bytes);

    /* Not `small`: the Windows headers define it as a macro for `char`. */
    EmitEpilogue scatter_50k = read_epilogue("emit_err_scatter_50k.txt");
    EmitEpilogue scatter_400k = read_epilogue("emit_err_scatter_400k.txt");
    EmitEpilogue byte_cap = read_epilogue("emit_err_scatter_bytes.txt");
    CHECK(scatter_50k.found && scatter_400k.found && byte_cap.found,
          "bounded runs: -v printed no emit epilogue (50k %d, 400k %d, byte cap %d)",
          scatter_50k.found, scatter_400k.found, byte_cap.found);
    if (!scatter_50k.found || !scatter_400k.found || !byte_cap.found) return;

    CHECK(scatter_50k.peak_entries == 64 && scatter_400k.peak_entries == 64,
          "bounded runs: peak entries %llu (50k) and %llu (400k), expected the 64-entry cap",
          scatter_50k.peak_entries, scatter_400k.peak_entries);
    CHECK(strcmp(scatter_50k.peak_bytes, scatter_400k.peak_bytes) == 0,
          "bounded runs: peak bytes \"%s\" (50k) differ from \"%s\" (400k)", scatter_50k.peak_bytes,
          scatter_400k.peak_bytes);
    CHECK(scatter_50k.runs_per_pass == 64 && scatter_400k.runs_per_pass == 64,
          "bounded runs: %llu (50k) and %llu (400k) runs per pass, expected 64",
          scatter_50k.runs_per_pass, scatter_400k.runs_per_pass);
    CHECK(scatter_50k.sources == 783 && scatter_50k.passes == 2,
          "bounded runs: 50k merged %llu sources in %llu passes, expected 783 in 2",
          scatter_50k.sources, scatter_50k.passes);
    CHECK(scatter_400k.sources == 6251 && scatter_400k.passes == 3,
          "bounded runs: 400k merged %llu sources in %llu passes, expected 6251 in 3",
          scatter_400k.sources, scatter_400k.passes);
    CHECK(byte_cap.peak_entries > 0 && byte_cap.peak_entries < 64 &&
              byte_cap.spills > scatter_50k.spills,
          "bounded runs: a 256-byte cap should spill by bytes — peak %llu entries, %llu spills "
          "(%llu under the element cap alone)",
          byte_cap.peak_entries, byte_cap.spills, scatter_50k.spills);

    /* The largest merge is whole, and its runs are gone. */
    size_t len = 0;
    uint8_t *data = read_file("emit_out_scatter_400k.beast2", &len);
    CHECK(data != NULL, "bounded runs: no 400k output written");
    if (data) {
        EastType *st = east_set_type(&east_integer_type);
        Beast2Pages *pages = east_beast2_pages_new(data, len, st);
        CHECK(pages != NULL && east_beast2_pages_element_count(pages) == 400000,
              "bounded runs: the 400k output does not hold 400000 elements");
        if (pages) east_beast2_pages_free(pages);
        free(data);
    }
    CHECK(!file_exists("emit_out_scatter_400k.beast2.run0") &&
              !file_exists("emit_out_scatter_400k.beast2.run0.p1") &&
              !file_exists("emit_out_scatter_400k.beast2.run0.p2"),
          "bounded runs: temporary runs left behind");
}

/* The lifeline gate's bound on each wait: for the runner to report that its
 * body is running, and — once its stdin closes — for it to exit. */
#define LIFELINE_WAIT_MS 10000

/* The notice the emit_spin fixture's out-of-order second emission prints
 * before the body loops forever. */
#define LIFELINE_RUNNING "left ascending order"

#ifndef _WIN32
static void sleep_ms(long ms)
{
    struct timespec ts = {ms / 1000, (ms % 1000) * 1000000L};
    nanosleep(&ts, NULL);
}

static void test_exit_with_parent(const char *bin, const char *fixtures)
{
    /* Issue #770 gate (c): a runner started with EAST_EXIT_WITH_PARENT=1 and
     * a stdin pipe nobody writes exits once that pipe closes — while its body
     * is still computing. */
    char ir[1024];
    snprintf(ir, sizeof(ir), "%s/emit_spin.beast2", fixtures);
    int in_pipe[2], err_pipe[2];
    if (pipe(in_pipe) != 0) {
        CHECK(false, "lifeline: pipe failed");
        return;
    }
    if (pipe(err_pipe) != 0) {
        close(in_pipe[0]);
        close(in_pipe[1]);
        CHECK(false, "lifeline: pipe failed");
        return;
    }
    /* Set before the fork, so the child only execs. */
    setenv("EAST_EXIT_WITH_PARENT", "1", 1);
    pid_t pid = fork();
    if (pid == 0) {
        dup2(in_pipe[0], STDIN_FILENO);
        dup2(err_pipe[1], STDERR_FILENO);
        close(in_pipe[0]);
        close(in_pipe[1]);
        close(err_pipe[0]);
        close(err_pipe[1]);
        execl(bin, bin, "run", ir, "--emit", "set", "-o", "emit_out_spin.beast2", (char *)NULL);
        _exit(127);
    }
    unsetenv("EAST_EXIT_WITH_PARENT");
    close(in_pipe[0]);
    close(err_pipe[1]);
    if (pid < 0) {
        close(in_pipe[1]);
        close(err_pipe[0]);
        CHECK(false, "lifeline: fork failed");
        return;
    }

    char err[8192];
    size_t err_len = 0;
    err[0] = '\0';
    bool running = false;
    for (long waited = 0; !running && waited < LIFELINE_WAIT_MS;) {
        struct pollfd pfd = {err_pipe[0], POLLIN, 0};
        if (poll(&pfd, 1, 50) <= 0) {
            waited += 50;
            continue;
        }
        ssize_t n = read(err_pipe[0], err + err_len, sizeof(err) - 1 - err_len);
        if (n <= 0) break; /* the runner exited without running */
        err_len += (size_t)n;
        err[err_len] = '\0';
        running = strstr(err, LIFELINE_RUNNING) != NULL;
        if (err_len == sizeof(err) - 1) break;
    }
    CHECK(running, "lifeline: the runner never reported its body running; stderr:\n%s", err);

    close(in_pipe[1]); /* the lifeline closes */
    int status = 0;
    bool exited = false;
    for (long waited = 0; waited <= LIFELINE_WAIT_MS; waited += 20) {
        if (waitpid(pid, &status, WNOHANG) == pid) {
            exited = true;
            break;
        }
        sleep_ms(20);
    }
    if (!exited) {
        kill(pid, SIGKILL);
        waitpid(pid, &status, 0);
    }
    CHECK(exited, "lifeline: the runner outlived its closed stdin by %d ms", LIFELINE_WAIT_MS);
    CHECK(!exited || (WIFEXITED(status) && WEXITSTATUS(status) == 1),
          "lifeline: expected the watcher's exit status 1, got wait status %d", status);

    /* Whatever else the runner wrote, for the sanitizer scan. */
    for (;;) {
        ssize_t n = read(err_pipe[0], err + err_len, sizeof(err) - 1 - err_len);
        if (n <= 0) break;
        err_len += (size_t)n;
        err[err_len] = '\0';
        if (err_len == sizeof(err) - 1) break;
    }
    close(err_pipe[0]);
    CHECK(strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL,
          "sanitizer report in CLI stderr:\n%s", err);
    /* The watcher's exit, not an error's: exit 1 with nothing reported. */
    CHECK(strstr(err, "Error") == NULL, "lifeline: the runner reported an error:\n%s", err);
    remove("emit_out_spin.beast2");
    remove("emit_out_spin.beast2.run0");
}
#else
static void test_exit_with_parent(const char *bin, const char *fixtures)
{
    /* Issue #770 gate (c): a runner started with EAST_EXIT_WITH_PARENT=1 and
     * a stdin pipe nobody writes exits once that pipe closes — while its body
     * is still computing. */
    SECURITY_ATTRIBUTES inherit = {sizeof(SECURITY_ATTRIBUTES), NULL, TRUE};
    HANDLE in_read = NULL, in_write = NULL, err_read = NULL, err_write = NULL;
    if (!CreatePipe(&in_read, &in_write, &inherit, 0)) {
        CHECK(false, "lifeline: CreatePipe failed (%lu)", GetLastError());
        return;
    }
    if (!CreatePipe(&err_read, &err_write, &inherit, 0)) {
        CloseHandle(in_read);
        CloseHandle(in_write);
        CHECK(false, "lifeline: CreatePipe failed (%lu)", GetLastError());
        return;
    }
    /* The child inherits only its own ends. */
    SetHandleInformation(in_write, HANDLE_FLAG_INHERIT, 0);
    SetHandleInformation(err_read, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si;
    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdInput = in_read;
    si.hStdOutput = err_write;
    si.hStdError = err_write;
    PROCESS_INFORMATION pi;
    char cmd[4096];
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_spin.beast2\" --emit set -o emit_out_spin.beast2", bin,
             fixtures);
    SetEnvironmentVariableA("EAST_EXIT_WITH_PARENT", "1");
    BOOL started = CreateProcessA(NULL, cmd, NULL, NULL, TRUE, 0, NULL, NULL, &si, &pi);
    SetEnvironmentVariableA("EAST_EXIT_WITH_PARENT", NULL);
    CloseHandle(in_read);
    CloseHandle(err_write);
    if (!started) {
        CloseHandle(in_write);
        CloseHandle(err_read);
        CHECK(false, "lifeline: CreateProcess failed (%lu)", GetLastError());
        return;
    }

    char err[8192];
    size_t err_len = 0;
    err[0] = '\0';
    bool running = false;
    for (long waited = 0; !running && waited < LIFELINE_WAIT_MS;) {
        DWORD available = 0;
        if (!PeekNamedPipe(err_read, NULL, 0, NULL, &available, NULL)) break; /* it exited */
        if (available == 0) {
            Sleep(50);
            waited += 50;
            continue;
        }
        DWORD want = (DWORD)(sizeof(err) - 1 - err_len), got = 0;
        if (available < want) want = available;
        if (!ReadFile(err_read, err + err_len, want, &got, NULL) || got == 0) break;
        err_len += got;
        err[err_len] = '\0';
        running = strstr(err, LIFELINE_RUNNING) != NULL;
        if (err_len == sizeof(err) - 1) break;
    }
    CHECK(running, "lifeline: the runner never reported its body running; stderr:\n%s", err);

    CloseHandle(in_write); /* the lifeline closes */
    bool exited = WaitForSingleObject(pi.hProcess, LIFELINE_WAIT_MS) == WAIT_OBJECT_0;
    if (!exited) {
        TerminateProcess(pi.hProcess, 99);
        WaitForSingleObject(pi.hProcess, INFINITE);
    }
    DWORD code = 0;
    GetExitCodeProcess(pi.hProcess, &code);
    CHECK(exited, "lifeline: the runner outlived its closed stdin by %d ms", LIFELINE_WAIT_MS);
    CHECK(!exited || code == 1, "lifeline: expected the watcher's exit code 1, got %lu", code);

    /* Whatever else the runner wrote. */
    for (;;) {
        DWORD want = (DWORD)(sizeof(err) - 1 - err_len), got = 0;
        if (want == 0 || !ReadFile(err_read, err + err_len, want, &got, NULL) || got == 0) break;
        err_len += got;
        err[err_len] = '\0';
    }
    /* The watcher's exit, not an error's: exit 1 with nothing reported. */
    CHECK(strstr(err, "Error") == NULL, "lifeline: the runner reported an error:\n%s", err);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    CloseHandle(err_read);
    remove("emit_out_spin.beast2");
    remove("emit_out_spin.beast2.run0");
}
#endif

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    east_type_of_type_init();

    test_producer(argv[1], argv[2]);
    test_stream_fold(argv[1], argv[2]);
    test_dict(argv[1], argv[2]);
    test_dict_out_of_order(argv[1], argv[2]);
    test_dict_shuffled(argv[1], argv[2]);
    test_dict_nested_shuffled(argv[1], argv[2]);
    test_dict_duplicate(argv[1], argv[2]);
    test_snapshot_guard(argv[1], argv[2]);
    test_fold_contract(argv[1], argv[2]);
    test_bounded_runs(argv[1], argv[2]);
    test_exit_with_parent(argv[1], argv[2]);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli emit gate: all checks passed\n");
    return 0;
}
