/*
 * CLI lifeline gate (issue #770).
 *
 * `exec --exit-with-parent` on a unit whose program never returns: once the
 * runner's stdin pipe closes, it exits — mid-computation, within a bounded
 * wait (10 s). The program (tests/fixtures/emit_spin.beast2, generated by
 * tests/generate_fixtures.mjs) emits one element into a set output and then
 * loops forever; the unit is built here from the protocol's own type, beside
 * the gate in the working directory. The sink creates the output directory
 * before the program runs, so its appearance is the sign the runner is up. On
 * Windows the gate runs over a synchronous pipe and over an overlapped one,
 * the kind e3 hands its runners.
 *
 * Run under ASan/LSan (run_leak_check.sh's build-asan configuration) the
 * spawned CLI is itself instrumented, and the gate scans the child's stderr
 * for a sanitizer report.
 */
#include <east/compat.h>
#include <east/east.h>
#include <east/type_of_type.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <signal.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

/* The gate's bound on each wait: for the runner to create its output
 * directory, and — once its stdin closes — for it to exit. */
#define LIFELINE_WAIT_MS 10000
#define LIFELINE_UNIT "lifeline_unit.beast2"
#define LIFELINE_OUTPUT "lifeline_output"
#define LIFELINE_RESULT "lifeline_result.beast2"

/* Writes the unit: `program` run with no inputs, emitting a set into
 * LIFELINE_OUTPUT, its result to LIFELINE_RESULT. Both are relative, so they
 * resolve against the unit's directory, the working directory. */
static bool write_unit(const char *program)
{
    static const char *unit_names[4] = {"work", "platforms", "threads", "result"};
    static const char *run_names[3] = {"program", "inputs", "output"};
    EastType *unit_type = east_unit_type();
    EastType *work_type = unit_type->data.struct_.fields[0].type;
    EastType *run_type = work_type->data.variant.cases[1].type; /* merge, run */
    EastType *output_type = run_type->data.struct_.fields[2].type;

    EastValue *dir = east_string(LIFELINE_OUTPUT);
    EastValue *output = east_variant_new("set", dir, output_type);
    east_value_release(dir);
    EastValue *run_fields[3] = {east_string(program), east_array_new(&east_string_type), output};
    EastValue *run = east_struct_new_owned(run_names, run_fields, 3, run_type);
    EastValue *work = east_variant_new("run", run, work_type);
    east_value_release(run);
    EastValue *fields[4] = {work, east_array_new(&east_string_type), east_integer(1),
                            east_string(LIFELINE_RESULT)};
    EastValue *unit = east_struct_new_owned(unit_names, fields, 4, unit_type);
    ByteBuffer *bytes = east_beast2_encode_full(unit, unit_type);
    east_value_release(unit);
    if (!bytes) return false;
    FILE *f = fopen(LIFELINE_UNIT, "wb");
    bool ok = f && fwrite(bytes->data, 1, bytes->len, f) == bytes->len;
    if (f) ok = fclose(f) == 0 && ok;
    byte_buffer_free(bytes);
    return ok;
}

/* Whether `path` names a directory. */
static bool directory_exists(const char *path)
{
    struct stat st;
    return stat(path, &st) == 0 && S_ISDIR(st.st_mode);
}

/* Removes what a run left: the (empty) output directory and the result. */
static void remove_outputs(void)
{
    rmdir(LIFELINE_OUTPUT);
    remove(LIFELINE_RESULT);
}

#ifndef _WIN32
static void sleep_ms(long ms)
{
    struct timespec ts = {ms / 1000, (ms % 1000) * 1000000L};
    nanosleep(&ts, NULL);
}

static void test_exit_with_parent(const char *bin)
{
    /* A runner started with --exit-with-parent and a stdin pipe nobody writes
     * exits once that pipe closes — while its program is still computing. */
    remove_outputs();
    int in_pipe[2], err_pipe[2];
    if (pipe(in_pipe) != 0) {
        CHECK(false, "lifeline: pipe failed");
        return;
    }
    if (pipe(err_pipe) != 0) {
        close(in_pipe[0]);
        close(in_pipe[1]);
        CHECK(false, "lifeline: pipe failed");
        return;
    }
    pid_t pid = fork();
    if (pid == 0) {
        dup2(in_pipe[0], STDIN_FILENO);
        dup2(err_pipe[1], STDERR_FILENO);
        close(in_pipe[0]);
        close(in_pipe[1]);
        close(err_pipe[0]);
        close(err_pipe[1]);
        execl(bin, bin, "exec", "--exit-with-parent", LIFELINE_UNIT, (char *)NULL);
        _exit(127);
    }
    close(in_pipe[0]);
    close(err_pipe[1]);
    if (pid < 0) {
        close(in_pipe[1]);
        close(err_pipe[0]);
        CHECK(false, "lifeline: fork failed");
        return;
    }

    bool running = false;
    bool gone = false;
    int status = 0;
    for (long waited = 0; !running && !gone && waited < LIFELINE_WAIT_MS; waited += 20) {
        running = directory_exists(LIFELINE_OUTPUT);
        if (!running) {
            gone = waitpid(pid, &status, WNOHANG) == pid;
            if (!gone) sleep_ms(20);
        }
    }
    CHECK(running, "lifeline: the runner never created its output directory%s",
          gone ? " (it exited first)" : "");

    close(in_pipe[1]); /* the lifeline closes */
    bool exited = gone;
    for (long waited = 0; !exited && waited <= LIFELINE_WAIT_MS; waited += 20) {
        if (waitpid(pid, &status, WNOHANG) == pid) {
            exited = true;
            break;
        }
        sleep_ms(20);
    }
    if (!exited) {
        kill(pid, SIGKILL);
        waitpid(pid, &status, 0);
    }
    CHECK(exited, "lifeline: the runner outlived its closed stdin by %d ms", LIFELINE_WAIT_MS);
    CHECK(!exited || (WIFEXITED(status) && WEXITSTATUS(status) == 1),
          "lifeline: expected the watcher's exit status 1, got wait status %d", status);

    /* Whatever the runner wrote, for the sanitizer scan. */
    char err[8192];
    size_t err_len = 0;
    err[0] = '\0';
    for (;;) {
        ssize_t n = read(err_pipe[0], err + err_len, sizeof(err) - 1 - err_len);
        if (n <= 0) break;
        err_len += (size_t)n;
        err[err_len] = '\0';
        if (err_len == sizeof(err) - 1) break;
    }
    close(err_pipe[0]);
    CHECK(strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL,
          "sanitizer report in CLI stderr:\n%s", err);
    /* The watcher's exit, not a failure's: exit 1 with nothing reported. */
    CHECK(err_len == 0, "lifeline: the runner reported:\n%s", err);
    remove_outputs();
}
#else
/* The two ends of an overlapped pipe — the child's to read, inheritable, and
 * the parent's to close — as Node's stdio 'overlapped' makes the lifeline e3
 * hands its runners. */
static bool overlapped_pipe(HANDLE *child_end, HANDLE *parent_end)
{
    wchar_t name[96];
    swprintf(name, sizeof(name) / sizeof(name[0]), L"\\\\.\\pipe\\east-c-lifeline-%lu-%lu",
             GetCurrentProcessId(), GetTickCount());
    HANDLE server = CreateNamedPipeW(
        name, PIPE_ACCESS_OUTBOUND | FILE_FLAG_FIRST_PIPE_INSTANCE | FILE_FLAG_OVERLAPPED,
        PIPE_TYPE_BYTE | PIPE_WAIT, 1, 4096, 4096, 0, NULL);
    if (server == INVALID_HANDLE_VALUE) return false;
    SECURITY_ATTRIBUTES inherit = {sizeof(SECURITY_ATTRIBUTES), NULL, TRUE};
    HANDLE client = CreateFileW(name, GENERIC_READ | FILE_WRITE_ATTRIBUTES, 0, &inherit,
                                OPEN_EXISTING, FILE_FLAG_OVERLAPPED, NULL);
    if (client == INVALID_HANDLE_VALUE) {
        CloseHandle(server);
        return false;
    }
    *child_end = client;
    *parent_end = server;
    return true;
}

/* One run of the gate, over a synchronous pipe or an overlapped one. */
static void lifeline_case(const char *bin, bool overlapped)
{
    const char *kind = overlapped ? "overlapped" : "synchronous";
    remove_outputs();
    SECURITY_ATTRIBUTES inherit = {sizeof(SECURITY_ATTRIBUTES), NULL, TRUE};
    HANDLE in_read = NULL, in_write = NULL, err_read = NULL, err_write = NULL;
    if (overlapped ? !overlapped_pipe(&in_read, &in_write)
                   : !CreatePipe(&in_read, &in_write, &inherit, 0)) {
        CHECK(false, "lifeline (%s): the pipe could not be made (%lu)", kind, GetLastError());
        return;
    }
    if (!CreatePipe(&err_read, &err_write, &inherit, 0)) {
        CloseHandle(in_read);
        CloseHandle(in_write);
        CHECK(false, "lifeline (%s): CreatePipe failed (%lu)", kind, GetLastError());
        return;
    }
    /* The child inherits only its own ends. */
    SetHandleInformation(in_write, HANDLE_FLAG_INHERIT, 0);
    SetHandleInformation(err_read, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si;
    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdInput = in_read;
    si.hStdOutput = err_write;
    si.hStdError = err_write;
    PROCESS_INFORMATION pi;
    char cmd[4096];
    snprintf(cmd, sizeof(cmd), "\"%s\" exec --exit-with-parent " LIFELINE_UNIT, bin);
    BOOL started = CreateProcessA(NULL, cmd, NULL, NULL, TRUE, 0, NULL, NULL, &si, &pi);
    CloseHandle(in_read);
    CloseHandle(err_write);
    if (!started) {
        CloseHandle(in_write);
        CloseHandle(err_read);
        CHECK(false, "lifeline (%s): CreateProcess failed (%lu)", kind, GetLastError());
        return;
    }

    bool running = false;
    bool gone = false;
    for (long waited = 0; !running && !gone && waited < LIFELINE_WAIT_MS; waited += 20) {
        running = directory_exists(LIFELINE_OUTPUT);
        if (!running) {
            gone = WaitForSingleObject(pi.hProcess, 0) == WAIT_OBJECT_0;
            if (!gone) Sleep(20);
        }
    }
    CHECK(running, "lifeline (%s): the runner never created its output directory%s", kind,
          gone ? " (it exited first)" : "");

    CloseHandle(in_write); /* the lifeline closes */
    bool exited = gone || WaitForSingleObject(pi.hProcess, LIFELINE_WAIT_MS) == WAIT_OBJECT_0;
    if (!exited) {
        TerminateProcess(pi.hProcess, 99);
        WaitForSingleObject(pi.hProcess, INFINITE);
    }
    DWORD code = 0;
    GetExitCodeProcess(pi.hProcess, &code);
    CHECK(exited, "lifeline (%s): the runner outlived its closed stdin by %d ms", kind,
          LIFELINE_WAIT_MS);
    CHECK(!exited || code == 1, "lifeline (%s): expected the watcher's exit code 1, got %lu", kind,
          code);

    /* Whatever the runner wrote. */
    char err[8192];
    size_t err_len = 0;
    err[0] = '\0';
    for (;;) {
        DWORD want = (DWORD)(sizeof(err) - 1 - err_len), got = 0;
        if (want == 0 || !ReadFile(err_read, err + err_len, want, &got, NULL) || got == 0) break;
        err_len += got;
        err[err_len] = '\0';
    }
    /* The watcher's exit, not a failure's: exit 1 with nothing reported. */
    CHECK(err_len == 0, "lifeline (%s): the runner reported:\n%s", kind, err);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    CloseHandle(err_read);
    remove_outputs();
}

static void test_exit_with_parent(const char *bin)
{
    /* A runner started with --exit-with-parent and a stdin pipe nobody writes
     * exits once that pipe closes — while its program is still computing —
     * over a synchronous pipe (CreatePipe's) and an overlapped one (what e3
     * hands its runners): the watcher reads either. */
    lifeline_case(bin, false);
    lifeline_case(bin, true);
}
#endif

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    east_type_of_type_init();

    char program[4096];
    snprintf(program, sizeof(program), "%s/emit_spin.beast2", argv[2]);
    CHECK(write_unit(program), "lifeline: the unit could not be written");
    if (failures == 0) test_exit_with_parent(argv[1]);
    remove(LIFELINE_UNIT);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli lifeline gate: all checks passed\n");
    return 0;
}
