/*
 * CLI --emit gate (issues #507, #770).
 *
 * Spawns the built `east-c` binary over the checked-in IR fixtures in
 * tests/fixtures (generated by tests/generate_fixtures.mjs from the TS
 * side, mirroring east-node-cli/src/runner.spec.ts) and validates the
 * emitted beast2 blobs with east-c's own readers:
 *
 *   1. producer      — `run --emit array`: 2500 emissions land segmented
 *                      + indexed (pages open, exact counts, keyed reads);
 *   2. stream fold   — `run --emit array --stream 0 -i events.beast2`:
 *                      running sums over a TS-paged-written input blob, so
 *                      this case is also a cross-runtime decode of
 *                      TS-writer bytes;
 *   3. dict producer — `run --emit dict`: 1000 ascending pairs decode with
 *                      exact size and keyed content;
 *   4. out-of-order  — `run --emit dict` on a descending emitter: exit 1,
 *                      the canonical out-of-order message, no index in the
 *                      aborted output (the sink does one pass; a re-keying
 *                      producer partitions and merges instead);
 *   5. duplicate     — exit 1, the canonical duplicate-key message, no
 *                      index in the aborted output;
 *   6. fold contract — `--merge` (dict) and `--union` (set) over ascending
 *                      sequences with adjacent duplicates write exactly the
 *                      bytes the flag-less sink writes for the folded
 *                      sequence — including a fold into the last entry of a
 *                      full batch;
 *   7. lifeline      — with --exit-with-parent the runner exits once its
 *                      stdin pipe closes, mid-computation (bounded wait,
 *                      10 s).
 *
 * Run under ASan/LSan (run_leak_check.sh's build-asan configuration) the
 * spawned CLI is itself instrumented; every case scans the child's stderr
 * for sanitizer reports, so an emit-sink lifetime regression — including
 * the error path, where the sink is freed without finish — fails the gate
 * even when the exit code is the expected non-zero.
 */
#include <east/east.h>
#include <east/type_of_type.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static uint8_t *read_file(const char *path, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(len > 0 ? (size_t)len : 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, (size_t)len, f);
    fclose(f);
    *out_len = rd;
    return buf;
}

/* Runs one CLI invocation with stderr captured to `err_path`; returns the
 * child's exit code (-1 on spawn failure) and fails the gate if the child's
 * stderr carries a sanitizer report. */
static int run_cli(const char *cmdline, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    /* cmd.exe strips a leading quote unless the whole line is re-quoted. */
    snprintf(full, sizeof(full), "\"%s 2> \"%s\"\"", cmdline, err_path);
#else
    snprintf(full, sizeof(full), "%s 2> \"%s\"", cmdline, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif

    size_t err_len = 0;
    uint8_t *err = read_file(err_path, &err_len);
    if (err) {
        /* NUL-terminate for strstr (read_file allocates at least 1 byte). */
        uint8_t *text = realloc(err, err_len + 1);
        if (text) {
            err = text;
            err[err_len] = '\0';
            CHECK(strstr((const char *)err, "AddressSanitizer") == NULL &&
                      strstr((const char *)err, "LeakSanitizer") == NULL,
                  "sanitizer report in CLI stderr:\n%s", (const char *)err);
        }
        free(err);
    }
    return rc;
}

/* Reads the captured stderr and asserts it contains `needle`. */
static void check_stderr_contains(const char *err_path, const char *needle)
{
    size_t len = 0;
    uint8_t *err = read_file(err_path, &len);
    CHECK(err != NULL, "cannot read %s", err_path);
    if (!err) return;
    uint8_t *text = realloc(err, len + 1);
    if (!text) {
        free(err);
        return;
    }
    text[len] = '\0';
    CHECK(strstr((const char *)text, needle) != NULL, "stderr missing \"%s\"; got:\n%s", needle,
          (const char *)text);
    free(text);
}

/* Whether `path` names a readable file. */
static bool file_exists(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    fclose(f);
    return true;
}

/* Whether two files hold the same bytes (false when either is unreadable). */
static bool same_bytes(const char *path_a, const char *path_b)
{
    size_t len_a = 0, len_b = 0;
    uint8_t *a = read_file(path_a, &len_a);
    uint8_t *b = read_file(path_b, &len_b);
    bool same = a && b && len_a == len_b && memcmp(a, b, len_a) == 0;
    free(a);
    free(b);
    return same;
}

/* east_array_get borrows — no release. */
static int64_t integer_at(EastValue *arr, size_t index)
{
    EastValue *v = east_array_get(arr, index);
    return v ? v->data.integer : INT64_MIN;
}

static void test_producer(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_producer.beast2", err[64] = "emit_err_producer.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_producer.beast2\" --emit array -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "producer: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "producer: no output written");
    if (!data) return;

    EastType *at = east_array_type(&east_integer_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, at);
    CHECK(pages != NULL, "producer: emitted blob carries no index");
    if (pages) {
        CHECK(east_beast2_pages_element_count(pages) == 2500, "producer: element count %zu",
              east_beast2_pages_element_count(pages));
        CHECK(east_beast2_pages_segment_count(pages) > 1, "producer: expected multiple segments");
        CHECK(east_beast2_pages_self_contained(pages), "producer: segments not self-contained");
        EastValue *row = east_beast2_pages_element(pages, 1234);
        CHECK(row != NULL && row->data.integer == 2468, "producer: element(1234) wrong");
        if (row) east_value_release(row);
        east_beast2_pages_free(pages);
    }

    EastValue *whole = east_beast2_decode_full(data, len, at);
    CHECK(whole != NULL, "producer: whole decode failed");
    if (whole) {
        CHECK(whole->data.array.len == 2500, "producer: decoded length %zu", whole->data.array.len);
        CHECK(integer_at(whole, 0) == 0 && integer_at(whole, 2499) == 4998,
              "producer: decoded values wrong");
        east_value_release(whole);
    }
    free(data);
}

static void test_stream_fold(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_fold.beast2", err[64] = "emit_err_fold.txt";
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_fold.beast2\" --emit array --stream 0 -i \"%s/events.beast2\" "
             "-o %s",
             bin, fixtures, fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "fold: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "fold: no output written");
    if (!data) return;

    EastType *at = east_array_type(&east_integer_type);
    EastValue *sums = east_beast2_decode_full(data, len, at);
    CHECK(sums != NULL, "fold: decode failed");
    if (sums) {
        CHECK(sums->data.array.len == 2500, "fold: length %zu", sums->data.array.len);
        /* Running sums of [0..2500): prefix k holds k*(k+1)/2. */
        CHECK(integer_at(sums, 0) == 0, "fold: first sum wrong");
        CHECK(integer_at(sums, 99) == 4950, "fold: sum(99) wrong");
        CHECK(integer_at(sums, 2499) == 3123750, "fold: final sum wrong");
        east_value_release(sums);
    }
    free(data);
}

static void test_dict(const char *bin, const char *fixtures)
{
    char cmd[2048], out[64] = "emit_out_dict.beast2", err[64] = "emit_err_dict.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict.beast2\" --emit dict -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 0, "dict: expected exit 0, got %d", rc);
    if (rc != 0) return;

    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    CHECK(data != NULL, "dict: no output written");
    if (!data) return;

    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
    CHECK(pages != NULL, "dict: emitted blob carries no index");
    if (pages) {
        CHECK(east_beast2_pages_element_count(pages) == 1000, "dict: pair count %zu",
              east_beast2_pages_element_count(pages));
        east_beast2_pages_free(pages);
    }

    EastValue *dict = east_beast2_decode_full(data, len, dt);
    CHECK(dict != NULL, "dict: decode failed");
    if (dict) {
        CHECK(dict->data.dict.len == 1000, "dict: decoded size %zu", dict->data.dict.len);
        EastValue *key = east_integer(42);
        /* east_dict_get borrows — no release of the returned value. */
        EastValue *row = east_dict_get(dict, key);
        CHECK(row != NULL && strcmp(row->data.string.data, "row-42") == 0, "dict: get(42) wrong");
        east_value_release(key);
        east_value_release(dict);
    }
    free(data);
}

/* An aborted emission leaves no index in its output. */
static void check_no_index(const char *out, const char *label)
{
    size_t len = 0;
    uint8_t *data = read_file(out, &len);
    if (!data) return;
    EastType *dt = east_dict_type(&east_integer_type, &east_string_type);
    Beast2Pages *pages = east_beast2_pages_new(data, len, dt);
    CHECK(pages == NULL, "%s: aborted output unexpectedly carries an index", label);
    if (pages) east_beast2_pages_free(pages);
    free(east_builtin_get_error());
    free(data);
}

static void test_dict_out_of_order(const char *bin, const char *fixtures)
{
    /* The sink does one pass (issue #770): a key below the previous one ends
     * the emission with the canonical message, and the output stays
     * unfinalised. A re-keying producer partitions and merges instead. */
    char cmd[2048], out[64] = "emit_out_disorder.beast2", err[64] = "emit_err_disorder.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict_disorder.beast2\" --emit dict -o %s", bin,
             fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 1, "disorder: expected exit 1, got %d", rc);
    check_stderr_contains(err, "beast2 v5: Dict key emitted out of order: 1 after 2 — Set/Dict "
                               "emissions must ascend in East order");
    check_no_index(out, "disorder");
}

static void test_dict_duplicate(const char *bin, const char *fixtures)
{
    /* Duplicate keys are an error under any emission order: exit 1, the
     * canonical message, and no index in the aborted output. */
    char cmd[2048], out[64] = "emit_out_duplicate.beast2", err[64] = "emit_err_duplicate.txt";
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/emit_dict_duplicate.beast2\" --emit dict -o %s",
             bin, fixtures, out);
    int rc = run_cli(cmd, err);
    CHECK(rc == 1, "duplicate: expected exit 1, got %d", rc);
    check_stderr_contains(err, "duplicate Dict key emitted");
    check_no_index(out, "duplicate");
}

static void test_snapshot_guard(const char *bin, const char *fixtures)
{
    /* The snapshot manifest (format v1) carries no streaming flags, so a
     * captured emit invocation would replay with the wrong arity — the CLI
     * must refuse the combination at capture time (issue #508). */
    char cmd[2048], err[64] = "emit_err_snapshot.txt";
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run \"%s/emit_producer.beast2\" --emit array -o emit_out_snap.beast2 "
             "--snapshot emit_snap.east-snapshot",
             bin, fixtures);
    int rc = run_cli(cmd, err);
    CHECK(rc == 1, "snapshot guard: expected exit 1, got %d", rc);
    check_stderr_contains(err, "--snapshot does not capture --emit/--stream");
}

static void test_fold_contract(const char *bin, const char *fixtures)
{
    /* Issue #770: with --merge (dict) or --union (set) the sink folds
     * adjacent equal keys in emission order, and the file is byte-identical
     * to what the flag-less sink writes for the folded sequence. The
     * sequences fold key 999 — the last entry of a full 1000-element batch —
     * four times, which the flush rule keeps in the open batch. */
    static const char *programs[] = {"emit_merge_ascending", "emit_union_ascending"};
    for (size_t i = 0; i < 2; i++) {
        const char *program = programs[i];
        bool dict = i == 0;
        char cmd[4096], flags[1100], expected[64], folded[64], err[64];
        snprintf(expected, sizeof(expected), "emit_out_fold%zu_expected.beast2", i);
        snprintf(folded, sizeof(folded), "emit_out_fold%zu.beast2", i);
        snprintf(err, sizeof(err), "emit_err_fold%zu.txt", i);
        if (dict)
            snprintf(flags, sizeof(flags), "--emit dict --merge \"%s/emit_merge_concat.beast2\"",
                     fixtures);
        else
            snprintf(flags, sizeof(flags), "--emit set --union");

        snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/%s_folded.beast2\" --emit %s -o %s", bin,
                 fixtures, program, dict ? "dict" : "set", expected);
        int rc = run_cli(cmd, err);
        CHECK(rc == 0, "fold %s: the folded control expected exit 0, got %d", program, rc);

        snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/%s.beast2\" %s -o %s", bin, fixtures, program,
                 flags, folded);
        rc = run_cli(cmd, err);
        CHECK(rc == 0, "fold %s: expected exit 0, got %d", program, rc);
        if (rc != 0) continue;
        CHECK(same_bytes(expected, folded),
              "fold %s: not byte-identical to the flag-less sink's output for the folded sequence",
              program);
    }
}

/* The lifeline gate's bound on each wait: for the runner to open its output
 * (the sink opens the file before the body runs), and — once its stdin
 * closes — for it to exit. */
#define LIFELINE_WAIT_MS 10000
#define LIFELINE_OUTPUT "emit_out_spin.beast2"

#ifndef _WIN32
static void sleep_ms(long ms)
{
    struct timespec ts = {ms / 1000, (ms % 1000) * 1000000L};
    nanosleep(&ts, NULL);
}

static void test_exit_with_parent(const char *bin, const char *fixtures)
{
    /* Issue #770 gate (c): a runner started with --exit-with-parent and a
     * stdin pipe nobody writes exits once that pipe closes — while its body
     * is still computing (the fixture loops forever after one emission). */
    char ir[1024];
    snprintf(ir, sizeof(ir), "%s/emit_spin.beast2", fixtures);
    remove(LIFELINE_OUTPUT);
    int in_pipe[2], err_pipe[2];
    if (pipe(in_pipe) != 0) {
        CHECK(false, "lifeline: pipe failed");
        return;
    }
    if (pipe(err_pipe) != 0) {
        close(in_pipe[0]);
        close(in_pipe[1]);
        CHECK(false, "lifeline: pipe failed");
        return;
    }
    pid_t pid = fork();
    if (pid == 0) {
        dup2(in_pipe[0], STDIN_FILENO);
        dup2(err_pipe[1], STDERR_FILENO);
        close(in_pipe[0]);
        close(in_pipe[1]);
        close(err_pipe[0]);
        close(err_pipe[1]);
        execl(bin, bin, "run", "--exit-with-parent", ir, "--emit", "set", "-o", LIFELINE_OUTPUT,
              (char *)NULL);
        _exit(127);
    }
    close(in_pipe[0]);
    close(err_pipe[1]);
    if (pid < 0) {
        close(in_pipe[1]);
        close(err_pipe[0]);
        CHECK(false, "lifeline: fork failed");
        return;
    }

    bool running = false;
    bool gone = false;
    int status = 0;
    for (long waited = 0; !running && !gone && waited < LIFELINE_WAIT_MS; waited += 20) {
        running = file_exists(LIFELINE_OUTPUT);
        if (!running) {
            gone = waitpid(pid, &status, WNOHANG) == pid;
            if (!gone) sleep_ms(20);
        }
    }
    CHECK(running, "lifeline: the runner never opened its output%s",
          gone ? " (it exited first)" : "");

    close(in_pipe[1]); /* the lifeline closes */
    bool exited = gone;
    for (long waited = 0; !exited && waited <= LIFELINE_WAIT_MS; waited += 20) {
        if (waitpid(pid, &status, WNOHANG) == pid) {
            exited = true;
            break;
        }
        sleep_ms(20);
    }
    if (!exited) {
        kill(pid, SIGKILL);
        waitpid(pid, &status, 0);
    }
    CHECK(exited, "lifeline: the runner outlived its closed stdin by %d ms", LIFELINE_WAIT_MS);
    CHECK(!exited || (WIFEXITED(status) && WEXITSTATUS(status) == 1),
          "lifeline: expected the watcher's exit status 1, got wait status %d", status);

    /* Whatever the runner wrote, for the sanitizer scan. */
    char err[8192];
    size_t err_len = 0;
    err[0] = '\0';
    for (;;) {
        ssize_t n = read(err_pipe[0], err + err_len, sizeof(err) - 1 - err_len);
        if (n <= 0) break;
        err_len += (size_t)n;
        err[err_len] = '\0';
        if (err_len == sizeof(err) - 1) break;
    }
    close(err_pipe[0]);
    CHECK(strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL,
          "sanitizer report in CLI stderr:\n%s", err);
    /* The watcher's exit, not an error's: exit 1 with nothing reported. */
    CHECK(strstr(err, "Error") == NULL, "lifeline: the runner reported an error:\n%s", err);
    remove(LIFELINE_OUTPUT);
}
#else
static void test_exit_with_parent(const char *bin, const char *fixtures)
{
    /* Issue #770 gate (c): a runner started with --exit-with-parent and a
     * stdin pipe nobody writes exits once that pipe closes — while its body
     * is still computing (the fixture loops forever after one emission). */
    remove(LIFELINE_OUTPUT);
    SECURITY_ATTRIBUTES inherit = {sizeof(SECURITY_ATTRIBUTES), NULL, TRUE};
    HANDLE in_read = NULL, in_write = NULL, err_read = NULL, err_write = NULL;
    if (!CreatePipe(&in_read, &in_write, &inherit, 0)) {
        CHECK(false, "lifeline: CreatePipe failed (%lu)", GetLastError());
        return;
    }
    if (!CreatePipe(&err_read, &err_write, &inherit, 0)) {
        CloseHandle(in_read);
        CloseHandle(in_write);
        CHECK(false, "lifeline: CreatePipe failed (%lu)", GetLastError());
        return;
    }
    /* The child inherits only its own ends. */
    SetHandleInformation(in_write, HANDLE_FLAG_INHERIT, 0);
    SetHandleInformation(err_read, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si;
    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdInput = in_read;
    si.hStdOutput = err_write;
    si.hStdError = err_write;
    PROCESS_INFORMATION pi;
    char cmd[4096];
    snprintf(cmd, sizeof(cmd),
             "\"%s\" run --exit-with-parent \"%s/emit_spin.beast2\" --emit set -o " LIFELINE_OUTPUT,
             bin, fixtures);
    BOOL started = CreateProcessA(NULL, cmd, NULL, NULL, TRUE, 0, NULL, NULL, &si, &pi);
    CloseHandle(in_read);
    CloseHandle(err_write);
    if (!started) {
        CloseHandle(in_write);
        CloseHandle(err_read);
        CHECK(false, "lifeline: CreateProcess failed (%lu)", GetLastError());
        return;
    }

    bool running = false;
    bool gone = false;
    for (long waited = 0; !running && !gone && waited < LIFELINE_WAIT_MS; waited += 20) {
        running = file_exists(LIFELINE_OUTPUT);
        if (!running) {
            gone = WaitForSingleObject(pi.hProcess, 0) == WAIT_OBJECT_0;
            if (!gone) Sleep(20);
        }
    }
    CHECK(running, "lifeline: the runner never opened its output%s",
          gone ? " (it exited first)" : "");

    CloseHandle(in_write); /* the lifeline closes */
    bool exited = gone || WaitForSingleObject(pi.hProcess, LIFELINE_WAIT_MS) == WAIT_OBJECT_0;
    if (!exited) {
        TerminateProcess(pi.hProcess, 99);
        WaitForSingleObject(pi.hProcess, INFINITE);
    }
    DWORD code = 0;
    GetExitCodeProcess(pi.hProcess, &code);
    CHECK(exited, "lifeline: the runner outlived its closed stdin by %d ms", LIFELINE_WAIT_MS);
    CHECK(!exited || code == 1, "lifeline: expected the watcher's exit code 1, got %lu", code);

    /* Whatever the runner wrote. */
    char err[8192];
    size_t err_len = 0;
    err[0] = '\0';
    for (;;) {
        DWORD want = (DWORD)(sizeof(err) - 1 - err_len), got = 0;
        if (want == 0 || !ReadFile(err_read, err + err_len, want, &got, NULL) || got == 0) break;
        err_len += got;
        err[err_len] = '\0';
    }
    /* The watcher's exit, not an error's: exit 1 with nothing reported. */
    CHECK(strstr(err, "Error") == NULL, "lifeline: the runner reported an error:\n%s", err);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    CloseHandle(err_read);
    remove(LIFELINE_OUTPUT);
}
#endif

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    east_type_of_type_init();

    test_producer(argv[1], argv[2]);
    test_stream_fold(argv[1], argv[2]);
    test_dict(argv[1], argv[2]);
    test_dict_out_of_order(argv[1], argv[2]);
    test_dict_duplicate(argv[1], argv[2]);
    test_snapshot_guard(argv[1], argv[2]);
    test_fold_contract(argv[1], argv[2]);
    test_exit_with_parent(argv[1], argv[2]);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli emit gate: all checks passed\n");
    return 0;
}
