/*
 * CLI lazy paged-input gate (#516).
 *
 * Spawns the built `east-c` binary over the checked-in IR fixtures in
 * tests/fixtures (generated by tests/generate_fixtures.mjs from the TS side)
 * with EAST_LAZY_INPUT_BYTES=1, so every eligible collection input opens as
 * a lazy paged value, and pins the semantics the lazy contract promises:
 *
 *   1. iteration lock — mutating a dict inside its own `$.for` raises the
 *      canonical "Cannot modify Dict during iteration" on a lazily-opened
 *      input exactly as on eager (the paged loop's lock carries over to the
 *      hydrated child);
 *   2. keyed-read errors — `has` over a corrupt blob (non-disjoint spliced
 *      key ranges) propagates the pager error instead of answering `false`
 *      with exit 0;
 *   3. shape gate — an element type that transitively contains a mutable
 *      container decodes eagerly regardless of the threshold, so a write
 *      through a read-out element lands in the input.
 *
 * Runs in the ASan tree too (leak-check's ctest pass), where the spawned
 * CLI is itself instrumented; each case scans the child's stderr for
 * sanitizer reports.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef _WIN32
#include <sys/wait.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static char *read_text(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc(len > 0 ? (size_t)len + 1 : 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, len > 0 ? (size_t)len : 0, f);
    buf[rd] = '\0';
    fclose(f);
    return buf;
}

/* Runs one CLI invocation with stdout and stderr captured; returns the
 * child's exit code (-1 on spawn failure) and fails the gate on a sanitizer
 * report in the child's stderr. The threshold env var rides the command line
 * so the ASan tree needs no harness plumbing. */
static int run_cli(const char *cmdline, const char *out_path, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    snprintf(full, sizeof(full), "\"%s 1> \"%s\" 2> \"%s\"\"", cmdline, out_path, err_path);
#else
    snprintf(full, sizeof(full), "%s 1> \"%s\" 2> \"%s\"", cmdline, out_path, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif
    char *err = read_text(err_path);
    if (err) {
        CHECK(strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL,
              "sanitizer report in CLI stderr:\n%s", err);
        free(err);
    }
    return rc;
}

static void check_file_contains(const char *path, const char *needle)
{
    char *text = read_text(path);
    CHECK(text != NULL, "cannot read %s", path);
    if (!text) return;
    CHECK(strstr(text, needle) != NULL, "%s missing \"%s\"; got:\n%s", path, needle, text);
    free(text);
}

/* The env prefix that forces the lazy open for any input size. `system` runs
 * through the shell on POSIX; on Windows `set VAR=…&&` is the equivalent. */
#ifdef _WIN32
#define LAZY_ENV "set EAST_LAZY_INPUT_BYTES=1&& "
#else
#define LAZY_ENV "EAST_LAZY_INPUT_BYTES=1 "
#endif

static void test_paged_for_mutate(const char *bin, const char *fixtures)
{
    char cmd[2048];
    snprintf(cmd, sizeof(cmd),
             LAZY_ENV "\"%s\" run \"%s/paged_for_mutate.beast2\" -i \"%s/paged_table.beast2\"", bin,
             fixtures, fixtures);
    int rc = run_cli(cmd, "paged_out_mutate.txt", "paged_err_mutate.txt");
    CHECK(rc == 1, "paged for-mutate: expected exit 1, got %d", rc);
    check_file_contains("paged_err_mutate.txt", "Cannot modify Dict during iteration");
}

static void test_paged_has_corrupt(const char *bin, const char *fixtures)
{
    char cmd[2048];
    snprintf(cmd, sizeof(cmd),
             LAZY_ENV "\"%s\" run \"%s/paged_has.beast2\" -i \"%s/paged_corrupt.beast2\"", bin,
             fixtures, fixtures);
    int rc = run_cli(cmd, "paged_out_has.txt", "paged_err_has.txt");
    CHECK(rc == 1, "paged has: expected exit 1 on the corrupt blob, got %d", rc);
    check_file_contains("paged_err_has.txt", "not disjoint ascending key ranges");
    /* The wrong outcome this pins against: `false` on stdout with exit 0. */
    char *out = read_text("paged_out_has.txt");
    if (out) {
        CHECK(strstr(out, "false") == NULL, "paged has answered instead of erroring: %s", out);
        free(out);
    }
}

static void test_paged_shape_gate(const char *bin, const char *fixtures)
{
    char cmd[2048];
    snprintf(cmd, sizeof(cmd),
             LAZY_ENV "\"%s\" run \"%s/paged_nested_mutate.beast2\" -i \"%s/paged_nested.beast2\"",
             bin, fixtures, fixtures);
    int rc = run_cli(cmd, "paged_out_nested.txt", "paged_err_nested.txt");
    CHECK(rc == 0, "shape gate: expected exit 0, got %d", rc);
    /* 3 only if the write through the read-out element landed in the input —
     * i.e. the gate routed the mutable-nested shape to the eager decode. */
    check_file_contains("paged_out_nested.txt", "3");
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }

    test_paged_for_mutate(argv[1], argv[2]);
    test_paged_has_corrupt(argv[1], argv[2]);
    test_paged_shape_gate(argv[1], argv[2]);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli paged gate: all checks passed\n");
    return 0;
}
