/*
 * CLI --profile gate.
 *
 * Spawns the built `east-c` binary over profile_calls.beast2 (generated by
 * tests/generate_fixtures.mjs: a helper called 100 times from a loop) and
 * pins the epilogue: the helper appears with its call count and the source
 * location of its Function node, the program's answer is unchanged by
 * profiling, and nothing is printed without the flag.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef _WIN32
#include <sys/wait.h>
#endif

static int failures = 0;

#define CHECK(cond, ...)                                                                           \
    do {                                                                                           \
        if (!(cond)) {                                                                             \
            fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);                                   \
            fprintf(stderr, __VA_ARGS__);                                                          \
            fprintf(stderr, "\n");                                                                 \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

static char *read_text(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)len + 1);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    size_t rd = fread(buf, 1, (size_t)len, f);
    buf[rd] = '\0';
    fclose(f);
    return buf;
}

/* Runs one CLI invocation with stdout and stderr captured; returns the exit
 * code (-1 on spawn failure). */
static int run_cli(const char *cmdline, const char *out_path, const char *err_path)
{
    char full[4096];
#ifdef _WIN32
    snprintf(full, sizeof(full), "\"%s > \"%s\" 2> \"%s\"\"", cmdline, out_path, err_path);
#else
    snprintf(full, sizeof(full), "%s > \"%s\" 2> \"%s\"", cmdline, out_path, err_path);
#endif
    int rc = system(full);
#ifndef _WIN32
    rc = rc == -1 ? -1 : WEXITSTATUS(rc);
#endif
    return rc;
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s <east-c-binary> <fixtures-dir>\n", argv[0]);
        return 2;
    }
    const char *bin = argv[1], *fixtures = argv[2];
    char cmd[2048];

    /* With the flag: the answer on stdout, the profile on stderr. */
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/profile_calls.beast2\" --profile", bin, fixtures);
    int rc = run_cli(cmd, "profile_out.txt", "profile_err.txt");
    CHECK(rc == 0, "profile: expected exit 0, got %d", rc);
    char *out = read_text("profile_out.txt");
    char *err = read_text("profile_err.txt");
    CHECK(out && strstr(out, "100") != NULL, "profile: the program must still answer 100, got: %s",
          out ? out : "(none)");
    CHECK(err && strstr(err, "Profile (self time") != NULL, "profile: epilogue header missing:\n%s",
          err ? err : "(none)");
    CHECK(err && strstr(err, "100 calls") != NULL,
          "profile: the helper must be listed with 100 calls:\n%s", err ? err : "(none)");
    CHECK(err && strstr(err, "generate_fixtures.mjs:") != NULL,
          "profile: the helper must be placed at its source location:\n%s", err ? err : "(none)");
    CHECK(err && strstr(err, "AddressSanitizer") == NULL && strstr(err, "LeakSanitizer") == NULL,
          "profile: sanitizer report in CLI stderr:\n%s", err ? err : "(none)");
    free(out);
    free(err);

    /* Without the flag: the same answer and no profile. */
    snprintf(cmd, sizeof(cmd), "\"%s\" run \"%s/profile_calls.beast2\"", bin, fixtures);
    rc = run_cli(cmd, "noprofile_out.txt", "noprofile_err.txt");
    CHECK(rc == 0, "no profile: expected exit 0, got %d", rc);
    out = read_text("noprofile_out.txt");
    err = read_text("noprofile_err.txt");
    CHECK(out && strstr(out, "100") != NULL, "no profile: the program must answer 100");
    CHECK(err && strstr(err, "Profile") == NULL, "no profile: nothing must be printed:\n%s",
          err ? err : "(none)");
    free(out);
    free(err);

    if (failures > 0) {
        fprintf(stderr, "%d failure(s)\n", failures);
        return 1;
    }
    printf("cli profile gate: all checks passed\n");
    return 0;
}
