/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Dual-licensed under AGPL-3.0 and commercial license. See LICENSE for details.
 */
/** Warehouse fixture transcribed from docs/proposals/Roster Spec.html. */
import { ArrayType, BooleanType, DictType, FloatType, OptionType, SetType, StringType, StructType, SortedMap, SortedSet, DateTimeType, compareFor, none, some, variant, type ValueTypeOf } from "@elaraai/east";
import { Roster } from "@elaraai/e3-ui";
export const WarehousePerson = StructType({ name: StringType, team: StringType, position: StringType, skills: SetType(StringType), contract: FloatType, agency: BooleanType, trainer: BooleanType, trainee: BooleanType, usual: OptionType(StringType) });
export const WarehouseConfig = StructType({ groups: ArrayType(Roster.Types.Group), shifts: ArrayType(Roster.Types.Shift), duties: ArrayType(Roster.Types.Skill), positions: DictType(StringType, Roster.Types.Position), agencies: ArrayType(Roster.Types.Agency), rules: Roster.Types.Rules, costs: Roster.Types.Costs });
export const StaffScope = StructType({ key: StringType, name: StringType, team: StringType, position: StringType, agency: BooleanType, trainer: BooleanType });
export const warehouseStart = new Date("2028-03-05T00:00:00Z");
const stringOrder = compareFor(StringType);
export const warehouseConfig: ValueTypeOf<typeof WarehouseConfig> = {
    groups: [{"key":"inbound","label":"Inbound","skills":[{"key":"unload","label":"Unloading","code":"UL"},{"key":"putaway","label":"Put-away","code":"PA"},{"key":"reach","label":"Reach truck","code":"RT"},{"key":"xdock","label":"Cross-dock","code":"XD"},{"key":"rcvqa","label":"Receiving QA","code":"QA"},{"key":"yard","label":"Yard","code":"YD"}]},{"key":"picking","label":"Picking","skills":[{"key":"pick","label":"Order picking","code":"OP"},{"key":"voice","label":"Voice picking","code":"VP"},{"key":"replen","label":"Replenishment","code":"RP"},{"key":"cold","label":"Cold store · licence","code":"CS"}]},{"key":"dispatch","label":"Dispatch","skills":[{"key":"pack","label":"Packing","code":"PK"},{"key":"load","label":"Loading","code":"LD"},{"key":"label","label":"Labelling","code":"LB"},{"key":"returns","label":"Returns","code":"RN"},{"key":"admin","label":"Dispatch admin","code":"DA"},{"key":"hazmat","label":"Hazmat · licence","code":"HZ"}]}],
    shifts: [
        { key: "early", label: "Early", code: "E", start: { hour: 6n, minute: 0n }, hours: 8 },
        { key: "late", label: "Late", code: "L", start: { hour: 14n, minute: 0n }, hours: 8 },
        { key: "night", label: "Night", code: "N", start: { hour: 22n, minute: 0n }, hours: 8 },
    ],
    duties: [{ key: "general", label: "General duties", code: "GD" }],
    positions: new SortedMap([
        ["crew", { key: "crew", label: "Associate", code: "", lead: false }],
        ["lead", { key: "lead", label: "Supervisor", code: "SV", lead: true }],
        ["deputy", { key: "deputy", label: "Deputy supervisor", code: "DS", lead: true }],
        ["acting", { key: "acting", label: "Acting supervisor", code: "ACT", lead: true }],
    ], stringOrder),
    agencies: [{ key: "northside", name: "Northside Staffing" }],
    rules: { rest: 10, lead: true, trainer: true, skill: true, agree: true },
    costs: { currency: "AUD", rates: { permanent: 42, overtime: 63, agency: 51 }, budget: some(24800) },
};
export const warehousePeople: SortedMap<string, ValueTypeOf<typeof WarehousePerson>> = new SortedMap<string, ValueTypeOf<typeof WarehousePerson>>([
    ["aalder", { name: "A. Alder", team: "inbound", position: "lead", skills: new SortedSet(["unload","reach","xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["haspen", { name: "H. Aspen", team: "inbound", position: "crew", skills: new SortedSet(["unload","putaway"], stringOrder), contract: 38, agency: false, trainer: true, trainee: false, usual: some("early") }],
    ["rbirch", { name: "R. Birch", team: "inbound", position: "crew", skills: new SortedSet(["unload","putaway","xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["dbracken", { name: "D. Bracken", team: "inbound", position: "crew", skills: new SortedSet(["unload","xdock","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["lbriar", { name: "L. Briar", team: "inbound", position: "crew", skills: new SortedSet(["reach","xdock"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["wbrook", { name: "W. Brook", team: "inbound", position: "crew", skills: new SortedSet(["unload","reach","xdock"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["gcairn", { name: "G. Cairn", team: "inbound", position: "crew", skills: new SortedSet(["rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["pcedar", { name: "P. Cedar", team: "inbound", position: "crew", skills: new SortedSet(["unload","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["cclover", { name: "C. Clover", team: "inbound", position: "crew", skills: new SortedSet(["unload","putaway","reach"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["kcoppice", { name: "K. Coppice", team: "inbound", position: "crew", skills: new SortedSet(["unload","putaway"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["tcorrie", { name: "T. Corrie", team: "inbound", position: "crew", skills: new SortedSet(["unload","xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["fdune", { name: "F. Dune", team: "inbound", position: "crew", skills: new SortedSet(["xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["nelder", { name: "N. Elder", team: "inbound", position: "crew", skills: new SortedSet(["reach","xdock"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["bfallow", { name: "B. Fallow", team: "inbound", position: "crew", skills: new SortedSet(["unload","xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["jfern", { name: "J. Fern", team: "inbound", position: "crew", skills: new SortedSet(["rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["sfirth", { name: "S. Firth", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("early") }],
    ["eflint", { name: "E. Flint", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("early") }],
    ["mgorse", { name: "M. Gorse", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("early") }],
    ["aglen", { name: "A. Glen", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("early") }],
    ["hgrove", { name: "H. Grove", team: "inbound", position: "lead", skills: new SortedSet(["unload","xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["rhawthorn", { name: "R. Hawthorn", team: "inbound", position: "deputy", skills: new SortedSet(["unload","putaway","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["dheath", { name: "D. Heath", team: "inbound", position: "crew", skills: new SortedSet(["unload","putaway","xdock","yard"], stringOrder), contract: 38, agency: false, trainer: true, trainee: false, usual: some("late") }],
    ["lholm", { name: "L. Holm", team: "inbound", position: "crew", skills: new SortedSet(["unload","reach","xdock"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["winlet", { name: "W. Inlet", team: "inbound", position: "crew", skills: new SortedSet(["unload","putaway"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["givy", { name: "G. Ivy", team: "inbound", position: "crew", skills: new SortedSet(["reach","xdock"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["pjuniper", { name: "P. Juniper", team: "inbound", position: "crew", skills: new SortedSet(["unload","reach","xdock","rcvqa"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["ckestrel", { name: "C. Kestrel", team: "inbound", position: "crew", skills: new SortedSet(["unload","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["kknoll", { name: "K. Knoll", team: "inbound", position: "crew", skills: new SortedSet(["rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["tlarch", { name: "T. Larch", team: "inbound", position: "crew", skills: new SortedSet(["unload","reach","xdock","rcvqa","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["flinnet", { name: "F. Linnet", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("late") }],
    ["nloch", { name: "N. Loch", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("late") }],
    ["blupin", { name: "B. Lupin", team: "inbound", position: "lead", skills: new SortedSet(["unload","yard"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["jmarram", { name: "J. Marram", team: "inbound", position: "deputy", skills: new SortedSet(["unload","putaway","reach","rcvqa"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["smeadow", { name: "S. Meadow", team: "inbound", position: "crew", skills: new SortedSet(["unload","xdock","rcvqa"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["emere", { name: "E. Mere", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("night") }],
    ["mnettle", { name: "M. Nettle", team: "inbound", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("night") }],
    ["aosier", { name: "A. Osier", team: "picking", position: "lead", skills: new SortedSet(["pick","voice","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["hpebble", { name: "H. Pebble", team: "picking", position: "deputy", skills: new SortedSet(["pick","replen","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["rplover", { name: "R. Plover", team: "picking", position: "crew", skills: new SortedSet(["pick","voice","cold"], stringOrder), contract: 38, agency: false, trainer: true, trainee: false, usual: some("early") }],
    ["dquarry", { name: "D. Quarry", team: "picking", position: "crew", skills: new SortedSet(["cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["lrill", { name: "L. Rill", team: "picking", position: "crew", skills: new SortedSet(["pick","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["wrowan", { name: "W. Rowan", team: "picking", position: "crew", skills: new SortedSet(["pick","replen","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["grush", { name: "G. Rush", team: "picking", position: "crew", skills: new SortedSet(["replen","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["psedge", { name: "P. Sedge", team: "picking", position: "crew", skills: new SortedSet(["pick","voice","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["cshale", { name: "C. Shale", team: "picking", position: "crew", skills: new SortedSet([], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["kshingle", { name: "K. Shingle", team: "picking", position: "crew", skills: new SortedSet(["cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["tsorrel", { name: "T. Sorrel", team: "picking", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("early") }],
    ["fspinney", { name: "F. Spinney", team: "picking", position: "lead", skills: new SortedSet(["cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["nsprig", { name: "N. Sprig", team: "picking", position: "deputy", skills: new SortedSet(["replen"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["bswale", { name: "B. Swale", team: "picking", position: "crew", skills: new SortedSet(["cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: true, usual: some("late") }],
    ["jtansy", { name: "J. Tansy", team: "picking", position: "crew", skills: new SortedSet(["pick","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["steasel", { name: "S. Teasel", team: "picking", position: "crew", skills: new SortedSet(["pick","voice","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["ethistle", { name: "E. Thistle", team: "picking", position: "crew", skills: new SortedSet(["voice","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("late") }],
    ["mtor", { name: "M. Tor", team: "picking", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("late") }],
    ["atarn", { name: "A. Tarn", team: "picking", position: "lead", skills: new SortedSet(["pick","voice","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["hvetch", { name: "H. Vetch", team: "picking", position: "deputy", skills: new SortedSet(["cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["rwold", { name: "R. Wold", team: "picking", position: "crew", skills: new SortedSet(["replen","cold"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["dyarrow", { name: "D. Yarrow", team: "picking", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("night") }],
    ["lbramble", { name: "L. Bramble", team: "picking", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("night") }],
    ["wcopse", { name: "W. Copse", team: "dispatch", position: "crew", skills: new SortedSet(["pack","load"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["gember", { name: "G. Ember", team: "dispatch", position: "crew", skills: new SortedSet(["pack","load","label"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["pgarnet", { name: "P. Garnet", team: "dispatch", position: "crew", skills: new SortedSet(["label","returns"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["charrow", { name: "C. Harrow", team: "dispatch", position: "crew", skills: new SortedSet(["pack","load","returns"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["kjasper", { name: "K. Jasper", team: "dispatch", position: "crew", skills: new SortedSet(["label","returns","admin"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["tkelp", { name: "T. Kelp", team: "dispatch", position: "crew", skills: new SortedSet(["admin","hazmat"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
    ["flichen", { name: "F. Lichen", team: "dispatch", position: "crew", skills: new SortedSet([], stringOrder), contract: 40, agency: true, trainer: false, trainee: false, usual: some("early") }],
    ["nochre", { name: "N. Ochre", team: "inbound", position: "crew", skills: new SortedSet(["unload","xdock","rcvqa"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["bpumice", { name: "B. Pumice", team: "picking", position: "crew", skills: new SortedSet(["pick","voice"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("night") }],
    ["jquartz", { name: "J. Quartz", team: "dispatch", position: "deputy", skills: new SortedSet(["pack","label","returns","admin"], stringOrder), contract: 38, agency: false, trainer: false, trainee: false, usual: some("early") }],
], stringOrder);
type SeedRow = readonly [string, number, string, string, string | null, string, string, string | null, number, number, boolean | null];
const previousRows: readonly SeedRow[] = [
    ["p1-1",0,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["p1-2",1,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["p1-3",5,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["p1-4",6,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["p1-5",0,"inbound","early","haspen","perm","crew","unload",0,0,null],
    ["p1-6",1,"inbound","early","haspen","perm","crew","unload",0,0,null],
    ["p1-7",2,"inbound","early","haspen","perm","acting","unload",0,0,null],
    ["p1-8",3,"inbound","early","haspen","perm","acting","unload",0,0,null],
    ["p1-9",6,"inbound","early","haspen","perm","crew","unload",0,0,null],
    ["p1-10",0,"inbound","early","rbirch","perm","crew","putaway",0,0,null],
    ["p1-11",1,"inbound","early","rbirch","perm","crew","putaway",0,0,null],
    ["p1-12",2,"inbound","early","rbirch","perm","crew","unload",0,0,null],
    ["p1-13",6,"inbound","early","rbirch","perm","crew","unload",0,0,null],
    ["p1-14",1,"inbound","early","dbracken","perm","crew","xdock",0,0,null],
    ["p1-15",2,"inbound","early","dbracken","perm","crew","unload",0,0,null],
    ["p1-16",3,"inbound","early","dbracken","perm","crew","unload",0,0,null],
    ["p1-17",4,"inbound","early","dbracken","perm","acting","unload",0,0,null],
    ["p1-18",0,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["p1-19",1,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["p1-20",2,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["p1-21",5,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["p1-22",6,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["p1-23",1,"inbound","early","wbrook","perm","crew","xdock",0,0,null],
    ["p1-24",2,"inbound","early","wbrook","perm","crew","reach",0,0,null],
    ["p1-25",3,"inbound","early","wbrook","perm","crew","unload",0,0,null],
    ["p1-26",4,"inbound","early","wbrook","perm","crew","unload",0,0,null],
    ["p1-27",5,"inbound","early","wbrook","perm","crew","unload",0,0,null],
    ["p1-28",3,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["p1-29",4,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["p1-30",5,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["p1-31",6,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["p1-32",0,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["p1-33",1,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["p1-34",2,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["p1-35",3,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["p1-36",6,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["p1-37",0,"inbound","early","cclover","perm","crew",null,0,0,null],
    ["p1-38",1,"inbound","early","cclover","perm","crew",null,0,0,null],
    ["p1-39",2,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["p1-40",3,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["p1-41",6,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["p1-42",0,"inbound","early","kcoppice","perm","crew",null,0,0,null],
    ["p1-43",1,"inbound","early","kcoppice","perm","crew",null,0,0,null],
    ["p1-44",2,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["p1-45",3,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["p1-46",4,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["p1-47",0,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["p1-48",3,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["p1-49",4,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["p1-50",5,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["p1-51",6,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["p1-52",0,"inbound","early","fdune","perm","crew","xdock",0,0,null],
    ["p1-53",4,"inbound","early","fdune","perm","crew","xdock",0,0,null],
    ["p1-54",5,"inbound","early","fdune","perm","crew","xdock",0,0,null],
    ["p1-55",6,"inbound","early","fdune","perm","crew","xdock",0,0,null],
    ["p1-56",3,"inbound","early","nelder","perm","crew","reach",0,0,null],
    ["p1-57",4,"inbound","early","nelder","perm","crew","reach",0,0,null],
    ["p1-58",5,"inbound","early","nelder","perm","crew",null,0,0,null],
    ["p1-59",6,"inbound","early","nelder","perm","crew","reach",0,0,null],
    ["p1-60",2,"inbound","early","bfallow","perm","crew","xdock",0,0,null],
    ["p1-61",3,"inbound","early","bfallow","perm","crew","xdock",0,0,null],
    ["p1-62",4,"inbound","early","bfallow","perm","crew",null,0,0,null],
    ["p1-63",5,"inbound","early","bfallow","perm","crew",null,0,0,null],
    ["p1-64",6,"inbound","early","bfallow","perm","crew","xdock",0,0,null],
    ["p1-65",2,"inbound","early","jfern","perm","crew","rcvqa",0,0,null],
    ["p1-66",3,"inbound","early","jfern","perm","crew","yard",0,0,null],
    ["p1-67",4,"inbound","early","jfern","perm","crew",null,0,0,null],
    ["p1-68",5,"inbound","early","jfern","perm","crew",null,0,0,null],
    ["p1-69",0,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["p1-70",1,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["p1-71",2,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["p1-72",3,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["p1-73",6,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["p1-74",2,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["p1-75",3,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["p1-76",4,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["p1-77",5,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["p1-78",6,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["p1-79",0,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["p1-80",1,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["p1-81",2,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["p1-82",3,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["p1-83",6,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["p1-84",0,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["p1-85",1,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["p1-86",4,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["p1-87",5,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["p1-88",6,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["p1-89",3,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["p1-90",4,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["p1-91",5,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["p1-92",6,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["p1-93",1,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["p1-94",2,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["p1-95",3,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["p1-96",4,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["p1-97",2,"inbound","late","dheath","perm","crew","unload",0,0,null],
    ["p1-98",3,"inbound","late","dheath","perm","crew","xdock",0,0,null],
    ["p1-99",4,"inbound","late","dheath","perm","crew","xdock",0,0,null],
    ["p1-100",5,"inbound","late","dheath","perm","crew","unload",0,0,null],
    ["p1-101",1,"inbound","late","lholm","perm","crew","unload",0,0,null],
    ["p1-102",2,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["p1-103",3,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["p1-104",4,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["p1-105",5,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["p1-106",2,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["p1-107",3,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["p1-108",4,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["p1-109",5,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["p1-110",6,"inbound","late","winlet","perm","crew","unload",0,0,null],
    ["p1-111",0,"inbound","late","givy","perm","acting","xdock",0,0,null],
    ["p1-112",1,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["p1-113",2,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["p1-114",3,"inbound","late","givy","perm","crew",null,0,0,null],
    ["p1-115",4,"inbound","late","givy","perm","crew",null,0,0,null],
    ["p1-116",0,"inbound","late","pjuniper","perm","crew","unload",0,0,null],
    ["p1-117",1,"inbound","late","pjuniper","perm","crew","xdock",0,0,null],
    ["p1-118",2,"inbound","late","pjuniper","perm","crew","rcvqa",0,0,null],
    ["p1-119",5,"inbound","late","pjuniper","perm","crew","xdock",0,0,null],
    ["p1-120",6,"inbound","late","pjuniper","perm","crew","xdock",0,0,null],
    ["p1-121",0,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["p1-122",4,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["p1-123",5,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["p1-124",6,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["p1-125",2,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["p1-126",3,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["p1-127",4,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["p1-128",5,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["p1-129",6,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["p1-130",0,"inbound","late","tlarch","perm","crew",null,0,0,null],
    ["p1-131",1,"inbound","late","tlarch","perm","crew","rcvqa",0,0,null],
    ["p1-132",4,"inbound","late","tlarch","perm","crew","yard",0,0,null],
    ["p1-133",5,"inbound","late","tlarch","perm","crew","yard",0,0,null],
    ["p1-134",6,"inbound","late","tlarch","perm","crew","xdock",0,0,null],
    ["p1-135",1,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["p1-136",2,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["p1-137",3,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["p1-138",4,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["p1-139",5,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["p1-140",0,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["p1-141",1,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["p1-142",2,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["p1-143",5,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["p1-144",6,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["p1-145",0,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["p1-146",4,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["p1-147",5,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["p1-148",6,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["p1-149",2,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["p1-150",3,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["p1-151",4,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["p1-152",5,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["p1-153",3,"inbound","night","smeadow","perm","crew","unload",0,0,null],
    ["p1-154",4,"inbound","night","smeadow","perm","crew","rcvqa",0,0,null],
    ["p1-155",5,"inbound","night","smeadow","perm","crew","unload",0,0,null],
    ["p1-156",6,"inbound","night","smeadow","perm","crew","unload",0,0,null],
    ["p1-157",0,"inbound","night","emere","ag","crew",null,0,0,null],
    ["p1-158",3,"inbound","night","emere","ag","crew",null,0,0,null],
    ["p1-159",4,"inbound","night","emere","ag","crew",null,0,0,null],
    ["p1-160",5,"inbound","night","emere","ag","crew",null,0,0,null],
    ["p1-161",6,"inbound","night","emere","ag","crew",null,0,0,null],
    ["p1-162",0,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["p1-163",1,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["p1-164",2,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["p1-165",5,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["p1-166",6,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["p1-167",2,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["p1-168",3,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["p1-169",4,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["p1-170",5,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["p1-171",1,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["p1-172",2,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["p1-173",3,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["p1-174",4,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["p1-175",0,"picking","early","rplover","perm","acting","pick",0,0,null],
    ["p1-176",1,"picking","early","rplover","perm","crew","pick",0,0,null],
    ["p1-177",2,"picking","early","rplover","perm","crew","voice",0,0,null],
    ["p1-178",3,"picking","early","rplover","perm","crew","voice",0,0,null],
    ["p1-179",6,"picking","early","rplover","perm","acting","pick",0,0,null],
    ["p1-180",0,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["p1-181",4,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["p1-182",5,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["p1-183",6,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["p1-184",2,"picking","early","lrill","perm","crew",null,0,0,null],
    ["p1-185",3,"picking","early","lrill","perm","crew",null,0,0,null],
    ["p1-186",4,"picking","early","lrill","perm","crew","pick",0,0,null],
    ["p1-187",5,"picking","early","lrill","perm","crew","pick",0,0,null],
    ["p1-188",6,"picking","early","lrill","perm","crew","pick",0,0,null],
    ["p1-189",0,"picking","early","wrowan","perm","crew","pick",0,0,null],
    ["p1-190",1,"picking","early","wrowan","perm","crew","replen",0,0,null],
    ["p1-191",5,"picking","early","wrowan","perm","crew","pick",0,0,null],
    ["p1-192",6,"picking","early","wrowan","perm","crew","pick",0,0,null],
    ["p1-193",0,"picking","early","grush","perm","crew","replen",0,0,null],
    ["p1-194",1,"picking","early","grush","perm","crew",null,0,0,null],
    ["p1-195",4,"picking","early","grush","perm","crew","replen",0,0,null],
    ["p1-196",5,"picking","early","grush","perm","crew","replen",0,0,null],
    ["p1-197",6,"picking","early","grush","perm","crew","replen",0,0,null],
    ["p1-198",0,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["p1-199",1,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["p1-200",2,"picking","early","psedge","perm","crew",null,0,0,null],
    ["p1-201",5,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["p1-202",6,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["p1-203",0,"picking","early","cshale","perm","crew",null,0,0,null],
    ["p1-204",1,"picking","early","cshale","perm","crew",null,0,0,null],
    ["p1-205",2,"picking","early","cshale","perm","crew",null,0,0,null],
    ["p1-206",3,"picking","early","cshale","perm","crew",null,0,0,null],
    ["p1-207",4,"picking","early","cshale","perm","crew",null,0,0,null],
    ["p1-208",3,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["p1-209",4,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["p1-210",5,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["p1-211",6,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["p1-212",2,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["p1-213",3,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["p1-214",4,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["p1-215",5,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["p1-216",6,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["p1-217",0,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["p1-218",1,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["p1-219",5,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["p1-220",6,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["p1-221",3,"picking","late","nsprig","perm","deputy","general",0,0,null],
    ["p1-222",4,"picking","late","nsprig","perm","deputy","general",0,0,null],
    ["p1-223",5,"picking","late","nsprig","perm","deputy","general",0,0,null],
    ["p1-224",6,"picking","late","nsprig","perm","deputy","general",0,0,null],
    ["p1-225",2,"picking","late","bswale","perm","acting","general",0,0,null],
    ["p1-226",3,"picking","late","bswale","perm","crew",null,0,0,null],
    ["p1-227",4,"picking","late","bswale","perm","crew",null,0,0,null],
    ["p1-228",5,"picking","late","bswale","perm","crew",null,0,0,null],
    ["p1-229",6,"picking","late","bswale","perm","crew",null,0,0,null],
    ["p1-230",0,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["p1-231",1,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["p1-232",2,"picking","late","jtansy","perm","crew",null,0,0,null],
    ["p1-233",5,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["p1-234",6,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["p1-235",0,"picking","late","steasel","perm","crew",null,0,0,null],
    ["p1-236",1,"picking","late","steasel","perm","crew","voice",0,0,null],
    ["p1-237",4,"picking","late","steasel","perm","crew","pick",0,0,null],
    ["p1-238",5,"picking","late","steasel","perm","crew","voice",0,0,null],
    ["p1-239",6,"picking","late","steasel","perm","crew","voice",0,0,null],
    ["p1-240",2,"picking","late","ethistle","perm","crew",null,0,0,null],
    ["p1-241",3,"picking","late","ethistle","perm","crew",null,0,0,null],
    ["p1-242",4,"picking","late","ethistle","perm","crew","voice",0,0,null],
    ["p1-243",5,"picking","late","ethistle","perm","crew",null,0,0,null],
    ["p1-244",0,"picking","late","mtor","ag","crew",null,0,0,null],
    ["p1-245",1,"picking","late","mtor","ag","crew",null,0,0,null],
    ["p1-246",4,"picking","late","mtor","ag","crew",null,0,0,null],
    ["p1-247",5,"picking","late","mtor","ag","crew",null,0,0,null],
    ["p1-248",6,"picking","late","mtor","ag","crew",null,0,0,null],
    ["p1-249",3,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["p1-250",4,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["p1-251",5,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["p1-252",6,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["p1-253",1,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["p1-254",2,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["p1-255",3,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["p1-256",4,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["p1-257",0,"picking","night","rwold","perm","acting","general",0,0,null],
    ["p1-258",1,"picking","night","rwold","perm","crew","general",0,0,null],
    ["p1-259",2,"picking","night","rwold","perm","crew","general",0,0,null],
    ["p1-260",5,"picking","night","rwold","perm","crew","general",0,0,null],
    ["p1-261",6,"picking","night","rwold","perm","crew","general",0,0,null],
    ["p1-262",0,"picking","night","dyarrow","ag","crew","general",0,0,null],
    ["p1-263",1,"picking","night","dyarrow","ag","crew",null,0,0,null],
    ["p1-264",4,"picking","night","dyarrow","ag","crew",null,0,0,null],
    ["p1-265",5,"picking","night","dyarrow","ag","crew",null,0,0,null],
    ["p1-266",6,"picking","night","dyarrow","ag","crew","general",0,0,null],
    ["p1-267",0,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["p1-268",1,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["p1-269",2,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["p1-270",3,"picking","night","lbramble","ag","crew","general",0,0,null],
    ["p1-271",6,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["p1-272",0,"dispatch","early","wcopse","perm","crew","pack",0,0,null],
    ["p1-273",1,"dispatch","early","wcopse","perm","crew","pack",0,0,null],
    ["p1-274",4,"dispatch","early","wcopse","perm","acting","pack",0,0,null],
    ["p1-275",5,"dispatch","early","wcopse","perm","acting","pack",0,0,null],
    ["p1-276",6,"dispatch","early","wcopse","perm","crew","pack",0,0,null],
    ["p1-277",2,"dispatch","early","gember","perm","acting","pack",0,0,null],
    ["p1-278",3,"dispatch","early","gember","perm","acting","pack",0,0,null],
    ["p1-279",4,"dispatch","early","gember","perm","crew",null,0,0,null],
    ["p1-280",5,"dispatch","early","gember","perm","crew",null,0,0,null],
    ["p1-281",6,"dispatch","early","gember","perm","crew","pack",0,0,null],
    ["p1-282",0,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["p1-283",1,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["p1-284",2,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["p1-285",3,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["p1-286",6,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["p1-287",0,"dispatch","early","charrow","perm","crew","returns",0,0,null],
    ["p1-288",1,"dispatch","early","charrow","perm","crew","returns",0,0,null],
    ["p1-289",2,"dispatch","early","charrow","perm","crew","returns",0,0,null],
    ["p1-290",6,"dispatch","early","charrow","perm","crew","load",0,0,null],
    ["p1-291",2,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["p1-292",3,"dispatch","early","kjasper","perm","crew","returns",0,0,null],
    ["p1-293",4,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["p1-294",5,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["p1-295",6,"dispatch","early","kjasper","perm","crew","returns",0,0,null],
    ["p1-296",2,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["p1-297",3,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["p1-298",4,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["p1-299",5,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["p1-300",6,"dispatch","early","tkelp","perm","crew","admin",0,0,null],
    ["p1-301",0,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["p1-302",1,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["p1-303",2,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["p1-304",3,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["p1-305",6,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["p1-306",1,"inbound","night","nochre","perm","acting","unload",0,0,null],
    ["p1-307",2,"inbound","night","nochre","perm","crew","unload",0,0,null],
    ["p1-308",3,"inbound","night","nochre","perm","crew","rcvqa",0,0,null],
    ["p1-309",2,"picking","night","bpumice","perm","crew","pick",0,0,null],
    ["p1-310",3,"picking","night","bpumice","perm","crew",null,0,0,null],
    ["p1-311",0,"picking","night","bpumice","perm","crew","pick",0,0,null],
    ["p1-312",1,"dispatch","early","jquartz","perm","deputy",null,0,0,null],
    ["p1-313",6,"dispatch","early","jquartz","perm","deputy",null,0,0,null],
    ["p1-314",0,"dispatch","early","jquartz","perm","deputy",null,0,0,null],
];
const previousTargets: readonly (readonly [number, string, string, number, Readonly<Record<string, number>>])[] = [
    [0,"inbound","early",12,{"unload":21,"putaway":15,"reach":14,"xdock":21,"rcvqa":14,"yard":7}],
    [1,"inbound","early",12,{"unload":21,"putaway":15,"reach":14,"xdock":21,"rcvqa":14,"yard":7}],
    [2,"inbound","early",14,{"unload":25,"putaway":17,"reach":16,"xdock":25,"rcvqa":16,"yard":8}],
    [3,"inbound","early",14,{"unload":25,"putaway":17,"reach":16,"xdock":25,"rcvqa":16,"yard":8}],
    [4,"inbound","early",11,{"unload":20,"putaway":8,"reach":13,"xdock":20,"rcvqa":13,"yard":6}],
    [5,"inbound","early",11,{"unload":20,"reach":13,"xdock":20,"rcvqa":13,"yard":6}],
    [6,"inbound","early",16,{"unload":29,"putaway":19,"reach":19,"xdock":29,"rcvqa":19,"yard":9}],
    [0,"inbound","late",5,{"unload":12,"xdock":12,"rcvqa":12,"yard":6}],
    [1,"inbound","late",7,{"unload":16,"xdock":16,"rcvqa":16,"yard":8}],
    [2,"inbound","late",9,{"unload":21,"xdock":21,"rcvqa":16,"yard":11}],
    [3,"inbound","late",8,{"unload":19,"xdock":19,"rcvqa":16,"yard":9}],
    [4,"inbound","late",10,{"unload":23,"xdock":23,"rcvqa":23,"yard":12}],
    [5,"inbound","late",10,{"unload":23,"xdock":23,"rcvqa":23,"yard":12}],
    [6,"inbound","late",7,{"unload":16,"xdock":16,"rcvqa":16,"yard":8}],
    [0,"inbound","night",3,{"unload":8}],
    [1,"inbound","night",2,{"unload":8,"rcvqa":6}],
    [2,"inbound","night",3,{"unload":16,"rcvqa":9}],
    [3,"inbound","night",4,{"unload":21,"rcvqa":12}],
    [4,"inbound","night",4,{"unload":21,"rcvqa":12}],
    [5,"inbound","night",5,{"unload":24,"rcvqa":15}],
    [6,"inbound","night",4,{"unload":16,"rcvqa":8}],
    [0,"picking","early",6,{"pick":19,"voice":12,"replen":12,"cold":3,"general":4}],
    [1,"picking","early",6,{"pick":19,"voice":12,"replen":12,"cold":3,"general":4}],
    [2,"picking","early",7,{"pick":22,"voice":14,"replen":8,"cold":4,"general":4}],
    [3,"picking","early",7,{"pick":22,"voice":14,"replen":8,"cold":4,"general":4}],
    [4,"picking","early",8,{"pick":24,"voice":8,"replen":16,"cold":4,"general":5}],
    [5,"picking","early",8,{"pick":25,"voice":16,"replen":16,"cold":4,"general":5}],
    [6,"picking","early",9,{"pick":28,"voice":16,"replen":16,"cold":5,"general":5}],
    [0,"picking","late",4,{"pick":8,"voice":7,"cold":4,"general":11}],
    [1,"picking","late",5,{"pick":10,"voice":8,"cold":4,"general":13}],
    [2,"picking","late",3,{"pick":6,"voice":5,"cold":3,"general":8}],
    [3,"picking","late",3,{"voice":5,"replen":3,"cold":3,"general":8}],
    [4,"picking","late",5,{"pick":8,"voice":9,"replen":5,"cold":4,"general":13}],
    [5,"picking","late",7,{"pick":14,"voice":12,"replen":7,"cold":6,"general":18}],
    [6,"picking","late",7,{"pick":14,"voice":8,"replen":7,"cold":6,"general":18}],
    [0,"picking","night",4,{"pick":8,"cold":5,"general":17}],
    [1,"picking","night",4,{"cold":5,"general":17}],
    [2,"picking","night",5,{"pick":8,"cold":6,"general":21}],
    [3,"picking","night",4,{"pick":11,"cold":5,"general":17}],
    [4,"picking","night",3,{"pick":8,"cold":4,"general":13}],
    [5,"picking","night",3,{"pick":8,"cold":4,"general":13}],
    [6,"picking","night",4,{"pick":8,"cold":5,"general":17}],
    [0,"dispatch","early",6,{"pack":13,"load":6,"label":9,"returns":9,"admin":6}],
    [1,"dispatch","early",5,{"pack":11,"load":5,"label":8,"returns":8,"admin":5}],
    [2,"dispatch","early",6,{"pack":13,"load":6,"label":9,"returns":9,"admin":6,"hazmat":6}],
    [3,"dispatch","early",5,{"pack":8,"load":5,"label":8,"returns":8,"admin":5,"hazmat":5}],
    [4,"dispatch","early",4,{"pack":9,"load":4,"label":6,"returns":6,"admin":4,"hazmat":4}],
    [5,"dispatch","early",4,{"pack":9,"load":4,"label":6,"returns":6,"admin":4,"hazmat":4}],
    [6,"dispatch","early",8,{"pack":17,"load":8,"label":13,"returns":13,"admin":8,"hazmat":8}],
    [0,"dispatch","late",0,{}],
    [1,"dispatch","late",0,{}],
    [2,"dispatch","late",0,{}],
    [3,"dispatch","late",0,{}],
    [4,"dispatch","late",0,{}],
    [5,"dispatch","late",0,{}],
    [6,"dispatch","late",0,{}],
    [0,"dispatch","night",0,{}],
    [1,"dispatch","night",0,{}],
    [2,"dispatch","night",0,{}],
    [3,"dispatch","night",0,{}],
    [4,"dispatch","night",0,{}],
    [5,"dispatch","night",0,{}],
    [6,"dispatch","night",0,{}],
];
const currentRows: readonly SeedRow[] = [
    ["s1",4,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["s2",0,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["s3",1,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["s4",6,"inbound","early","aalder","perm","lead","unload",0,0,null],
    ["s5",4,"inbound","early","haspen","perm","crew","unload",0,0,null],
    ["s6",0,"inbound","early","haspen","perm","crew","unload",0,0,null],
    ["s7",1,"inbound","early","haspen","perm","crew","unload",0,0,null],
    ["s8",2,"inbound","early","haspen","perm","acting","unload",0,0,null],
    ["s9",3,"inbound","early","haspen","perm","acting","unload",0,0,null],
    ["s10",4,"inbound","early","rbirch","perm","crew","unload",0,0,null],
    ["s11",1,"inbound","early","rbirch","perm","crew","putaway",0,0,null],
    ["s12",2,"inbound","early","rbirch","perm","crew","unload",0,0,null],
    ["s13",3,"inbound","early","rbirch","perm","crew","unload",0,0,null],
    ["s14",4,"inbound","early","dbracken","perm","crew","unload",0,0,null],
    ["s15",0,"inbound","early","dbracken","perm","crew","xdock",0,0,null],
    ["s16",5,"inbound","early","dbracken","perm","acting","unload",0,0,null],
    ["s17",6,"inbound","early","dbracken","perm","crew","unload",0,0,null],
    ["s18",4,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["s19",2,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["s20",3,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["s21",5,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["s22",6,"inbound","early","lbriar","perm","crew","reach",0,0,null],
    ["s23",4,"inbound","early","wbrook","perm","crew","reach",0,0,null],
    ["s24",2,"inbound","early","wbrook","perm","crew","unload",0,0,null],
    ["s25",3,"inbound","early","wbrook","perm","crew","xdock",0,0,null],
    ["s26",5,"inbound","early","wbrook","perm","crew","xdock",0,0,null],
    ["s27",6,"inbound","early","wbrook","perm","crew","xdock",0,0,null],
    ["s28",4,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["s29",3,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["s30",5,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["s31",6,"inbound","early","gcairn","perm","crew","rcvqa",0,0,null],
    ["s32",4,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["s33",2,"inbound","early","pcedar","perm","crew","rcvqa",0,0,null],
    ["s34",3,"inbound","early","pcedar","perm","crew",null,0,0,null],
    ["s35",5,"inbound","early","pcedar","perm","crew",null,0,0,null],
    ["s36",6,"inbound","early","pcedar","perm","crew",null,0,0,null],
    ["s37",4,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["s38",1,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["s39",2,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["s40",3,"inbound","late","cclover","perm","crew","unload",0,2,true],
    ["s41",5,"inbound","early","cclover","perm","crew","putaway",0,0,null],
    ["s42",4,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["s43",0,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["s44",1,"inbound","early","kcoppice","perm","crew",null,0,0,null],
    ["s45",2,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["s46",6,"inbound","early","kcoppice","perm","crew","putaway",0,0,null],
    ["s47",4,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["s48",0,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["s49",1,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["s50",2,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["s51",3,"inbound","early","tcorrie","perm","crew","xdock",0,0,null],
    ["s52",4,"inbound","early","fdune","perm","crew","xdock",0,0,null],
    ["s53",3,"inbound","early","fdune","perm","crew",null,0,0,null],
    ["s54",5,"inbound","early","fdune","perm","crew",null,0,0,null],
    ["s55",6,"inbound","early","fdune","perm","crew","xdock",0,0,null],
    ["s56",4,"inbound","early","nelder","perm","crew","xdock",0,0,null],
    ["s57",0,"inbound","early","nelder","perm","crew","reach",0,0,null],
    ["s58",1,"inbound","early","nelder","perm","crew","reach",0,0,null],
    ["s59",6,"inbound","early","nelder","perm","crew",null,0,0,null],
    ["s60",4,"inbound","early","bfallow","perm","crew","xdock",0,0,null],
    ["s61",1,"inbound","early","bfallow","perm","crew","xdock",0,0,null],
    ["s62",2,"inbound","early","bfallow","perm","crew","xdock",0,0,null],
    ["s63",3,"inbound","early","bfallow","perm","crew",null,0,0,null],
    ["s64",5,"inbound","early","bfallow","perm","crew",null,0,0,null],
    ["s65",4,"inbound","early","jfern","perm","crew","yard",0,0,null],
    ["s66",0,"inbound","early","jfern","perm","crew","rcvqa",0,0,null],
    ["s67",1,"inbound","early","jfern","perm","crew","rcvqa",0,0,null],
    ["s68",6,"inbound","early","jfern","perm","crew",null,0,0,null],
    ["s69",4,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["s70",0,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["s71",1,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["s72",2,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["s73",6,"inbound","early","sfirth","ag","crew",null,0,0,null],
    ["s74",4,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["s75",0,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["s76",1,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["s77",2,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["s78",3,"inbound","early","eflint","ag","crew",null,0,0,null],
    ["s79",4,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["s80",0,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["s81",1,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["s82",2,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["s83",3,"inbound","early","mgorse","ag","crew",null,0,0,null],
    ["s84",4,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["s85",0,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["s86",1,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["s87",2,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["s88",3,"inbound","early","aglen","ag","crew",null,0,0,null],
    ["s89",4,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["s90",1,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["s91",2,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["s92",3,"inbound","late","hgrove","perm","lead","unload",0,0,null],
    ["s93",4,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["s94",0,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["s95",5,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["s96",6,"inbound","late","rhawthorn","perm","deputy","unload",0,0,null],
    ["s97",4,"inbound","late","dheath","perm","crew","unload",0,0,null],
    ["s98",1,"inbound","late","dheath","perm","crew","unload",0,0,null],
    ["s99",2,"inbound","late","dheath","perm","crew","unload",0,0,null],
    ["s100",3,"inbound","late","dheath","perm","crew","xdock",0,0,null],
    ["s101",4,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["s102",0,"inbound","late","lholm","perm","crew","unload",0,0,null],
    ["s103",1,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["s104",5,"inbound","late","lholm","perm","crew","xdock",0,0,null],
    ["s105",6,"inbound","late","lholm","perm","crew","unload",0,0,null],
    ["s106",4,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["s107",0,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["s108",3,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["s109",5,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["s110",6,"inbound","late","winlet","perm","crew",null,0,0,null],
    ["s111",4,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["s112",0,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["s113",1,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["s114",2,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["s115",3,"inbound","late","givy","perm","crew","xdock",0,0,null],
    ["s116",4,"inbound","late","pjuniper","perm","crew","xdock",0,0,null],
    ["s117",0,"inbound","late","pjuniper","perm","crew","xdock",0,0,null],
    ["s118",1,"inbound","late","pjuniper","perm","crew","rcvqa",0,0,null],
    ["s119",2,"inbound","late","pjuniper","perm","crew","xdock",0,0,null],
    ["s120",3,"inbound","late","pjuniper","perm","crew","rcvqa",0,0,null],
    ["s121",4,"inbound","late","ckestrel","perm","crew","rcvqa",0,2,false],
    ["s122",0,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["s123",1,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["s124",6,"inbound","late","ckestrel","perm","crew","rcvqa",0,0,null],
    ["s125",4,"inbound","late","kknoll","perm","crew","rcvqa",2,0,false],
    ["s126",0,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["s127",1,"inbound","late","kknoll","perm","crew","yard",0,0,null],
    ["s128",2,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["s129",3,"inbound","late","kknoll","perm","crew","rcvqa",0,0,null],
    ["s130",4,"inbound","late","tlarch","perm","crew","rcvqa",2,0,false],
    ["s131",0,"inbound","late","tlarch","perm","crew","yard",0,0,null],
    ["s132",1,"inbound","late","tlarch","perm","crew",null,0,0,null],
    ["s133",2,"inbound","late","tlarch","perm","crew","rcvqa",0,0,null],
    ["s134",6,"inbound","late","tlarch","perm","crew","xdock",0,0,null],
    ["s135",4,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["s136",0,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["s137",1,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["s138",2,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["s139",6,"inbound","late","flinnet","ag","crew",null,0,0,null],
    ["s140",4,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["s141",0,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["s142",1,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["s143",5,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["s144",6,"inbound","late","nloch","ag","crew",null,0,0,null],
    ["s145",4,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["s146",0,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["s147",5,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["s148",6,"inbound","night","blupin","perm","lead","unload",0,0,null],
    ["s149",4,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["s150",0,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["s151",1,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["s152",6,"inbound","night","jmarram","perm","deputy","unload",0,0,null],
    ["s153",4,"inbound","night","smeadow","perm","crew","unload",0,2,false],
    ["s154",3,"inbound","night","smeadow","perm","acting","unload",0,0,null],
    ["s155",5,"inbound","night","smeadow","perm","crew","unload",0,0,null],
    ["s156",6,"inbound","night","smeadow","perm","crew","rcvqa",0,0,null],
    ["s157",4,"inbound","night","emere","ag","crew",null,0,0,null],
    ["s158",1,"inbound","night","emere","ag","crew",null,0,0,null],
    ["s159",2,"inbound","night","emere","ag","crew",null,0,0,null],
    ["s160",3,"inbound","night","emere","ag","crew",null,0,0,null],
    ["s161",5,"inbound","night","emere","ag","crew",null,0,0,null],
    ["s162",4,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["s163",0,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["s164",1,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["s165",5,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["s166",6,"inbound","night","mnettle","ag","crew",null,0,0,null],
    ["s167",4,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["s168",1,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["s169",2,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["s170",3,"picking","early","aosier","perm","lead","pick",0,0,null],
    ["s171",4,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["s172",0,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["s173",1,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["s174",2,"picking","early","hpebble","perm","deputy","pick",0,0,null],
    ["s175",4,"picking","early","rplover","perm","crew","pick",0,0,null],
    ["s176",0,"picking","early","rplover","perm","crew","pick",0,0,null],
    ["s177",1,"picking","early","rplover","perm","crew","pick",0,0,null],
    ["s178",5,"picking","early","rplover","perm","acting","pick",0,0,null],
    ["s179",6,"picking","early","rplover","perm","acting","pick",0,0,null],
    ["s180",4,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["s181",1,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["s182",2,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["s183",3,"picking","early","dquarry","perm","crew",null,0,0,null],
    ["s184",4,"picking","early","lrill","perm","crew","pick",0,0,null],
    ["s185",0,"picking","early","lrill","perm","crew",null,0,0,null],
    ["s186",1,"picking","early","lrill","perm","crew",null,0,0,null],
    ["s187",2,"picking","early","lrill","perm","crew","pick",0,0,null],
    ["s188",6,"picking","early","lrill","perm","crew","pick",0,0,null],
    ["s189",4,"picking","early","wrowan","perm","crew","replen",0,0,null],
    ["s190",2,"picking","early","wrowan","perm","crew","replen",0,0,null],
    ["s191",3,"picking","early","wrowan","perm","crew","replen",0,0,null],
    ["s192",5,"picking","early","wrowan","perm","crew",null,0,0,null],
    ["s193",4,"picking","early","grush","perm","crew","replen",0,0,null],
    ["s194",0,"picking","early","grush","perm","crew","replen",0,0,null],
    ["s195",1,"picking","early","grush","perm","crew","replen",0,0,null],
    ["s196",2,"picking","early","grush","perm","crew","replen",0,0,null],
    ["s197",6,"picking","early","grush","perm","crew","replen",0,0,null],
    ["s198",4,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["s199",0,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["s200",1,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["s201",2,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["s202",3,"picking","early","psedge","perm","crew","voice",0,0,null],
    ["s203",4,"picking","early","cshale","perm","crew",null,0,0,null],
    ["s204",0,"picking","early","cshale","perm","crew",null,0,0,null],
    ["s205",1,"picking","early","cshale","perm","crew",null,0,0,null],
    ["s206",2,"picking","early","cshale","perm","crew",null,0,0,null],
    ["s207",6,"picking","early","cshale","perm","crew",null,0,0,null],
    ["s208",4,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["s209",0,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["s210",1,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["s211",6,"picking","early","kshingle","perm","crew",null,0,0,null],
    ["s212",4,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["s213",2,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["s214",3,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["s215",5,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["s216",6,"picking","early","tsorrel","ag","crew",null,0,0,null],
    ["s217",4,"picking","early",null,"request","crew",null,0,0,null],
    ["s218",4,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["s219",2,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["s220",3,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["s221",5,"picking","late","fspinney","perm","lead","general",0,0,null],
    ["s222",4,"picking","late","nsprig","perm","deputy","replen",0,0,null],
    ["s223",3,"picking","late","nsprig","perm","deputy",null,0,0,null],
    ["s224",5,"picking","late","nsprig","perm","deputy",null,0,0,null],
    ["s225",6,"picking","late","nsprig","perm","deputy","general",0,0,null],
    ["s226",4,"picking","late","bswale","perm","crew","general",0,0,null],
    ["s227",0,"picking","late","bswale","perm","acting","general",0,0,null],
    ["s228",1,"picking","late","bswale","perm","acting","general",0,0,null],
    ["s229",2,"picking","late","bswale","perm","crew",null,0,0,null],
    ["s230",6,"picking","late","bswale","perm","crew","general",0,0,null],
    ["s231",4,"picking","late","jtansy","perm","crew","pick",0,2,true],
    ["s232",0,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["s233",1,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["s234",5,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["s235",6,"picking","late","jtansy","perm","crew","pick",0,0,null],
    ["s236",4,"picking","late","steasel","perm","crew","pick",0,0,null],
    ["s237",0,"picking","late","steasel","perm","crew","voice",0,0,null],
    ["s238",3,"picking","late","steasel","perm","crew",null,0,0,null],
    ["s239",5,"picking","late","steasel","perm","crew","voice",0,0,null],
    ["s240",6,"picking","late","steasel","perm","crew","voice",0,0,null],
    ["s241",4,"picking","late","ethistle","perm","crew","voice",0,0,null],
    ["s242",0,"picking","late","ethistle","perm","crew",null,0,0,null],
    ["s243",5,"picking","late","ethistle","perm","crew",null,0,0,null],
    ["s244",6,"picking","late","ethistle","perm","crew",null,0,0,null],
    ["s245",4,"picking","late","mtor","ag","crew",null,0,0,null],
    ["s246",0,"picking","late","mtor","ag","crew",null,0,0,null],
    ["s247",1,"picking","late","mtor","ag","crew",null,0,0,null],
    ["s248",2,"picking","late","mtor","ag","crew",null,0,0,null],
    ["s249",6,"picking","late","mtor","ag","crew",null,0,0,null],
    ["s250",4,"picking","late",null,"request","crew",null,0,0,null],
    ["s251",4,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["s252",0,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["s253",1,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["s254",2,"picking","night","atarn","perm","lead","pick",0,0,null],
    ["s255",4,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["s256",3,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["s257",5,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["s258",6,"picking","night","hvetch","perm","deputy","general",0,0,null],
    ["s259",4,"picking","night","rwold","perm","crew","general",0,0,null],
    ["s260",0,"picking","night","rwold","perm","crew","general",0,0,null],
    ["s261",1,"picking","night","rwold","perm","crew","general",0,0,null],
    ["s262",5,"picking","night","rwold","perm","crew",null,0,0,null],
    ["s263",6,"picking","night","rwold","perm","crew","general",0,0,null],
    ["s264",4,"picking","night","dyarrow","ag","crew","general",0,0,null],
    ["s265",0,"picking","night","dyarrow","ag","crew","general",0,0,null],
    ["s266",1,"picking","night","dyarrow","ag","crew","general",0,0,null],
    ["s267",5,"picking","night","dyarrow","ag","crew",null,0,0,null],
    ["s268",6,"picking","night","dyarrow","ag","crew",null,0,0,null],
    ["s269",4,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["s270",0,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["s271",1,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["s272",2,"picking","night","lbramble","ag","crew","general",0,0,null],
    ["s273",3,"picking","night","lbramble","ag","crew",null,0,0,null],
    ["s274",4,"dispatch","early","wcopse","perm","crew","pack",0,0,null],
    ["s275",0,"dispatch","early","wcopse","perm","crew","pack",0,0,null],
    ["s276",1,"dispatch","early","wcopse","perm","acting","pack",0,0,null],
    ["s277",2,"dispatch","early","wcopse","perm","acting","pack",0,0,null],
    ["s278",6,"dispatch","early","wcopse","perm","crew","pack",0,0,null],
    ["s279",4,"dispatch","early","gember","perm","crew","label",0,0,null],
    ["s280",0,"dispatch","early","gember","perm","crew","pack",0,0,null],
    ["s281",1,"dispatch","early","gember","perm","crew","label",0,0,null],
    ["s282",5,"dispatch","early","gember","perm","crew","pack",0,0,null],
    ["s283",6,"dispatch","early","gember","perm","crew","label",0,0,null],
    ["s284",4,"dispatch","early","pgarnet","perm","crew","returns",0,0,null],
    ["s285",0,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["s286",1,"dispatch","early","pgarnet","perm","crew","returns",0,0,null],
    ["s287",2,"dispatch","early","pgarnet","perm","crew","label",0,0,null],
    ["s288",3,"dispatch","early","pgarnet","perm","acting",null,0,0,null],
    ["s289",4,"dispatch","early","charrow","perm","crew",null,0,0,null],
    ["s290",0,"dispatch","early","charrow","perm","crew","load",0,0,null],
    ["s291",5,"dispatch","early","charrow","perm","crew",null,0,0,null],
    ["s292",6,"dispatch","early","charrow","perm","crew","returns",0,0,null],
    ["s293",4,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["s294",2,"dispatch","early","kjasper","perm","crew","returns",0,0,null],
    ["s295",3,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["s296",5,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["s297",6,"dispatch","early","kjasper","perm","crew",null,0,0,null],
    ["s298",4,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["s299",0,"dispatch","early","tkelp","perm","crew","admin",0,0,null],
    ["s300",1,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["s301",2,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["s302",6,"dispatch","early","tkelp","perm","crew",null,0,0,null],
    ["s303",4,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["s304",0,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["s305",1,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["s306",2,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["s307",6,"dispatch","early","flichen","ag","crew",null,0,0,null],
    ["s308",0,"inbound","night","nochre","perm","crew","rcvqa",0,0,null],
    ["s309",1,"inbound","night","nochre","perm","crew","unload",0,0,null],
    ["s310",2,"inbound","night","nochre","perm","acting","unload",0,0,null],
    ["s311",1,"picking","night","bpumice","perm","crew",null,0,0,null],
    ["s312",2,"picking","night","bpumice","perm","crew","general",0,0,null],
    ["s313",6,"picking","night","bpumice","perm","crew","pick",0,0,null],
    ["s314",0,"dispatch","early","jquartz","perm","deputy","returns",0,0,null],
    ["s315",5,"dispatch","early","jquartz","perm","deputy",null,0,0,null],
    ["s316",6,"dispatch","early","jquartz","perm","deputy",null,0,0,null],
];
const currentTargets: readonly (readonly [number, string, string, number, Readonly<Record<string, number>>])[] = [
    [0,"inbound","early",11,{"unload":20,"putaway":13,"reach":13,"xdock":20,"rcvqa":13,"yard":6}],
    [1,"inbound","early",13,{"unload":23,"putaway":16,"reach":15,"xdock":23,"rcvqa":15,"yard":8}],
    [2,"inbound","early",14,{"unload":25,"putaway":17,"reach":16,"xdock":25,"rcvqa":16,"yard":8}],
    [3,"inbound","early",12,{"unload":21,"putaway":15,"reach":14,"xdock":21,"rcvqa":14,"yard":7}],
    [4,"inbound","early",19,{"unload":34,"putaway":23,"reach":22,"xdock":34,"rcvqa":22,"yard":11}],
    [5,"inbound","early",8,{"unload":14,"putaway":8,"reach":9,"xdock":14,"rcvqa":9,"yard":5}],
    [6,"inbound","early",12,{"unload":21,"putaway":8,"reach":14,"xdock":21,"rcvqa":14,"yard":7}],
    [0,"inbound","late",10,{"unload":23,"xdock":23,"rcvqa":23,"yard":12}],
    [1,"inbound","late",10,{"unload":23,"xdock":23,"rcvqa":23,"yard":12}],
    [2,"inbound","late",7,{"unload":16,"xdock":16,"rcvqa":16,"yard":8}],
    [3,"inbound","late",7,{"unload":16,"xdock":16,"rcvqa":16,"yard":8}],
    [4,"inbound","late",12,{"unload":28,"xdock":28,"rcvqa":28,"yard":14}],
    [5,"inbound","late",4,{"unload":9,"xdock":8,"yard":5}],
    [6,"inbound","late",7,{"unload":16,"xdock":16,"rcvqa":16,"yard":8}],
    [0,"inbound","night",4,{"unload":21,"rcvqa":12}],
    [1,"inbound","night",4,{"unload":16,"rcvqa":12}],
    [2,"inbound","night",2,{"unload":8,"rcvqa":6}],
    [3,"inbound","night",2,{"unload":8,"rcvqa":6}],
    [4,"inbound","night",6,{"unload":32,"rcvqa":18}],
    [5,"inbound","night",4,{"unload":16,"rcvqa":8}],
    [6,"inbound","night",4,{"unload":21,"rcvqa":12}],
    [0,"picking","early",7,{"pick":22,"voice":14,"replen":14,"cold":4,"general":4}],
    [1,"picking","early",9,{"pick":28,"voice":18,"replen":16,"cold":5,"general":5}],
    [2,"picking","early",9,{"pick":28,"voice":16,"replen":18,"cold":5,"general":5}],
    [3,"picking","early",5,{"pick":15,"voice":10,"replen":8,"cold":3,"general":3}],
    [4,"picking","early",12,{"pick":37,"voice":24,"replen":24,"cold":6,"general":7}],
    [5,"picking","early",3,{"pick":9,"voice":6,"replen":6,"cold":2,"general":2}],
    [6,"picking","early",7,{"pick":16,"voice":8,"replen":8,"cold":4,"general":4}],
    [0,"picking","late",5,{"pick":10,"voice":9,"cold":4,"general":13}],
    [1,"picking","late",4,{"pick":8,"cold":4,"general":11}],
    [2,"picking","late",3,{"cold":3,"general":8}],
    [3,"picking","late",3,{"pick":6,"voice":5,"replen":3,"cold":3,"general":8}],
    [4,"picking","late",8,{"pick":16,"voice":14,"replen":8,"cold":7,"general":21}],
    [5,"picking","late",5,{"pick":10,"voice":9,"replen":5,"cold":4,"general":13}],
    [6,"picking","late",7,{"pick":14,"voice":12,"replen":7,"cold":6,"general":18}],
    [0,"picking","night",4,{"pick":8,"cold":5,"general":17}],
    [1,"picking","night",5,{"pick":13,"cold":6,"general":21}],
    [2,"picking","night",4,{"pick":11,"cold":5,"general":17}],
    [3,"picking","night",2,{"cold":2,"general":8}],
    [4,"picking","night",6,{"pick":16,"cold":7,"general":25}],
    [5,"picking","night",3,{"cold":4,"general":13}],
    [6,"picking","night",4,{"pick":8,"cold":5,"general":17}],
    [0,"dispatch","early",8,{"pack":17,"load":8,"label":13,"returns":13,"admin":8,"hazmat":8}],
    [1,"dispatch","early",5,{"pack":11,"load":5,"label":8,"returns":8,"admin":5,"hazmat":5}],
    [2,"dispatch","early",5,{"pack":8,"load":5,"label":8,"returns":8,"admin":5,"hazmat":5}],
    [3,"dispatch","early",2,{"label":3,"returns":3,"admin":2}],
    [4,"dispatch","early",7,{"pack":15,"load":7,"label":11,"returns":11,"admin":7,"hazmat":7}],
    [5,"dispatch","early",4,{"pack":9,"load":4,"label":6,"returns":6,"admin":4}],
    [6,"dispatch","early",7,{"pack":15,"load":7,"label":11,"returns":11,"admin":7,"hazmat":7}],
    [0,"dispatch","late",0,{}],
    [1,"dispatch","late",0,{}],
    [2,"dispatch","late",0,{}],
    [3,"dispatch","late",0,{}],
    [4,"dispatch","late",0,{}],
    [5,"dispatch","late",0,{}],
    [6,"dispatch","late",0,{}],
    [0,"dispatch","night",0,{}],
    [1,"dispatch","night",0,{}],
    [2,"dispatch","night",0,{}],
    [3,"dispatch","night",0,{}],
    [4,"dispatch","night",0,{}],
    [5,"dispatch","night",0,{}],
    [6,"dispatch","night",0,{}],
];
function seededWeek(rows: readonly SeedRow[], targets: typeof currentTargets, published: boolean): ValueTypeOf<typeof Roster.Types.Week> {
    return { status: published ? variant("published", { at: new Date("2028-03-04T12:00:00Z") }) : variant("draft", null),
        assignments: new SortedMap(rows.map(([id, day, group, shift, person, kind, position, activity, offset, overtime, agreed]) => [id, {
            slot: { day: BigInt(day), group, shift }, who: kind === "request" ? variant("request", "northside") : variant("person", person!), position,
            activity: activity === null ? none : some(activity), offset, overtime, agreed: agreed === null ? none : some(agreed),
        }] as const), stringOrder),
        requirements: new SortedMap(targets.map(([day, group, shift, positions, hours]) => [{ day: BigInt(day), group, shift }, { positions: BigInt(positions), hours: new SortedMap(Object.entries(hours), stringOrder) }] as const), compareFor(Roster.Types.Slot)),
        dismissed: new SortedSet([], stringOrder),
    };
}
export const warehouseWeek: ValueTypeOf<typeof Roster.Types.Week> = seededWeek(currentRows, currentTargets, false);
export const warehousePrevious: ValueTypeOf<typeof Roster.Types.Week> = seededWeek(previousRows, previousTargets, true);
export const warehouseWeeks: ValueTypeOf<typeof Roster.Types.Weeks> = new SortedMap([[new Date("2028-02-27T00:00:00Z"), warehousePrevious], [warehouseStart, warehouseWeek]], compareFor(DateTimeType));
export const warehouseForecast: Map<Date, ValueTypeOf<typeof Roster.Types.Requirements>> = new SortedMap([[new Date("2028-03-12T00:00:00Z"), warehouseWeek.requirements]], compareFor(DateTimeType));
export const warehouseProposals: ValueTypeOf<typeof Roster.Types.Proposal>[] = [
    { key: "s317", week: warehouseStart, slot: { day: 4n, group: "inbound", shift: "night" }, person: "nochre", reason: "Off Thursday · cover the open night position" },
    { key: "s318", week: warehouseStart, slot: { day: 4n, group: "picking", shift: "night" }, person: "bpumice", reason: "Off Thursday · cover the open night position" },
];
