#
# Copyright (c) 2025 Elara AI Pty Ltd
# Licensed under the Business Source License 1.1. See LICENSE.md for details.
#
"""``east-py transpile`` (#627): an IR file printed as python builder source
that rebuilds the same IR."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from east.runtime._compiler_eastc import diff_ir

from east_py_cli.loader import load_ir

FIXTURES = Path(__file__).parent / "fixtures"


def _run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, "-m", "east_py_cli", *args],
                          capture_output=True, text=True, check=False)


def test_transpile_writes_a_module_that_rebuilds_the_ir(tmp_path):
    src = FIXTURES / "zero_param.beast2"
    out = tmp_path / "zero_param.py"
    result = _run("transpile", str(src), "-o", str(out), "--name", "program")
    assert result.returncode == 0, result.stderr
    text = out.read_text(encoding="utf-8")
    assert "program = East." in text
    namespace: dict = {}
    exec(compile(text, str(out), "exec"), namespace)
    assert diff_ir(load_ir(src), namespace["program"]._east_ir) is None


def test_transpile_prints_to_stdout_by_default():
    result = _run("transpile", str(FIXTURES / "zero_param.beast2"))
    assert result.returncode == 0, result.stderr
    assert result.stdout.startswith("# Generated by east-py transpile")


def test_transpile_reports_a_missing_file():
    result = _run("transpile", "/nonexistent/program.json")
    assert result.returncode == 1
    assert "Error" in result.stderr
