#
# Copyright (c) 2025 Elara AI Pty Ltd
# Licensed under the Business Source License 1.1. See LICENSE.md for details.
#
"""``east-py transpile`` (#627): an IR file printed as python builder source
that rebuilds the same IR."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from east.runtime._compiler_eastc import diff_ir

from east_py_cli.loader import load_ir

FIXTURES = Path(__file__).parent / "fixtures"


def _run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, "-m", "east_py_cli", *args],
                          capture_output=True, text=True, check=False)


def test_transpile_writes_a_module_that_rebuilds_the_ir(tmp_path):
    src = FIXTURES / "zero_param.beast2"
    out = tmp_path / "zero_param.py"
    result = _run("transpile", str(src), "-o", str(out), "--name", "program")
    assert result.returncode == 0, result.stderr
    text = out.read_text(encoding="utf-8")
    assert "@East.function(" in text and "\ndef program(b" in text
    namespace: dict = {}
    exec(compile(text, str(out), "exec"), namespace)
    assert diff_ir(load_ir(src), namespace["program"]._east_ir) is None


def test_transpile_prints_to_stdout_by_default():
    result = _run("transpile", str(FIXTURES / "zero_param.beast2"))
    assert result.returncode == 0, result.stderr
    assert result.stdout.startswith("# Generated by east-py transpile")


def test_transpile_reports_a_missing_file():
    result = _run("transpile", "/nonexistent/program.json")
    assert result.returncode == 1
    assert "Error" in result.stderr


def test_transpile_accepts_the_examples_export_record(tmp_path):
    """`npm run export:examples` writes {ir, source_map, inputs, returns, …}:
    the extra keys must not stop the loader."""
    import json

    from east.serialization.json import encode_json_for
    from east.types.type_of_type import IRType

    ir = load_ir(FIXTURES / "zero_param.beast2")
    encoded = encode_json_for(IRType)(ir)
    encoded = encoded.decode("utf-8") if isinstance(encoded, bytes) else encoded
    record = tmp_path / "example.json"
    record.write_text(json.dumps({
        "suite": "x", "name": "y", "description": "d", "keywords": [], "inputs": [],
        "returns": None, "async": False, "ir": json.loads(encoded),
        "source_map": {"stacks": []},
    }), encoding="utf-8")
    result = _run("transpile", str(record), "--name", "ex")
    assert result.returncode == 0, result.stderr
    namespace: dict = {}
    exec(compile(result.stdout, "example.py", "exec"), namespace)
    assert diff_ir(ir, namespace["ex"]._east_ir) is None


def test_transpile_imports_a_providers_implementation_with_p(tmp_path):
    """``-p east-py-std``: a platform call the package implements prints as
    the package's own function, not a restated declaration (#667)."""
    from east import East, IntegerType, StringType
    from east.serialization.beast2 import encode_beast2_with_header_for
    from east.types.type_of_type import IRType
    from east_py_std import fs_read_file_bytes

    size = East.function([StringType], IntegerType, lambda b, p: fs_read_file_bytes(p).size())
    ir_file = tmp_path / "size.beast2"
    ir_file.write_bytes(encode_beast2_with_header_for(IRType)(size._east_ir))
    result = _run("transpile", str(ir_file), "-p", "east-py-std", "--name", "size")
    assert result.returncode == 0, result.stderr
    assert "from east_py_std import fs_read_file_bytes" in result.stdout
    assert "East.platform(" not in result.stdout
    namespace: dict = {}
    exec(compile(result.stdout, "size.py", "exec"), namespace)
    assert diff_ir(size._east_ir, namespace["size"]._east_ir) is None
    plain = _run("transpile", str(ir_file), "--name", "size")
    assert "fs_read_file_bytes = East.platform(" in plain.stdout
    missing = _run("transpile", str(ir_file), "-p", "no-such-package")
    assert missing.returncode == 1 and "no_such_package" in missing.stderr
