/**
 * Copyright (c) 2025 Elara AI Pty Ltd
 * Licensed under BSL 1.1. See LICENSE for details.
 */

/**
 * API types for e3-api-client.
 *
 * Re-exports all API wire types from @elaraai/e3-types (the single source of truth).
 * Types with "Api" prefix in e3-types are re-exported here with shorter names
 * since API consumers don't see the conflicting domain types.
 */

// API wire types — re-export from @elaraai/e3-types
export {
  // Error types
  WorkspaceNotFoundErrorType,
  WorkspaceNotDeployedErrorType,
  WorkspaceExistsErrorType,
  LockHolderType,
  WorkspaceLockedErrorType,
  PackageNotFoundErrorType,
  PackageExistsErrorType,
  PackageInvalidErrorType,
  DatasetNotFoundErrorType,
  TaskNotFoundErrorType,
  ExecutionNotFoundErrorType,
  ObjectNotFoundErrorType,
  DataflowErrorType,
  PermissionDeniedErrorType,
  InternalErrorType,
  RepositoryNotFoundErrorType,
  ErrorType,
  ResponseType,
  // Repository
  RepositoryStatusType,
  GcRequestType,
  GcResultType,
  AsyncOperationStatusType,
  GcStartResultType,
  GcStatusResultType,
  // Packages
  PackageListItemType,
  PackageImportResultType,
  PackageInfoType,
  PackageDetailsType,
  // Workspaces
  WorkspaceCreateRequestType,
  WorkspaceInfoType,
  SchemaPolicyType,
  InputPolicyType,
  WorkspaceDeployRequestType,
  RecordPlanType,
  RecordIndexPlanType,
  InputPlanType,
  WorkspaceDeployResultType,
  WorkspaceDeployProgressType,
  WorkspaceDeployStatusType,
  WorkspaceExportRequestType,
  LockStatusType,
  // Workspace Status
  DatasetStatusType,
  TaskStatusUpToDateType,
  TaskStatusWaitingType,
  TaskStatusInProgressType,
  TaskStatusFailedType,
  TaskStatusErrorType,
  TaskStatusStaleRunningType,
  TaskStatusType,
  DatasetStatusInfoType,
  TaskStatusInfoType,
  WorkspaceStatusSummaryType,
  WorkspaceStatusResultType,
  // Tasks
  TaskListItemType,
  TaskDetailsType,
  // Execution
  DataflowRequestType,
  LogChunkType,
  TaskLogChunkType,
  TaskExecutionResultType,
  DataflowResultType,
  // Dataflow API polling
  DataflowEventType,
  ApiExecutionStatusType as ExecutionStatusType,
  DataflowExecutionSummaryType,
  DataflowBudgetType,
  UnitWaitType,
  SplitProgressType,
  ApiDataflowExecutionStateType as DataflowExecutionStateType,
  // Task Execution History
  ExecutionHistoryStatusType,
  ExecutionListItemType,
  TASK_EXECUTIONS_PAGE_DEFAULT,
  TASK_EXECUTIONS_PAGE_MAX,
  // Dataset List
  TreeKindType,
  ListEntryType,
  // Dataset Status Detail
  DatasetStatusDetailType,
  // Transfer types
  TransferUploadRequestType,
  TransferUploadResponseType,
  TransferPartResponseType,
  TransferDoneResponseType,
  PackageImportStatusType,
  PackageExportStatusType,
  // Function / one-shot execution
  RunnerType,
  ExecuteLimitsType,
  DiagnosticType,
  ExecuteResultType,
  CallArgType,
  FunctionCallRequestType,
  FunctionSignatureType,
  OneShotRequestType,
  // Split calls
  SplitCallArgType,
  SplitCallRequestType,
  SplitCallProgressType,
  SplitCallStatusType,
  SplitCallPlanType,
  MutationCallRequestType,
  MutationResultType,
  RecordMigrationAppliedType,
  RecordSignatureType,
  RecordCommitInfoType,
  RecordArgPreviewType,
  RecordCommitArgsType,
  RecordHistoryCommitType,
  RecordHistoryResultType,
  RECORD_ARG_TEXT_CHARS,
  RECORD_ARG_TEXT_BYTES,
  RECORD_ARGS_READ_BYTES,
  // Graph types (from dataflow.ts, structurally identical to old API GraphTaskType)
  DataflowGraphType,
  DataflowGraphTaskType,
} from '@elaraai/e3-types';

// Value type aliases — re-export from @elaraai/e3-types
export type {
  Error,
  RepositoryStatus,
  GcRequest,
  GcResult,
  AsyncOperationStatus,
  GcStartResult,
  GcStatusResult,
  PackageListItem,
  PackageImportResult,
  PackageInfo,
  PackageDetails,
  WorkspaceInfo,
  WorkspaceCreateRequest,
  WorkspaceDeployRequest,
  SchemaPolicy,
  InputPolicy,
  RecordPlan,
  RecordIndexPlan,
  InputPlan,
  WorkspaceDeployResult,
  WorkspaceDeployProgress,
  WorkspaceDeployStatus,
  LockStatus,
  LockProgress,
  DeployProgress,
  RecordDeployState,
  RecordDeployStep,
  IntakeFile,
  IntakeStep,
  DatasetStatus,
  ApiTaskStatus as TaskStatus,
  DatasetStatusInfo,
  TaskStatusInfo,
  WorkspaceStatusSummary,
  WorkspaceStatusResult,
  TaskListItem,
  TaskDetails,
  DataflowRequest,
  LogChunk,
  TaskLogChunk,
  TaskExecutionResult,
  DataflowResult,
  DataflowEvent,
  ApiExecutionStatus as ExecutionStatus,
  DataflowExecutionSummary,
  DataflowBudget,
  UnitWait,
  SplitProgress,
  StageUnit,
  RequeueReason,
  ApiDataflowExecutionState as DataflowExecutionState,
  ExecutionHistoryStatus,
  ExecutionListItem,
  TreeKind,
  ListEntry,
  DatasetStatusDetail,
  TransferUploadRequest,
  TransferUploadResponse,
  TransferPartResponse,
  TransferDoneResponse,
  PackageImportStatus,
  PackageExportStatus,
  RunnerValue,
  ExecuteLimits,
  Diagnostic,
  ExecuteResult,
  CallArg,
  FunctionCallRequest,
  FunctionSignature,
  OneShotRequest,
  SplitCallArg,
  SplitCallRequest,
  SplitCallProgress,
  SplitCallStatus,
  SplitCallPlan,
  MutationCallRequest,
  MutationResult,
  RecordMigrationApplied,
  RecordSignature,
  RecordCommitInfo,
  RecordArgPreview,
  RecordCommitArgs,
  RecordHistoryCommit,
  RecordHistoryResult,
  DataflowGraph,
  DataflowGraphTask,
} from '@elaraai/e3-types';

// =============================================================================
// Namespace export for convenience
// =============================================================================

import {
  ErrorType,
  RepositoryNotFoundErrorType,
  WorkspaceNotFoundErrorType,
  WorkspaceNotDeployedErrorType,
  WorkspaceExistsErrorType,
  WorkspaceLockedErrorType,
  LockHolderType,
  PackageNotFoundErrorType,
  PackageExistsErrorType,
  PackageInvalidErrorType,
  DatasetNotFoundErrorType,
  TaskNotFoundErrorType,
  ExecutionNotFoundErrorType,
  ObjectNotFoundErrorType,
  DataflowErrorType,
  PermissionDeniedErrorType,
  InternalErrorType,
  ResponseType,
  RepositoryStatusType,
  GcRequestType,
  GcResultType,
  AsyncOperationStatusType,
  GcStartResultType,
  GcStatusResultType,
  PackageListItemType,
  PackageImportResultType,
  PackageInfoType,
  PackageDetailsType,
  WorkspaceCreateRequestType,
  WorkspaceInfoType,
  SchemaPolicyType,
  InputPolicyType,
  WorkspaceDeployRequestType,
  RecordPlanType,
  RecordIndexPlanType,
  InputPlanType,
  WorkspaceDeployResultType,
  WorkspaceDeployProgressType,
  WorkspaceDeployStatusType,
  WorkspaceExportRequestType,
  LockStatusType,
  DatasetStatusType,
  TaskStatusType,
  TaskStatusUpToDateType,
  TaskStatusWaitingType,
  TaskStatusInProgressType,
  TaskStatusFailedType,
  TaskStatusErrorType,
  TaskStatusStaleRunningType,
  DatasetStatusInfoType,
  TaskStatusInfoType,
  WorkspaceStatusSummaryType,
  WorkspaceStatusResultType,
  TaskListItemType,
  TaskDetailsType,
  DataflowRequestType,
  DataflowGraphType,
  DataflowGraphTaskType,
  LogChunkType,
  TaskLogChunkType,
  TaskExecutionResultType,
  DataflowResultType,
  DataflowEventType,
  ApiExecutionStatusType,
  DataflowExecutionSummaryType,
  DataflowBudgetType,
  UnitWaitType,
  SplitProgressType,
  ApiDataflowExecutionStateType,
  ExecutionHistoryStatusType,
  ExecutionListItemType,
  TreeKindType,
  ListEntryType,
  DatasetStatusDetailType,
  TransferUploadRequestType,
  TransferUploadResponseType,
  TransferPartResponseType,
  TransferDoneResponseType,
  PackageImportStatusType,
  PackageExportStatusType,
  RunnerType as _RunnerType,
  ExecuteLimitsType as _ExecuteLimitsType,
  DiagnosticType as _DiagnosticType,
  ExecuteResultType as _ExecuteResultType,
  CallArgType as _CallArgType,
  FunctionCallRequestType as _FunctionCallRequestType,
  FunctionSignatureType as _FunctionSignatureType,
  OneShotRequestType as _OneShotRequestType,
  SplitCallArgType as _SplitCallArgType,
  SplitCallRequestType as _SplitCallRequestType,
  SplitCallProgressType as _SplitCallProgressType,
  SplitCallStatusType as _SplitCallStatusType,
  SplitCallPlanType as _SplitCallPlanType,
} from '@elaraai/e3-types';

export const ApiTypes = {
  // Errors
  ErrorType,
  RepositoryNotFoundErrorType,
  WorkspaceNotFoundErrorType,
  WorkspaceNotDeployedErrorType,
  WorkspaceExistsErrorType,
  WorkspaceLockedErrorType,
  LockHolderType,
  PackageNotFoundErrorType,
  PackageExistsErrorType,
  PackageInvalidErrorType,
  DatasetNotFoundErrorType,
  TaskNotFoundErrorType,
  ExecutionNotFoundErrorType,
  ObjectNotFoundErrorType,
  DataflowErrorType,
  PermissionDeniedErrorType,
  InternalErrorType,

  // Response
  ResponseType,

  // Repository
  RepositoryStatusType,
  GcRequestType,
  GcResultType,

  // Async Operations
  AsyncOperationStatusType,
  GcStartResultType,
  GcStatusResultType,

  // Packages
  PackageListItemType,
  PackageImportResultType,
  PackageInfoType,
  PackageDetailsType,

  // Workspaces
  WorkspaceCreateRequestType,
  WorkspaceInfoType,
  SchemaPolicyType,
  InputPolicyType,
  WorkspaceDeployRequestType,
  RecordPlanType,
  RecordIndexPlanType,
  InputPlanType,
  WorkspaceDeployResultType,
  WorkspaceDeployProgressType,
  WorkspaceDeployStatusType,
  WorkspaceExportRequestType,
  LockStatusType,

  // Workspace Status
  DatasetStatusType,
  TaskStatusType,
  TaskStatusUpToDateType,
  TaskStatusWaitingType,
  TaskStatusInProgressType,
  TaskStatusFailedType,
  TaskStatusErrorType,
  TaskStatusStaleRunningType,
  DatasetStatusInfoType,
  TaskStatusInfoType,
  WorkspaceStatusSummaryType,
  WorkspaceStatusResultType,

  // Tasks
  TaskListItemType,
  TaskDetailsType,

  // Execution
  DataflowRequestType,
  DataflowGraphType,
  DataflowGraphTaskType,
  LogChunkType,
  TaskLogChunkType,
  TaskExecutionResultType,
  DataflowResultType,

  // Execution State (polling)
  DataflowEventType,
  ExecutionStatusType: ApiExecutionStatusType,
  DataflowExecutionSummaryType,
  DataflowBudgetType,
  UnitWaitType,
  SplitProgressType,
  DataflowExecutionStateType: ApiDataflowExecutionStateType,

  // Task Execution History
  ExecutionHistoryStatusType,
  ExecutionListItemType,

  // Dataset List (recursive)
  TreeKindType,
  ListEntryType,

  // Dataset Status Detail (single dataset)
  DatasetStatusDetailType,

  // Transfer
  TransferUploadRequestType,
  TransferUploadResponseType,
  TransferPartResponseType,
  TransferDoneResponseType,
  PackageImportStatusType,
  PackageExportStatusType,

  // Function / one-shot execution
  RunnerType: _RunnerType,
  ExecuteLimitsType: _ExecuteLimitsType,
  DiagnosticType: _DiagnosticType,
  ExecuteResultType: _ExecuteResultType,
  CallArgType: _CallArgType,
  FunctionCallRequestType: _FunctionCallRequestType,
  FunctionSignatureType: _FunctionSignatureType,
  OneShotRequestType: _OneShotRequestType,

  // Split calls
  SplitCallArgType: _SplitCallArgType,
  SplitCallRequestType: _SplitCallRequestType,
  SplitCallProgressType: _SplitCallProgressType,
  SplitCallStatusType: _SplitCallStatusType,
  SplitCallPlanType: _SplitCallPlanType,
} as const;
